### ISSUE TITLE
[agw][orc8r] Log and exception handling audit in Python code

### ISSUE THREAD

**Issue by alexzurbonsen** [magma/magma#10027]
## Goal
 
Audit of logs and exception handling in order to (a) obtain cleaner and clearer logs and error handling and (b) enable Sentry with usable error rate and without performance issues.

## Path

_First step_: Assessment of effort levels for individual services. To that end statistics on the number of log and exception handling statements as well as the overall amount of code are needed.

_Next steps_: Look at error handling in different Python services and enable Sentry if possible.

**Comment by alexzurbonsen** [comment]
**Statistics on logging and exception handling (for Python in AGW and orc8r)**

As a first step you find statistics on the number of log statements, exception handling statements and code size in the tables below. Details are explained in the following and underneath the tables.

General details on counting: We scanned python code in lte/gateway/python/magma and orc8r/gateway/python/magma for the logging and exception handling keywords, ignoring comments and tests directories. Results are reported in two separate tables, one for logging statements and one for exception handling statements.

**Logging**
| directory     | lines of code (Python) | critical | fatal | exception | error | warning | info | debug | total | total >= error | lines with log statements (in %) | fraction of log statements >= error (in %) |
|---------------|------------------------|----------|-------|-----------|-------|---------|------|-------|-------|----------------|----------------------------------|--------------------------------------------|
| pipelined     | 12871                  | 0        | 0     | 6         | 130   | 32      | 61   | 144   | 373   | 136            | 2.90%                            | 36.46%                                     |
| enodebd       | 7053                   | 2        | 0     | 3         | 21    | 32      | 13   | 29    | 100   | 26             | 1.42%                            | 26.00%                                     |
| magmad        | 3888                   | 0        | 0     | 4         | 45    | 12      | 44   | 17    | 122   | 49             | 3.14%                            | 40.16%                                     |
| subscriberdb  | 2938                   | 0        | 1     | 5         | 14    | 13      | 20   | 8     | 61    | 20             | 2.08%                            | 32.79%                                     |
| common        | 2340                   | 0        | 0     | 1         | 13    | 5       | 22   | 3     | 44    | 14             | 1.88%                            | 31.82%                                     |
| mobilityd     | 2220                   | 0        | 0     | 0         | 15    | 11      | 22   | 39    | 87    | 15             | 3.92%                            | 17.24%                                     |
| policydb      | 767                    | 0        | 0     | 0         | 6     | 0       | 9    | 2     | 17    | 6              | 2.22%                            | 35.29%                                     |
| state         | 431                    | 0        | 0     | 0         | 5     | 3       | 8    | 11    | 27    | 5              | 6.26%                            | 18.52%                                     |
| health        | 417                    | 0        | 0     | 0         | 0     | 0       | 1    | 2     | 3     | 0              | 0.72%                            | 0.00%                                      |
| ctraced       | 396                    | 0        | 0     | 0         | 9     | 0       | 8    | 11    | 28    | 9              | 7.07%                            | 32.14%                                     |
| pkt_tester    | 299                    | 0        | 0     | 0         | 0     | 2       | 0    | 0     | 2     | 0              | 0.67%                            | 0.00%                                      |
| configuration | 239                    | 0        | 0     | 0         | 4     | 0       | 1    | 0     | 5     | 4              | 2.09%                            | 80.00%                                     |
| monitord      | 230                    | 0        | 0     | 0         | 1     | 3       | 2    | 3     | 9     | 1              | 3.91%                            | 11.11%                                     |
| directoryd    | 207                    | 0        | 0     | 0         | 5     | 0       | 2    | 4     | 11    | 5              | 5.31%                            | 45.45%                                     |
| eventd        | 190                    | 0        | 0     | 0         | 4     | 0       | 1    | 5     | 10    | 4              | 5.26%                            | 40.00%                                     |
| kernsnoopd    | 164                    | 0        | 0     | 0         | 4     | 0       | 1    | 1     | 6     | 4              | 3.66%                            | 66.67%                                     |
| smsd          | 130                    | 0        | 0     | 0         | 4     | 0       | 3    | 2     | 9     | 4              | 6.92%                            | 44.44%                                     |
| redirectd     | 113                    | 0        | 0     | 0         | 1     | 0       | 1    | 0     | 2     | 1              | 1.77%                            | 50.00%                                     |

*Table 1. Logging.* Code was searched for the seven logging terms "critical, fatal, ... , debug" to capture all kinds of logging statements (logging.error, logger.error and LOG.error). The columns show the respective count. The column "total >= error" shows the sum of "critical", "fatal", "exception" and "error". "lines with log statements" is the result of "total / lines of code" in percent. "fraction of log statements >= error" is the result of "total >= error / total". To prevent a possible source of confusion: the logging terms were searched in case sensitive mode and formatted as ".error(" to exclude unwanted by-catch.

**Exception handling**
| directory     | lines of code (Python) | except | raise | total | total / lines of code (in %) |
|---------------|------------------------|--------|-------|-------|------------------------------|
| pipelined     | 12871                  | 124    | 48    | 172   | 1.34%                        |
| enodebd       | 7053                   | 29     | 39    | 68    | 0.96%                        |
| magmad        | 3888                   | 54     | 29    | 83    | 2.13%                        |
| subscriberdb  | 2938                   | 40     | 70    | 110   | 3.74%                        |
| common        | 2340                   | 32     | 28    | 60    | 2.56%                        |
| mobilityd     | 2220                   | 26     | 27    | 53    | 2.39%                        |
| policydb      | 767                    | 4      | 0     | 4     | 0.52%                        |
| state         | 431                    | 5      | 0     | 5     |                              |
| health        | 417                    | 1      | 0     | 1     | 0.24%                        |
| ctraced       | 396                    | 5      | 1     | 6     | 1.52%                        |
| pkt_tester    | 299                    | 1      | 17    | 18    | 6.02%                        |
| configuration | 239                    | 3      | 5     | 8     | 3.35%                        |
| monitord      | 230                    | 3      | 0     | 3     | 1.30%                        |
| directoryd    | 207                    | 6      | 0     | 6     | 2.90%                        |
| eventd        | 190                    | 4      | 3     | 7     | 3.68%                        |
| kernsnoopd    | 164                    | 6      | 4     | 10    | 6.10%                        |
| smsd          | 130                    | 4      | 0     | 4     | 3.08%                        |
| redirectd     | 113                    | 0      | 0     | 0     | 0.00%                        |

*Table 2. Exception handling.* Code was searched for the two keywords "except" and "raise". Search pattern was " except" in case sensitive mode.

**Comment by jheidbrink** [comment]
# Overview of most frequent Sentry issues from lab so far

Note that currently some high volume Sentry events are filtered, those are not yet considered here.

**(pipelined) [send_periodic_session_update_error](https://sentry.io/organizations/lf-9c/issues/2770940545/)**
- Timeout in gRPC call
- Timeout was set to "5" in August 2021, maybe fix and not deployed yet (?)
- Periodic call to C++ session_manager
- Case that call fails is explicitly handled and errors are counted
  - Should this be log level error? Proposition: Decrease log level in case of timeout, only log error for other errors.

**(magmad) [StateReporting failure likely not due to invalid cert](https://sentry.io/organizations/lf-9c/issues/2770940243/)**
- Error in certificate check of magmad state_reporter#_schedule_bootstrap_if_cert_is_invalid
- Includes other error logs that are filtered out on server
- Set logs to level warning?

**(monitord) [list object is not callable](https://sentry.io/organizations/lf-9c/issues/2770941608/)**
- Already fixed: [https://github.com/magma/magma/pull/10161](https://github.com/magma/magma/pull/10161)

**(subscriberdb) [Sync subscribers request error](https://sentry.io/organizations/lf-9c/issues/2770941398/) / [Check subscribers in sync request error](https://sentry.io/organizations/lf-9c/issues/2770941417/)**
- Errors in subscriberdb talking to cloud
- Internal error is returned → unexpected exception on server (?)

**(pipelined) [ActivateFlows request processing timed out](https://sentry.io/organizations/lf-9c/issues/2771155780/)**
- Timeout error in pipelined ActivateFlows request
- Default timeout was reduced recently [pull/7724](https://github.com/magma/magma/pull/7724), but for other reasons?
 
**(eventd) [Connection to FluentBit failed: ConnectionRefusedError(111, 'Connection refused')](https://sentry.io/organizations/lf-9c/issues/2395399436/)**
- This probably implies some logs don't make it to Elasticsearch

**(magmad) [Upgrade loop failed! Error: Exception('Command failed: git -C /tmp/magma_upgrade/magma checkout 0.0.0-0')](https://sentry.io/organizations/lf-9c/issues/2771068653/)**
- magmad tries git checkout of tag "0.0.0-0"
- Sentry error shows no release version / real tag

**Comment by sebathomas** [comment]
Going through the frequent issues in Sentry shows that many of them are related to technical errors or timeouts in the communication between two services. They are observed 100s or 1,000s of times each day. Additionally, there are some Regex filters applied in the Sentry server that exclude ~500,000 error events per day.

For the events we looked at, it is hard to decide how to handle them without deep knowledge of the system and how the services are supposed to interact. In principle, either they are real errors and should be fixed, or they are part of the normal behavior of the system and should not be listed on Sentry. Even if they are real errors, however, it may make sense to track them in a ticket and still filter them out to avoid the large volume of error logging.

There are several ways to filter events or avoid them on Sentry:

1. Configure an inbound filter for a message pattern on the server or discard it explicitly.
2. Configure an outbound filter for a message pattern in the Python client.
3. Adapt the specific log not to use log level error.
4. Activate opt-in based logging and don't tag the specific log.
5. Deactivate Sentry for the entire service.

To save network traffic and avoid performance issues, it would be good to do the filtering on the client side. There are also a few "429 Too Many Requests" responses from Sentry in the logs, which is another reason to reduce the amount of Sentry issues. Filtering errors on the client side is less flexible than on the server side, however, since the services need to be redeployed. So it cannot completely replace server-side filters. However, it would be good to implement all current server-side filters also on the client side to reduce the request spam (option 1 -> 2 above).

Filtering should be done as specifically as possible, independent of whether errors are excluded on the client or the server side. Otherwise unknown errors can be missed. For this reason, the goal should be to have as many services as possible with Sentry fully enabled, and to use opt-in logging or to disable Sentry only if this is not feasible.

**Comment by sebathomas** [comment]
## Handling of Sentry issues so far

Results from our experiences with going through Sentry issues (#10507)

Frequent Sentry Issues as of 2021-12-23: **20**

Solved:

-   Fix bug **4**
-   Log level change **3**
-   Issue in old version, already solved **1**

Open:

-   Exclude from Sentry **7**
-   Unclear **5**

Half of the solved issues were real bug fixes. Most of the unresolved issues will most likely be resolved by excluding the issue from Sentry. This means that the issue represents an application error that should be visible as error in the logs but does not indicate a bug.

We have not resolved these yet because we're still missing a good option to exclude individual errors from Sentry. Which brings us to...

## Opt-in vs. opt-out

We initially set up the configurable opt-in option for Python services with the expectation that most Python services won\'t be manageable in Sentry at all without that option (due to performance issues or just sending way too many errors). Enabling opt-in mode means that only selected and marked error logs can ever appear in Sentry, which is a significant restriction since monitoring is normally intended to find unknown errors that wouldn't necessarily be marked in advance.

From our experience in the lab so far, enabling Python has gone more smoothly than expected. Opt-in has been used only sporadically, most services are fully enabled on Sentry. While there are a lot of sent issues (and most of them are filtered out on the server), so far no performance problems have been reported and the automatic grouping of issues works well enough that they can be analyzed and fixed.

The obvious alternative to using an opt-in mode that only sends selected errors would be an opt-out option that excludes selected errors.

#### Opt-in
```python
pylogging.error("Something went wrong that absolutely should not happen", extra=SEND_TO_ERROR_MONITORING)
```

#### Opt-out
```python
pylogging.error("Something went wrong but it's not a bug", extra=EXCLUDE_FROM_ERROR_MONITORING)
```

### Introducing opt-out

Pros:

- errors are sent to Sentry per default, i.e. new and unexpected errors are noticed and not filtered out unintentionally
- distinction between application (important for users) and platform errors (important for developers) can be implemented without unintended loss and with high resolution (on the level of single errors)
- no configurability needed

Cons:

- new effort to implement
- cannot exclude errors that are logged in third-party code (those could be handled via opt-in or via filters)

## Proposed solution

Judging from our previous experiences in the lab, we propose to reduce the complexity in Sentry configuration again now that it seems like most of these options are not needed.

- Use only opt-out and filters. Opt-out can be hardcoded in the logging statements, filters can remain configurable via mconfig. Filters allow users to react to new bugs without code changes and additionally could be used to handle errors in third-party libraries (which we haven't really had on Sentry so far).
- Our hope is that all the other options (opt-in, per-service config of Sentry and the decorators) are no longer needed and can be removed.
