### ISSUE TITLE
Provide guidance on path to codeownership

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#10059]
# Provide guidance on path to codeownership

## Problem

Path to becoming a codeowner is implicit, and not well documented, leaving external contributors unclear on which next steps to take.

## Solution

Explicit documentation, in the contributors guide

### Solution text

In order to become a codeowner, you need to be nominated by an existing codeowner and receive a majority vote from the full set of current codeowners. Feel free to start a chat in the #governance-codeowners channel about points of contact for receiving a nomination.

In order to receive a nomination, the project requests the following qualities in relation to the Magma project, with example ways to fulfill 

- Solid contributions history (example: 7+ PRs merged)
- Solid code review history (example: 10+ code reviews)
- Demonstrated ownership of particular component (example: contributions and code review for *sessiond* service)
- Demonstrated technical leadership of particular component (example: driving component design/evolution during code review, and/or through writing 1+ design docs)

Please note that this set of qualities is not an exact requirement -- if you're interested in supporting the project as a codeowner, please reach out! We'd love to work with you, and work on a path toward you becoming a Magma codeowner.

## Non-goals

Provide an explicit, box-ticking rubric that must be followed exactly

**Comment by electronjoe** [comment]
Thanks Hunter for establishing some process here with more detail.

My 2 cents is that we should make it explicit somewhere here that one doesn't need to meet all the criteria. So that people do not hesitate to apply if they miss some categories above.

E.g. I think we would not need every CODEOWNER to have `Demonstrated ownership of particular component` - e.g. we could really use some "Readability" reviewers who are simply demonstrated experts in the programming languages / markdowns of Magma.

**Comment by hcgatewood** [comment]
@electronjoe I think this is a great point and definitely worth discussing. I do think it's a somewhat different topic though -- documenting the path to current definition of codeowner vs. expanding the definition of codeowner

Let's chat about it during next TSC sync
