### ISSUE TITLE
[MME] Memory bloating investigation

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#10122]

**Comment by ssanadhya** [comment]
MME memory footprint keeps on growing during scale tests, and stays high even after all UEs have been detached. Several directions to explore here:
1. Look at the change in Redis database over time since it mirrors in-memory data structure: @ardzoht please add your findings in a comment here
2. Look at dirty pages: @ulaskozat please add your findings in a comment here
3. Profile MME memory usage with Gperf: To do for @ssanadhya

**Comment by ulaskozat** [comment]
On AGW, I sampled dirty pages for the mme process using the following bash command during TC003 10 hour runs:
`for i in {1..1200}; do sudo cat /proc/<mme_process_id>/smaps | grep "Private_Dirty" | awk '{SUM+=$2}END{print SUM}'; sleep 10; done`

A snippet of this sampling is posted here: https://fburl.com/q97kc28m

**Comment by ssanadhya** [comment]
**Benchmarking with TC003 of HIL test suite**

The scenario in TC00 is:
- 300 UEs in total
- Attach rate of 3 UEs per sec
- Switch UEs randomly between active/idle mode
- Send traffic to UE in active mode
- Run simulation for over 12 hours

Running this test case with different Magma versions, the MME memory usage reported by systemd changed as follows:
1. v1.6.1 with _stateless enabled_: MME starts at 28 MB and grows to 400 MB in 4 hours, even when test is stopped, the memory usage stays at 400 MB
2. v1.7 from [master](https://github.com/magma/magma/tree/a5c1867207866946f2d03717e5a88c3ab5b3c4dd) with _stateless enabled_: MME starts at 28 MB and grows to 110 MB in 10 hours, it maxes at 124 MB but stabilizes to 115 MB after test finishes
3. v1.7 from [master](https://github.com/magma/magma/tree/a5c1867207866946f2d03717e5a88c3ab5b3c4dd) with _stateless disabled_: MME starts at 28 MB and grows to 50 MB in four hours, it maxes at 52 MB but stabilizes at 41 MB after test finishes

**Next steps**
-  Create three custom [v1.7](https://github.com/magma/magma/tree/a5c1867207866946f2d03717e5a88c3ab5b3c4dd) MME service executable to have stateless enabled for each of S1AP, MME_app and SPGW threads in MME service and redo the above benchmarking

**Comment by ssanadhya** [comment]
Following up on the previous comment, MME executable with stateless mode for one of S1AP, MME_app and SPGW tasks also showed a memory bloat issue, independent of the task for which stateless mode was enabled. To further understand the memory footprint, I tried following:

### Memory allocation at the end of the test
In the previous experiments, we observed that MME reports a high memory usage even when there is no UE or eNB connected to it. With the help of @sudhikan, I ran the same test case with fewer UEs and dumped the process memory at the end of the test case using `pmap -x <pid>`.
1. 100 UEs at 3UEs per second, switching between active/idle for 300 iterations: 
The total resident memory at the end of the test is 168964 KB, with top 5 owners as:
```
Resident memory in KB
[anonymous] :        129252
mme:                  13376
libfolly.so.57.0.0:    2640
libprotobuf.so.17.0.0: 2560
libcrypto.so.1.1:      2072
```

2. 50 UEs at 3UEs per second, switching between active/idle, for 300 iterations
The total resident memory at the end of the test is  114784 KB, with top 5 owners as:
```
Resident memory in KB
[anonymous] :         75316
mme:                  13376
libfolly.so.57.0.0:    2512
libprotobuf.so.17.0.0: 2508
libcrypto.so.1.1:      2008
```

**Anonymous memory**, which is memory not mapped to any file object, is contributing to > 66% of the process memory consumption when the process is idle. This is _not_ memory allocated to heap or stack. 

To understand where is this memory getting allocated, I tried running MME service with Valgrind, but it significantly slows down the service, leading to failures with 50 or 100 UEs. Next section highlights the observations with 20 UE test case, since it can run with Valgrind.

### Memory allocation during the test

We next run a test scenarios where 20 UEs with attach rate of 1 UE per second randomly switch between active and idle mode. This test case was chosen so that it can run with Valgrind successfully. While running different test scenarios with @sudhikan , we also observed that the memory bloat is a function of the duration of the test case as well, not just the load on the network. Following graphs shows the memory usage for three test runs:

![mem_usage_20UEs_300_600_iters](https://user-images.githubusercontent.com/1519854/151430538-dc53f26a-17a4-4b9a-930d-0653ae96b4f6.png)


1. proc_573586 : 300 iterations of the test case
2. proc_778193 : 600 iterations of the test case
3. proc_682213 : 600 iterations with Valgrind running as
` /usr/bin/valgrind --tool=massif --stacks=yes --keep-debuginfo=yes /usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.conf`

Few observations here:
1. The memory usage with Valgrind is not meaningful since this is memory usage reported for the Valgrind tool itself, which takes the MME executable as an argument. Note that even with 600 iterations, the number of samples for Valgrind are fewer than case 2, since every sample is approximately (not exactly) 20 seconds apart. Hence the x-axis is _not_ absolute time.
2. The initial memory usage for scenario 1 and 2 above is different just because the sample collection started a little early in case 1. The MME at steady state reported about 48 MB memory usage before any control plane request was sent.
3. The peak memory usage for 600 iterations is about 150 MB (up from ~50 MB), while that of 300 iterations is about 100 MB. 
This gives us some leads in how to reproduce this issue.

Further, scenario 3 did generate a _Massif_ report from Valgrind, which is attached in 
[ms_print_massif.out.682213.txt](https://github.com/magma/magma/files/7953313/ms_print_massif.out.682213.txt)
Unfortunately, this report does not present a detailed backtrace of heap allocation from each allocation, since the lower level allocation happens through LibZMQ. Looking at the peak memory allocation snapshot (copied below), of the 6.5 MB heap, more than 57% is through calls to LibZMQ. 

```
95.54% (6,497,307B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->22.24% (1,512,551B) in 1047 places, all below massif's threshold (1.00%)
->17.62% (1,198,560B) 0x71D9E43: ??? (in /usr/lib/x86_64-linux-gnu/libzmq.so.5.2.2)
->14.95% (1,016,800B) 0x71A80B4: ??? (in /usr/lib/x86_64-linux-gnu/libzmq.so.5.2.2)
->14.95% (1,016,800B) 0x71A81E3: ??? (in /usr/lib/x86_64-linux-gnu/libzmq.so.5.2.2)
->06.26% (425,984B) 0x71D3081: ??? (in /usr/lib/x86_64-linux-gnu/libzmq.so.5.2.2)
->04.93% (335,520B) 0x956CCF: sgw_cm_create_bearer_context_information_in_collection (sgw_context_manager.c:143)
->03.08% (209,380B) 0x67B9DFE: gpr_malloc (in /usr/local/lib/libgrpc.so.6.0.0)
->02.89% (196,800B) 0x71A9015: ??? (in /usr/lib/x86_64-linux-gnu/libzmq.so.5.2.2)
->01.91% (130,176B) 0x67B9E5E: gpr_zalloc (in /usr/local/lib/libgrpc.so.6.0.0)
->01.58% (107,200B) 0x32111A: hashtable_ts_init (hashtable.c:221)
->01.51% (102,400B) 0x40A2AF: mme_create_new_ue_context (mme_app_context.c:126)
->01.33% (90,592B) 0x9ED061B: ??? (in /usr/lib/x86_64-linux-gnu/libtasn1.so.6.6.0)
->01.20% (81,840B) 0x71B3961: ??? (in /usr/lib/x86_64-linux-gnu/libzmq.so.5.2.2)
->01.07% (72,704B) 0x6352A99: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
```

The backtrace for calls to libzmq allocations points to:
1. `zsock_new_push` call from `init_task_context` for Main task and MME app thread
2. `start_thread` call from `clone` system call

While inconclusive, this does point us to messaging overhead being a contributor to memory usage.

**TODO**: Analyze the ZMQ message queues during the same test case.
Hypothesis 1: As the test case runs for a long duration, the ZMQ messaging queues build up, leading to high memory footprint.
Hypothesis 2: The impact is more pronounced with stateless since each task takes longer to process each ZMQ message, slowing down the rate at which messages are dequeued.

**Comment by ulaskozat** [comment]
@ssanadhya thanks for the detailed experimentation and analysis. It is worrisome that in steady state, the longer the run or more UEs are involved, it jumps to a higher level of memory consumption. @talkhasib do you think ZMQ can really be the culprit here?

**Comment by talkhasib** [comment]
From my previous experimentations with Valgrind, when the process is killed, any message still transiting through ZMQ will be declared as a leak as the deallocation happens at the receiving side.
Does Valgrind show any memory leaks that builds up with time?

**Comment by ssanadhya** [comment]
> From my previous experimentations with Valgrind, when the process is killed, any message still transiting through ZMQ will be declared as a leak as the deallocation happens at the receiving side. Does Valgrind show any memory leaks that builds up with time?

I did not run memcheck in Valgrind as ASAN is not reporting any leaks. Note that the steady state that @ulaskozat is referring to is when all the UEs and eNBs have disconnected from the network, so at that point there should not be any messages in ZMQ. I will re-run the above test case with memcheck to verify.

The report from Valgrind's Massif during the test run, i.e.  while the UEs are switching between active/idle, points to ZMQ in the backtrace. Could there be a queue build up happening there?

**Comment by electronjoe** [comment]
Would be nice to run the MME binary in these settings with Google's [gperftools](https://github.com/gperftools/gperftools). Specifically:
- linking with `-ltcmalloc`
- `$ HEAPPROFILE=/tmp/heapprof mme.binary` and run tests while profile collects to `/tmp/heapprof`
- Analyze heap data with [pprof](https://github.com/google/pprof) `pprof <path/to/mme.binary> /tmp/heapprof.0045.heap`

Unlike valgrind, pprof is not looking to trace EVERY allocation just a statistical sampling of them to give you an idea where large quantities of allocation are being stranded.  It therefore has ~minimal performance overhead.

Output looks like this for memory allocation analysis, with box size equal to the outstanding allocated bytes at each allocation point at that checkpoint in the test run (that is memory allocations not yet free'd by the program).

![image](https://user-images.githubusercontent.com/3752618/153044843-ea2b1750-0a74-44a2-8ae7-3b32b47927ff.png)

Edit: if allocations are made in libraries - they won't be traced here as this capability is link-time activated... So if the leak is truly in e.g. libczmq or its wrapping of libzmq then this won't help. But this will be rather authoritative of the issue being or not being an MME centric one.
