### ISSUE TITLE
[Regression]TC37 and TC38 are failing when executed in suit as PDU-Session retry is happening

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10455]
Your Environment

- Version: 1.7.0-1637262786-7c8beb72
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: Vagrant (AGW)

Describe the Issue

PDU session retry is happening while doing a long run in AGW.

To Reproduce
1. Make sure all the services in AGW are active.
2. Make sure NGAP and SCTP connections are UP .
3. Try to execute TC in TVM-setup as a batch.
4. After a long run TC37 and TC38 are failing as PDU-Session retry is happening.

Expected behavior
Proper session clean-up should happen and new request should get served even after a long run.

Screenshots
TC failure in batch run:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/8b34ee5e-17b8-43c0-bd01-a3a305430905)
TC passing when executed individually:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/3cedf034-4561-4d6e-ab2f-309e2ee5994f)

Please find the logs and pcaps from the attachment

[https://app.zenhub.com/files/170803235/4b214d5a-a530-480b-b3d3-5bd18ab50220/download](https://app.zenhub.com/files/170803235/4b214d5a-a530-480b-b3d3-5bd18ab50220/download)

Note: PCAPS for success case are also available.

**Comment by arun-magma** [comment]
Can add a test start delay for this in auto run if needed (Whats the preferred wait interval for session clearance ?), On current auto run 9 sec delay is not sufficient to cleaning up the session in AGW ? 
Please update the code merge status in Spread sheet as its now assigned to Wlabs to clarify the behavior, 
Fyi these TCs are planned based on DStest feasibility issues.

**Comment by NeelimaKalpana** [comment]
Hi Arun,
9 Sec should be sufficient. GaneshG is looking into this issue. from SMF session is not getting cleaned it seems.
Once developers give any inputs on this accordingly we can add delay between the TC execution. 

@Please update the code merge status in Spread sheet as its now assigned to Wlabs to clarify the behavior ==> I will get clarity and update the sheet.

**Comment by panyogesh** [comment]
@arun-magma : Can you please provide the test script expected behavior. For configuring the BW their is no code merge pending. But if there is any other expected behavior kindly let us know.

**Comment by arun-magma** [comment]
Hi @panyogesh : Expecting valid PDU response before the Retry Timer (15 sec) , We se no response either PDU accept or PDU Reject with valid cause should be reverted by AGW. here is the snap of one the test instance you can find 1 + 4 Retries (15 sec intervals) has no response.
This issue is often found in diff TCs.

In Syslog finding a Dup request for same PDU id = 5, as earlier session was not cleared on time this issue appears.
![Screen Shot 2021-11-30 at 11.42.19 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/99065258-d95a-40eb-b303-44f852c41ce4)

[Pcap]
![Screen Shot 2021-11-30 at 11.38.32 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/871619cf-738a-4fd9-aeb9-baafdb2c74e5)

**Comment by ganeshg87** [comment]
issue clarified https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/10532 ticket
