### ISSUE TITLE
[AMF] AMF is accepting the PDU-Session when a PDU-Request with DNN as empty string is been received from UE.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10477]
Your Environment

- Version: 1.7.0-1637360209-fcdd682f
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: Vagrant (AGW)

Describe the Issue

AMP is sending accept message for a PDU-Session request with empty DNN-Name is given.

**To Reproduce**
1. Configure subscriber without any DNN/APN name.
2. Send PDU session request from UE with DNN-Name as empty.
3. Check that PDU-Session is getting rejected are notified.
4.  PDU-Session is getting accepted and session is getting established.

Expected behavior

PDU-Session reject or notification should be sent and PDU-Session should not get established.

Screenshots
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/6f79eb14-fee2-40e6-a5f6-5d601575ddca)

Screenshot of PDU-Session Request with DNN-IE:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/31c1bdbf-f3a4-4a33-809a-58e4761fb52b)

PDU-Accept for Request:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/846db962-858c-440f-8035-74691b2c901f)

Syslogs where DNN string is taken as '0'

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/6ef38741-7e0d-45b1-9da4-65801552bb46)

[https://app.zenhub.com/files/170803235/a3927dc7-6fd2-4cd5-b589-77f243f79116/download](https://app.zenhub.com/files/170803235/a3927dc7-6fd2-4cd5-b589-77f243f79116/download)

**Comment by sreedharkumartn** [comment]
Fixed as part of PR #10500.

**Comment by rupa455wavelabs** [comment]
Issue resolved and tested in TVM setup.
Expected Behaviour: PDU-Session reject or notification should be sent and PDU-Session should not get established.
Actual Behaviour: PDU-Session is getting rejected due to cause 27(Missing or Unknown DNN)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/c7184219-d1d6-4e7d-8c5c-eb2a34d387c9)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/86ef9d8c-1ae4-4a4c-90b0-d81c72b1c5bc)

**Comment by rupa455wavelabs** [comment]
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/f90e5459-d675-47ff-890a-bffcf6089be6)
