### ISSUE TITLE
Make sure master always pass unit tests

### ISSUE THREAD

**Issue by quentinDERORY** [magma/magma#10648]
PR can be merged if all required unit tests are green but if the PR is not rebased, it can lead to failures in unit tests on master.
Solutions:
- Create a new required check that will block if the PR is not rebased.
- Track unit test in the new ci dashboard.

**Comment by quentinDERORY** [comment]
Just found out we can use Require branches to be up to date before merging check in branch protection of github to achieve that: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by sebathomas** [comment]
Maybe a merge queue would be a good solution from that page:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-merge-queue

Otherwise it might require a lot of manual rebasing if there are multiple PRs ready to be merged at the same time.

**Comment by quentinDERORY** [comment]
Thanks @sebathomas for bringing this up but per reading this https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/using-a-merge-queue,  this would use the push trigger and it would imply refactoring most of the workflows. In addition this introduces a new weird limbo states for PR where you don't know if they have been merged or not. Thus creating extra work on keeping an eye on your PR being merged... But I agree that enabling this check might be tricky as some ci tests would take longer than a new commit being landed on master.

**Comment by sebathomas** [comment]
Ah, I didn't realize it would have a large impact on the existing workflows, and that it was still in beta. I see how that might not be a good solution then.

I still worry that having to keep it up-to-date with master after setting the `ready2merge` tag would be hard to do, especially if the check is applied strictly, since the commit author is usually not the person that can trigger the merge.

**Comment by Neudrino** [comment]
For reference: https://github.blog/changelog/2021-10-27-pull-request-merge-queue-limited-beta/.
- https://github.com/github/roadmap/issues/272
- https://github.com/github/roadmap/issues/370
- https://github.com/github/roadmap/issues/455

Might be interesting once in production.
