### ISSUE TITLE
Paging with Multi PDU Session is failing

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#10739]
Your Environment
Version: magma/focal-ci, now 1.7.0-1638987121-f05b82db amd64
Affected Component : Access Gateway
Affected Subcomponent : AGW service

**Describe the Issue**

**Actual Behavior:**

UE should not able to transit from Idle Mode to Active state when we test with Multi PDU sessions (Only one PDU session is able to transition from IdleMode to Active Mode).

**Expected Behavior:**

UE should go to Idle Mode to Active Transition with Multi Pdu session

**Comment by moinuddin1980** [comment]
- Please attach the relevant  mme. syslogs and pcaps.
- As we see in the issue title the PDU session retry is happening, we need to check the sctp reset was done after - each TC execution and before the next TC execution.
- What is the TC status when it was run individually?

**Comment by rupa455wavelabs** [comment]
Hi @moinuddin1980 , Please find the below attached logs and pcap.
[https://app.zenhub.com/files/170803235/05f86cc9-a7e7-403c-b4fa-1bcac4200988/download](https://app.zenhub.com/files/170803235/05f86cc9-a7e7-403c-b4fa-1bcac4200988/download)

TC status when run it individually : 
PDU Session establishment request is retrying 
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/f9624e10-a1a0-40ae-a526-92b6e867169c)

**Comment by rupa455wavelabs** [comment]
Please find the attached pcap and logs

[https://app.zenhub.com/files/170803235/49fa0151-c606-4cdc-9abc-6e65bc10c03e/download](https://app.zenhub.com/files/170803235/49fa0151-c606-4cdc-9abc-6e65bc10c03e/download)

**Comment by rupa455wavelabs** [comment]
Duplicate issue, closing it

**Comment by Sathyaj27** [comment]
According to the pcap after paging only session id 5 is getting successful session  resource response from gnb.
![working_session_id_5.PNG](https://images.zenhubusercontent.com/6195e68b8c224223e2a51927/67624526-4bd2-4950-aae0-3806b18c73e8)
Session id 6, 7,8 is not getting successful response from gnb.
![session_id_6_not working.PNG](https://images.zenhubusercontent.com/6195e68b8c224223e2a51927/17ab668d-880a-4ec8-a54c-3d92e34784f2)
Looks like there seems to be an issue with the script.
I have attached the screen shot for  working and not working session id.

**Comment by moinuddin1980** [comment]
4 PDU sessions were created, but after paging procedure, only 1 PDU session came up(id 5), but rest got setup failure from gNB(id 6, 7, 8).  Below ZenHub task is created to pursue the reason for the 3 PDU session id setup failure from gNB or script. 
https://github.com/magma/magma/issues/10857

As part of Initial UE Message Service request AGW is sending all the allowed PDU sessions which can be re-established(5, 6, 7, 8). But, the gNB comes back with only PDU session id 5 in InitialContextSetupResponse
![image.png](https://images.zenhubusercontent.com/6184f6ae82047233ede1227b/3c433da0-8c96-488a-90bd-f30328a07083) 

![image.png](https://images.zenhubusercontent.com/6184f6ae82047233ede1227b/287abd00-2f32-4fe6-b69c-4da26f5f7b4f)

Later on when AGW tries to send PDUSessionResourceSetupReq for PDU session id 6, 7 and 8, it receives back PDUSessionResourceSetupResponse from gNB with PDUSessionResourceFailed(unknown PDU session id 6, 7, 8)
![image.png](https://images.zenhubusercontent.com/6184f6ae82047233ede1227b/52e3c181-b969-4b71-abe5-a9013691f7b9)

**Comment by GANESH-WAVELABS** [comment]
[15-December-2021 : Ganesh . I] : From the shared logs pipelined sending Paging request towards sessiond for 2 PDU sessions[PDUID 5 & 6],  In sessiond from session map does look up based on IMSI so it will receive all 4 sessions related  to that IMSI. so sessiond is triggering `service_handle_request_on_paging` for all 4 PDU sessions which changes the FSM session state from INACTIVE to CREATING, at this point sessiond received remaining 2 PDU sessions[PDUID 7 & 8] Paging request from pipelined. At this time as FSM state not in INACTIVE state for the later 2 PDU sessions[PDUID 7 & 8] sessiond is throwing below error and return from that function. 
`Can not Trigger Paging notification to AMF, as session is not an INACTIVE state`
So AMF doesn't forward this to UE, so for these 2 PDU sessions[PDUID 7 & 8] no PAGING service not completed.
after this for 1st PDU session[PDUID 5] AMF is sending 2nd request to sessiond, so sessiond moving the FSM state from CREATING --> CREATED --> ACTIVE for only the 1st PDU session[PDUID 5].

Action point: 
1) sessiond side lookup should happen with `IMSI+PDUID` to uniquely identify a paging request per session, instead of doing lookup based on just `IMSI`.
2) Also AMF has to check why 2nd request is not triggered for other PDU session[PDUID 6]..

**Comment by GANESH-WAVELABS** [comment]
[20-December-2021 : Ganesh . I] : From Sessiond side we have added code for do lookup based on `IMSI+PDUID` to uniquely identify a paging request per session. We have tested the code using sessiond stub CLI which was working fine, here stub was sending `imsi` with `IMSI + numeric value` .

After sharing the private binary to for testing on teravm setup I could see 4 PDU sessions [5,6,7,8] got established and moved to IDLE mode [INACTIVE state], then UPF sent Paging request towards sessiond for only 3 PDU sessions [5,6,7]. Then sessiond notified these paging notifications to AMF for 3 PDU sessions[5,6,7]. Then AMF sent back notification to only 1st PDU session[PDUID: 5], then sessiond handled first Paging request inside `service_handle_request_on_paging` method by  doing lookup based on `IMSI + numeric value` and `PDUID` but initially session was established with `numeric value` only as there was no `IMSI` prefix, so session store doesn't find this session and return nothing to session_map, so we could see below error and exit from there without moving this session to ACTIVE mode. Due to this paging was not success for PDU session ID : 5
![image.png](https://images.zenhubusercontent.com/608a39d761f99431f5047a77/7f0ebc07-6d93-4fa4-867b-4fa7a53b18c3)

Action Points:
----------------
1) why UPF did not send Paging request to sesssiond for PDU ID:8
2) why AMF did not send service request notification towards sessiond for PDU sessions[PDUID: 6, 7]
3) Need to check sessiond can proceed `IMSI+numeric value`  for lookup when paging request handling or need to check the possibility of Teravm to send `IMSI _ numeric value` during PDU session establishment and release request.

**Comment by NeelimaKalpana** [comment]
Closing this issue as Fix is working fine.
Please find the attached logs.[https://app.zenhub.com/files/170803235/b1ffdb8d-86f3-454c-a5a1-414bb1be0f73/download](https://app.zenhub.com/files/170803235/b1ffdb8d-86f3-454c-a5a1-414bb1be0f73/download)
