### ISSUE TITLE
[FEG] how to configure Magma to use Centralized Unit Determination (CUD).?

### ISSUE THREAD

**Issue by blueCARDSS** [magma/magma#10824]
# TITLE OF YOUR PROPOSAL

## Problem

how to configure Magma to use Centralised Unit Determination (CUD).?

What we see below is Decentralised Unit Determination (DUD) where Magma is making an explicit RSU unit request (164,012 octets). This value might be OK for an IoT use case but for a 4G smartphone it is way too low.  Given that it could download at 1Gb/s if it sends us a CCR for every 150KB that would be >800 transactions per second for just that one session!
```
#'3gpp_ro_CCR'{
      'Session-Id' = <<"magma.epc.mnc000.mcc460.3gppnetwork.org;94;552;IMSI460000000000707">>,
      'Origin-Host' = <<"magma.epc.mnc000.mcc460.3gppnetwork.org">>,
      'Origin-Realm' = <<"epc.mnc000.mcc460.3gppnetwork.org">>,
      'Destination-Realm' = <<"mnc000.mcc460.3gppnetwork.org">>,
      'Auth-Application-Id' = 4,
      'Service-Context-Id' = <<"32251@3gpp.org">>,
      'CC-Request-Type' = 2,'CC-Request-Number' = 24,
      'Destination-Host' = [<<"ocs3">>],
      'Origin-State-Id' = [1639370093],
      'Event-Timestamp' = [{{2021,12,13},{5,25,37}}],
      'Subscription-Id' =
          [#'3gpp_ro_Subscription-Id'{
               'Subscription-Id-Type' = 1,
               'Subscription-Id-Data' = <<"460000000000707">>}],
      'Multiple-Services-Indicator' = [1],
      'Multiple-Services-Credit-Control' =
          [#'3gpp_ro_Multiple-Services-Credit-Control'{
               'Granted-Service-Unit' = [],
               'Requested-Service-Unit' =
                   [#'3gpp_ro_Requested-Service-Unit'{
                        'CC-Total-Octets' = [164012]}],
               'Used-Service-Unit' =
                   [#'3gpp_ro_Used-Service-Unit'{
                        'Reporting-Reason' = [3],
                        'CC-Total-Octets' = [164095],
                        'CC-Input-Octets' = [81069],
                        'CC-Output-Octets' = [83026]}],
               'Rating-Group' = [1]}],
      'User-Equipment-Info' =
          [#'3gpp_ro_User-Equipment-Info'{
               'User-Equipment-Info-Type' = 0,
               'User-Equipment-Info-Value' = <<4,0,5,1,7,5,6,8,1,3,2,6,1,7,0,0>>}],
      'Service-Information' =
          [#'3gpp_ro_Service-Information'{
               'PS-Information' =
                   [#'3gpp_ro_PS-Information'{
                        '3GPP-PDP-Type' = [0],
                        'PDP-Address' = [{192,168,128,229}],
                        'SGSN-Address' = [{10,0,2,1}],
                        'GGSN-Address' = [{10,0,2,1}],
                        'CG-Address' = [{134,209,191,215}],
                        '3GPP-GGSN-MCC-MNC' = [<<"46000">>],
                        '3GPP-NSAPI' = [<<"5">>],
                        'Called-Station-Id' = [<<"cmnet">>],
                        '3GPP-Selection-Mode' = [<<"0">>],
                        '3GPP-SGSN-MCC-MNC' = [<<"46000">>],
                        '3GPP-User-Location-Info' = [<<130,100,240,0,0,11,100,240,0,3,14,45,45>>],
                        '3GPP-RAT-Type' = [<<6>>]}]}]},
```

## Solution

In CUD mode the OCS determines the unit type (i.e. octets or time) and unit size for a reservation (RSU). The way it does this is by including an empty Requested-Service-Unit (RSU) AVP in the Multiple-Services-Credit-Control (MSU) AVP.

**Comment by blueCARDSS** [comment]
@parthiban337 @uri200

**Comment by uri200** [comment]
Hey @blueCARDSS I am not sure if I fully understand the request, so let's see if this helps: sessiond uses the first RSU value received on following requests. So if in your first grant you received 1M octets, when s session gets 80% of that, sessiond will request 1M again  (a little bit less because it will take into consideration what it is still left).

Note that before 1.5, I think that value was set to 200k so that may explain why you see such low value. After 1.5 that value was defaulted to 10M

Note RSU initial default amount can be changed manually on sessiond.yml [here](http://github.com/magma/magma/blob/b206a41117a07e2f63ba95cb5a76b4ac45632da7/lte/gateway/configs/sessiond.yml#L59-L59). If you set that value to a big amount you may force OCS to provide bigger grants. You can also try to set it to 0 as you requested, but not sure if this is going to work for you.

But in case you want that avp not to be sent completely. session_proxy can disable that RSU setting this env var on session_proxy `DISABLE_REQUESTED_SERVICE_UNIT_AVP=1` at your feg (from [here](http://github.com/magma/magma/blob/b206a41117a07e2f63ba95cb5a76b4ac45632da7/feg/gateway/docker/docker-compose.yml#L105-L105)). Note you can do the same editing the  `.env` [file](http://github.com/magma/magma/blob/b206a41117a07e2f63ba95cb5a76b4ac45632da7/feg/gateway/docker/.env#L1-L1). You don't need to modify docker-compose.yml

**Comment by blueCARDSS** [comment]
After changing the value . OCs is happy . Thank you I am closing this issue .

**Comment by blueCARDSS** [comment]
After changing value as suggested . OCs happy now
