### ISSUE TITLE
[Regression-Failure] TC14b failing as AMF is not receiving response from Subscriber-db .

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10925]
Your Environment

- Version:  1.7.0-1639678730-75fa541b  
- Affected Component: Access Gateway 
- Affected Subcomponent : AGW service
- Deployment Environment: Vagrant (AGW)

### Describe the Issue
TC14b failing as AMF is not receiving response from Subscriber-db , for the auth-info request for the UE from subscriber-db.

To Reproduce
1. AGW should be UP, and all services should be active and running.
2. All connection Procedures should be successfull.
3. Trigger the Regression SUIT and see the output of below TC.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/c78fed96-82ba-40e8-8ef5-f04f2c2197d8)
4. TC failing as there is no Auth-Request sent to UE as AMF is not getting response from subscriber-db for the auth-info request sent.

**Expected behavior**
Registration procedure should get triggered as per testcase expectation.

**Screenshots**
MME_Logs_Failure:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/310451ce-6605-4b7d-a501-8cafcbfbf095)

MME_Logs_SUccess Flow:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/b320d8c1-ed84-4ac2-a74c-4cb41a2ffb5a)

Syslogs_Failure_Logs:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/1c2e1144-577a-47e3-be88-113185dcdf93)

[https://app.zenhub.com/files/170803235/9e64d055-2a75-4bad-9a9f-d0d7014ac6d8/download](https://app.zenhub.com/files/170803235/9e64d055-2a75-4bad-9a9f-d0d7014ac6d8/download)

**Comment by NeelimaKalpana** [comment]
TC 43c is also failing withe same subscriberdb lock issue.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/7a196f93-91cd-45df-a50b-8f4687bf82c1)

**Comment by moinuddin1980** [comment]
The subscriberDB lock issue got reported in the past as well.
- https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/9809
- https://github.com/magma/magma/issues/6937
 As there are multiple writer/reader for database in subscriberDB, the locking mechanism cannot be avoided. 
But, at the same time the GRPC failure must be reported back to AMF, so that AMF can take appropriate action.
e.g. 
- Based on the GRPC failure response, the AMF can retry to sending GRPC to subscriberDB for the UE after 1 sec(can be refined).
- If the response for the GRPC retry also is a failure, then the UE registration can be rejected.
But, the above approach need bit more analysis and cannot be handled in a ticket.

Hence, let's observe this issue for a while and if it re-occurs every time, we can crate a separate task to work on this.

**Comment by NeelimaKalpana** [comment]
Todays Regression : TC1a hyper_SUCI_No_PDU TC is failing because of subscriber-db locked issue.

From TC is intended to trigger 50 loops for same UE for registration and de-registration , But due to subscribed-db locking issue , 52 request are getting triggered .

**Comment by VinayKumar1591** [comment]
@NeelimaKalpana can you please attach logs

**Comment by NeelimaKalpana** [comment]
Hi Vinaya,

Logs are already attached ,please check it once.

**Comment by VinayKumar1591** [comment]
@NeelimaKalpana shared binary personally as unable to upload here. please test with binary share details here

**Comment by NeelimaKalpana** [comment]
Reopening the ticket as PR is not merged into the master . 
Test team need to validate this from master code after PR-Merged .

Please not that Test team is responsible for closing the bugs/tickets after testing from master branch.

**Comment by panyogesh** [comment]
Subscriber-db lock issue seems to be related to #11088.

**Comment by NeelimaKalpana** [comment]
Tracking this issue in below Ticket .
https://github.com/magma/magma/issues/11088
Closing this Ticket.
