### ISSUE TITLE
Requesting to add De-Registration in TC7d after service request failure and context release is happening.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10930]
Hi Arun,

In TC7d please add de-registration procedure for cleaning-up the PDU-Session, as this is impacting the consecutive TC.

Please refer below ticket for your perusal.

[Regression]TC7d failing because of PDU-Retry .#10662

**Comment by arun-magma** [comment]
[AGW Side]
Expect Service Reject Implicitly De register the Subscriber Context & Session in AGW and expect UE to send New Fresh Registration.
It makes sense as already UE got permanently populated with bad TMSI expect UE sending DeReg with bad TMSI is not appropriate. means the Original TMSI never recoverable in UE to send proper De-Reg to clear the active context.
[UE Side]
As per our understanding on Service Reject UE likely De Register context/session implicitly and It cannot send any further De Reg Request.

[Suggestion]
Once the AGW side implicit DeReg flow is agreed we add in this TC7d script a fresh SUCI based registration to verify a successful earlier context/session clearance and UE could Re-Reg successfully.

**Comment by moinuddin1980** [comment]
As far as the TC7d execution is concerned, it is passing as the expectation of getting a service reject for a corrupted TMSI service request message.
But, for the UE PDU session which got created earlier, the AGW has no clue how to clear it as there is no mapping w.r.t TMSI received in the service request.
Also, the implicit De-Registration flow functionality for the subscriber in AGW is not available(under progress) yet.
Hence, there will be stale UE PDU session/s which will be impacting the next TC execution.
Thus, in order to overcome this situation we have two suggestions:

1. Add UE de-registration at the end as part of TC7d script.
OR
2. Test the TC7d when implicit de-registration feature is ready in AGW.

**Comment by arun-magma** [comment]
De flow addition not possible as original TMSI lost by Teravm State machine, need to implement Implicit Dereg to avoid stale session, in Scripts we added Fresh Registration trigger to validate new session for same SUCI is supported, TC passing and probably earlier TMSI based session remains as stale. Marked this TC7d as Code Merge Pending until Imp Dereg gets Implemented, Share the PR in this ZH task once Code is ready.

if this adds trouble in regression run for Subsequent TCs then we would remove this TC, if not we will track it as Code Merge pending so that it won't affect pass %.

**Comment by NeelimaKalpana** [comment]
Hi Arun,
Please remove it from the regression suit as it is impacting the consecutive TC with pdu-session.

**Comment by NeelimaKalpana** [comment]
TC59 and TC60 are the PDU related TC's getting executed after TC7d , So once TC7d TC is Removed or Implicit deregistration feature is supported these cases will pass.

**Comment by rupa455wavelabs** [comment]
Requirement satisfied, Closing the issue.
