### ISSUE TITLE
GUTI Registration(200UE, 12Gnb, 5UE/s) with 30 loops Execution is not working properly 

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11000]
AGW magma : 1.7.0-1640288244-cfbb816f

Expected Behavior: GUTI Registration(200 ue, 12gnb, 5ue/s,30loops) call flow should be successful without any issues

Actual Behavior:
GUTI Registration(200UE, 12Gnb, 5UE/s, 30 loops) should not able to receive the exact number of Registration Accept, Registration Complete, Identity Response, Auth Response, Security mode complete, PDU session Establishment Accept, PDU session Release accept, PDU session Release complete, DeRegistration Accept.

Please check the below screenshots for reference
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/5e878c03-95f0-45c9-9b95-bed2628b6c39)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/a8a35c76-adff-4690-be7b-f2e3917ece18) 
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/0391af82-374d-4f36-9d1d-47cb626f4b7b)

**Comment by rupa455wavelabs** [comment]
**Test Case Verdict**
verification fail:  ((nas5g_sent_Registration_Req_=4366)     	>= 200*30)  => False
verification fail:  ((nas5g_received_Registration_Acc_=4600)		== (nas5g_sent_Registration_Req_=4366))  => False
verification fail:  ((nas5g_sent_Sess__Establ__Req_=4088)    	>= 200*30*1)  => False
verification fail:  ((nas5g_received_Sess__Establ__Acc_=4088)	>= 200*30*1)  => False
verification fail:  ((as_received_raw_bytes=212560000) 			>= (ue_sent_total_bytes=408829000)-((ue_sent_total_bytes=408829000)*0.01))  => False
verification fail:  ((ue_received_total_bytes=2568000)			>= (as_sent_total_bytes=203650524)-((as_sent_total_bytes=203650524)*0.01))  => False
verification fail:  ((nas5g_sent_Sess__Rel__Req_=4237)       	>= 200*30*1)  => False
verification fail:  ((nas5g_received_Sess__Rel__Cmd_=4010)   	>= 200*30*1)  => False
verification fail:  ((nas5g_sent_Sess__Rel__Req_=4237)       	== (nas5g_received_Sess__Rel__Cmd_=4010))  => False
verification fail:  ((nas5g_sent_Dereg__Req_=4210)           	>= 200*30)  => False
verification fail:  ((nas5g_received_Dereg__Acc_=4210)       	>= 200*30)  => False

**Comment by rupa455wavelabs** [comment]
Please find the required logs and pcaps from this link: https://drive.google.com/drive/folders/1B9zcK-12LOAjaVeAJ-b0qNwyFe1feMGO

**Comment by Kaleem-Wavelabs** [comment]
@Chandhu-Wavelabs Can you update first level of your analysis. Thanks.

**Comment by rupa455wavelabs** [comment]
We tried to reproduce the same issue with different scenario's and observed the below actions:

Hyper GUTI - 100 UE, 12 GNB, GUTI Registration, PDU_Session_Establishment/Release, Traffic UL DL - Test case is failing due to UL/DL issue, call flow was successful as expected.
 
Hyper GUTI - 200 UE, 12 GNB, GUTI Registration,1 loop, PDU_Session_Establishment/Release, Traffic UL DL - Test case is failing due to UL/DL issue, call flow was successful as expected.

Hyper GUTI - 200 UE, 12 GNB, GUTI Registration,5 loop, PDU_Session_Establishment/Release, Traffic UL DL - Test case is failing due to UL/DL issue and we observed the less count than expected. 

Hyper GUTI - 200 UE, 12 GNB,10 Loops, GUTI Registration, PDU_Session_Establishment/Release, Traffic UL DL - Test case is failing due to UL/DL issue and we observed the less count than expected. 

Hyper GUTI - 200 UE, 12 GNB,30 loops, GUTI Registration, PDU_Session_Establishment/Release, Traffic UL DL - Test case is failing due to UL/DL issue and we observed an issue with Registration Accept Timer due to no response from Gnodeb after 6000 sessions.

**Comment by rupa455wavelabs** [comment]
mme logs: 
3664976:3279585 Wed Jan 05 02:25:11 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48040 expired forue_id=9865
3665078:3279682 Wed Jan 05 02:25:12 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48044 expired forue_id=9867
3665620:3280194 Wed Jan 05 02:25:13 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48056 expired forue_id=9879
3665810:3280374 Wed Jan 05 02:25:13 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48057 expired forue_id=9883
3665912:3280471 Wed Jan 05 02:25:13 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48058 expired forue_id=9885
3666014:3280568 Wed Jan 05 02:25:14 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48059 expired forue_id=9888
3666116:3280665 Wed Jan 05 02:25:14 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48060 expired forue_id=9890
3666130:3280679 Wed Jan 05 02:25:14 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48061 expired forue_id=9892
3666144:3280693 Wed Jan 05 02:25:14 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48062 expired forue_id=9894
3666429:3280960 Wed Jan 05 02:25:16 2022 7FC4463EF700 WARNI AMF-AP tasks/amf/Registration.cpp      :0706    T3550: timer id: 48063 expired forue_id=9902


TEST VERDICT  LOGS:

 verification fail:  ((nas5g_received_Registration_Acc_=6389)		== (nas5g_sent_Registration_Req_=6092))  => False
verification fail:  ((nas5g_sent_Sess__Establ__Req_=5792)    	>= 200*30*1)  => False
verification fail:  ((nas5g_received_Sess__Establ__Acc_=5792)	>= 200*30*1)  => False
verification fail:  ((as_received_raw_bytes=341710000) 			>= (ue_sent_total_bytes=579165000)-((ue_sent_total_bytes=579165000)*0.01))  => False
verification fail:  ((ue_received_total_bytes=130222000)			>= (as_sent_total_bytes=327741876)-((as_sent_total_bytes=327741876)*0.01))  => False
verification fail:  ((nas5g_sent_Sess__Rel__Req_=5907)       	>= 200*30*1)  => False
verification fail:  ((nas5g_received_Sess__Rel__Cmd_=5693)   	>= 200*30*1)  => False
verification fail:  ((nas5g_sent_Sess__Rel__Req_=5907)       	== (nas5g_received_Sess__Rel__Cmd_=5693))  => False
verification fail:  ((nas5g_sent_Dereg__Req_=5893)           	>= 200*30)  => False
verification fail:  ((nas5g_received_Dereg__Acc_=5893)       	>= 200*30)  => False

**Comment by Kaleem-Wavelabs** [comment]
@Chandhu-Wavelabs 

Please check the below errors in mme thread which triggered mme abort. This is mainly caused when there were bulk of registration accept failures(retransmissions).

_Jan  6 04:27:57 TVM3-SA sessiond[2834087]: I0106 04:27:57.920105 2834087 SetMessageManagerHandler.cpp:387] Successfully released and updated SessionStore of subscriber222456000000102
Jan  6 04:27:57 TVM3-SA mobilityd[2834079]: WARNING:root:Releasing unknown <SID, IP> pair: <IMSI222456000000102.internet,ipv4, 0.6.140.202> sid_ips_map[IMSI222456000000102.internet,ipv4]: None
..._

_Jan  6 04:27:57 TVM3-SA mme[2834761]: ReleaseIPv4Address fails with code 5, msg: (SID, IP) map not found: (IMSI222456000000102, 0.6.140.202)
Jan  6 04:27:57 TVM3-SA mme[2834761]: LeakSanitizer:DEADLYSIGNAL
Jan  6 04:27:57 TVM3-SA mme[2834761]: ==2834761==ERROR: LeakSanitizer: SEGV on unknown address 0x000000000000 (pc 0x5615ca292038 bp 0x7f737fae29e0 sp 0x7f737fae2990 T15)
Jan  6 04:27:57 TVM3-SA mme[2834761]: ==2834761==The signal is caused by a READ memory access.
Jan  6 04:27:57 TVM3-SA mme[2834761]: ==2834761==Hint: address points to the zero page.
...
Jan  6 04:27:58 TVM3-SA mme[2834761]:     #0 0x5615ca292038 in registration_accept_t3550_handler /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/Registration.cpp:701
Jan  6 04:27:58 TVM3-SA mme[2834761]:     #1 0x7f738c0f1449 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x29449)
Jan  6 04:27:58 TVM3-SA mme[2834761]:     #2 0x5615ca275eb5 in magma5g::amf_app_thread(void*) /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp:176
Jan  6 04:27:58 TVM3-SA mme[2834761]:     #3 0x7f738cc88608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
Jan  6 04:27:58 TVM3-SA mme[2834761]:     #4 0x7f738ba73292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
Jan  6 04:27:58 TVM3-SA mme[2834761]: LeakSanitizer can not provide additional info.
Jan  6 04:27:58 TVM3-SA mme[2834761]: SUMMARY: LeakSanitizer: SEGV /home/vagrant/magma/lte/gateway/c/core/oai/tasks/amf/Registration.cpp:701 in registration_accept_t3550_handler
Jan  6 04:27:58 TVM3-SA mme[2834761]: ==2834761==ABORTING
..._

@rupa455wavelabs 

When we checked the issue in teraVM, we have observed that after 30 loops of iteration we started seeing bulk of registration accept retransmissions from teraVM script, need to check from script perspective why there were multiple retransmissions though there were complete failures from AGW.

**Comment by rupa455wavelabs** [comment]
Hi @Kaleem-Wavelabs,
I asked Arun about the same, I will update here once he replies back.

**Comment by Kaleem-Wavelabs** [comment]
@Chandhu-Wavelabs @rupa455wavelabs Please verify this with the latest build and conclude on this
