### ISSUE TITLE
bug[MME] unknown-mme-ue-s1ap-id In a specific multi-sim UE scenario

### ISSUE THREAD

**Issue by edaspb** [magma/magma#11050]
Your Environment:

- Version: 1.7.0-1640913705-e6e795fd (master)
- Affected Component: AGW MME
- Deployment Environment: bare-metal (AGW)

Hi, I'm testing a scenario when Magma acts as a core for data only mobile LTE network.

Environment: **Dual Sim UE**.
One sim slot is for data only services (our LTE network with Magma in a center).
Second sim slot is for voice and sms service from regular mobile operator.

I found inconvenience with some dual sim dual standby UE like Samsung A01s, Redmi Note 9 and other:
When multiple sms come to mobile operator sim, our sim card inserted to first slot lost connection for few minutes.
Many different combination of Android configuration has been tested, like sim card priority, network type restrictions, etc.
No luck.

To Reproduce:
1. Some UE like Samsung A01s, Redmi Note 9 with two sim card activated. One sim with data services, another one with voice and sms.
2. Send multiple sms in a short period of time to sim with voice and sms services. This behaivior is common for many  sms chat application.

Here is log and capture:
[magmaDoubleSimTest.zip](https://github.com/magma/magma/files/7809271/magmaDoubleSimTest.zip)

**Comment by ulaskozat** [comment]
@edaspb, @rsarwad has done an initial analysis and she will be posting her analysis as well as the approach to go around the problem (i.e., proposed code changes on Magma side).

**Comment by rsarwad** [comment]
From  the attached logs, below are my observations
1. UE attaches to network.
2. Then UE sends Tracking are update request in initial ue message. Not sure about the reason why eNB has sent TAU request in initial UE message. because UE has active s1 signaling connection.
3. Since mme has received TAU request in initial ue message, at s1ap task, new ue contexts are created and old contexts are released locally. But ecm_state of UE context at mme_app task would remain as "ECM_CONNECTED". So TAU accept is sent in Downlink nas transport message, even though active flag is set to true. Later eNB is sending error indication with cause "unknown_mme_ue_s1ap_id". In response to error indication, mme is releasing the s1ap signaling connection and moving the ecm state to "ECM_IDLE"
eNB might be sending "error indication" because even though active flag is set, TAU accept is sent in DL nas message but eNB might be expecting in Initial context setup request message to establish the bearers. 

To address the issue, on reception of TAU req or Service Req in initial ue message for UE in connected state;  Along with releasing s1 signal connection locally and let mme_app move the UE to idle state and intimate to SPGW as well and then handle the received message, which would eventually send the response messages in "Initial Context setup response" message.

**Comment by edaspb** [comment]
My comments, maybe it helps to understand better the situation:

In point number two  UE receives sms which cause disconnection from LTE network due to UE is dual standby. The disconnection happens for very short period of time. My  guess is:
1. UE attaches to network.
2.1 UE receives sms from voice service sim, service from data sim is cut off.
Here would be great to check signaling and session part on enb but unfortunately there is no way to do it.
2.2 UE has finished receiving sms and returning back LTE service. Sends TAU.

We've checked Baicells and Huawei enb and behavior is absolutely similar.

**Comment by rsarwad** [comment]
> My comments, maybe it helps to understand better the situation:
> 
> In point number two UE receives sms which cause disconnection from LTE network due to UE is dual standby. The disconnection happens for very short period of time. My guess is:
> 
> 1. UE attaches to network.
>    2.1 UE receives sms from voice service sim, service from data sim is cut off.
>    Here would be great to check signaling and session part on enb but unfortunately there is no way to do it.
>    2.2 UE has finished receiving sms and returning back LTE service. Sends TAU.
> 
> We've checked Baicells and Huawei enb and behavior is absolutely similar.

Thanks @edaspb for providing details and below are few queries:
UE has dual sim, the sim that supports PS service is connected Magma EPC solution and the sim that supports voice and sms is connected to mobile operator's network. Is eNB is same or different for both sims? 
I think both sims needs operate independently, right? then how will the reception of sms on sms sim would cause connection loss on other sim?
Anyway, wrt point 2.2, once UE has finished receiving sms and returning back LTE service, UE sends TAU. I shall follow the above approach, so that eNB can re-establish the bearers for TAU procedure.

**Comment by edaspb** [comment]
Hi @rsarwad! You are right, both sims work absolutely independent, have different plmn and connect to two distinct networks. In a few words, one sim connects to our lab environment, another one (voice and sms) is from one of the commercial mobile operator. BTW we checked sim cards from all available operators and the behavior didn't change, the issue with disconnection from LTE network did persist.
The reception of sms cause dropping lte connection from other sim, in my understanding, because of UE is dual standby. It means it is not able to maintain two active connection on both sim on the same time. And somehow voice and sms have a priority over data.
PS I've receive an access to logs from enb side. Here is s1 and UU messages, maybe it helps.
[doubleModemTest.csv](https://github.com/magma/magma/files/7823247/doubleModemTest.csv)

And I've noticed that from user perspective the lte session drops after third sms. First two ones only cause few packets drops on a moment of reception.

**Comment by rsarwad** [comment]
Hi @edaspb Thanks for sharing the logs at eNB. 
From logs I could interpret is, 
1. After UE has attached network, eNB is sending RRC Connection release and is neither from MME nor release indication is not sent to mme. So UU interface, contexts are released and but not on s1 interface.
2. When UE switches from sms support to PS service, TAU is sent in new RRC connection request. Since it's new RRC connection request, eNB is sending TAU Request in Initial UE message. So at this movement of time. there are 2 s1-signaling connection exists at eNB. 
When TAU Accept is sent in DL nas message, eNB fails to match mme_ue_s1ap_id for later s1-signaling connection, due to which eNB sends error indication.
To resolve this issue need to do 2 things:
1. Clear previous s1-signaling connection at eNB by sending UE Context Release Request
2. Then handle TAU request

I have done the changes at MME. Want to validate the changes using s1ap tester. The issue with s1ap tester is, after the UE has attached to network, UE will be  in connected state. Unable to send TAU Request in "Initial UE message", trying to add hack

**Comment by rsarwad** [comment]
Hi @edaspb, Can I share the binary with fixes? If so let me know how can I share?

**Comment by rsarwad** [comment]
Hi @edaspb, I modified code to send TAU Accept in  s1ap-Initial context setup req message. Can I share the binary? If so let me know, how to share it?

**Comment by edaspb** [comment]
Hi @rsarwad, thanks a lot, we will immediately test it! Could you please try to upload here https://drive.google.com/drive/folders/1Qj_AmuO3oNeLjZ_2rLc16XqHXMgol2Zv?usp=sharing

**Comment by rsarwad** [comment]
Hi @edaspb, uploaded the mme binary in above link with name, mme_11050.gz

**Comment by edaspb** [comment]
Hi @rsarwad, I've made a tests, unfortunately unknown-mme-ue-s1ap-id issue still persists and UE behavior hasn't changed...

`root@gw2-3:/home/eda# md5sum /usr/local/bin/mme
308820e37513470aa80f19f14445ea79  /usr/local/bin/mme`

Please let me know if any other type of logs can help, I'm ready to make all possible tests.
Thank you!

[mme_11050.log](https://github.com/magma/magma/files/7855793/mme_11050.log)
[mme_11050_s1ap.pcap.zip](https://github.com/magma/magma/files/7855795/mme_11050_s1ap.pcap.zip)

**Comment by rsarwad** [comment]
@edaspb Let me analyze the logs and let you know

**Comment by ssanadhya** [comment]
#11245 is reverted in #11771, re-opening the issue
