### ISSUE TITLE
PDU Session Establishment is Retrying due to PDU Session Resource Request IE encode error

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11067]
Magma Build Version
1.7.0-1641423148-a22acdb3
1.7.0-1641418334-fa760796
1.7.0-1641414680-d77cb8c3

Expected Behavior:  PDU Session Establishment should be Accepted and QOS parameters should be updated in PDUSessionResourceSetupRequest and PDU session establishment accept messages.

Actual Behavior:  PDU Session is Retrying due to PDU Session Resource Request IE encode Error.

Please check the attached logs and pcap for more information:
[https://app.zenhub.com/files/170803235/f3e86b7a-eba6-4cc0-b46c-42bb2a295867/download](https://app.zenhub.com/files/170803235/f3e86b7a-eba6-4cc0-b46c-42bb2a295867/download)

**Comment by Sathyaj27** [comment]
Have observed that the static rules coming are in the form of policy name and not the rule parameters.
It is expected in the form of policy rule ie id, priority etc. 

![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/6195e68b8c224223e2a51927/d739cf26-cd1f-4d01-8266-2368d9bae0f6)

**Comment by GANESH-WAVELABS** [comment]
Can we get syslogs with DEBUG logs and GRPC logs enabled for both sessiond and pipelined to debug from sessiond and pipeliend perspective?

**Comment by moinuddin1980** [comment]
Following are the input w.r.t today's analysis:
1. There is no facility to configure qos flow parameters like ARP priority level, pre-emption capability, pre-emption vulnerability etc from NMS tool. 
When policy is associated with APN at NMS, the qos parameters will be set to nil in policyDB. Hence, these values will be nil while sending the PDU session creation response from SMF to AMF.
2. At AMF while sending the PDU Session Resource Setup Request towards gNB, the AMF forces to include the Qos parameters whether they are present or not.
Because of the above reason the PDU Session Resource Setup Request encoding fails at AMF.

Approach to be followed to unblock testing:
- Continue testing without association of APN with policy at NMS, so that testing can continue.
- Deal with Qos flow parameters configuration both at AMF and SMF as part of Session modification changes.

**Comment by apekshapk** [comment]
In spirent setup we are observing same issue.

**Comment by rupa455wavelabs** [comment]
Verified with latest master code and observed that PDU Session Resource Request IE encode error is not triggering when we attach the policy to IMSI.

Please find the required logs and pcaps from the below.
[https://app.zenhub.com/files/170803235/2792c047-7499-4b0c-b7ff-6e358aef6326/download](https://app.zenhub.com/files/170803235/2792c047-7499-4b0c-b7ff-6e358aef6326/download)
