### ISSUE TITLE
[Magma] [Bug] AGW 1.6.1 Disk space fills up and crashes AGW once external network is down

### ISSUE THREAD

**Issue by fb-mose** [magma/magma#11240]
### Environment
**Version:** 1.6.1-1636170378-596f8702
**Affected Component(s):** AGW
**Affected Sub-Component(s):** AGW Memory issue
**Deployment Environment:** Bare-metal AGW
### Problem Description
**Description**
Issue:

External network went down due to an issue with the router but the internal network was working fine. AGW was trying to connect to Orc8r but was failing, gradually syslog looks to have filled up the disk, available memory dropped and AGW crashed.
**Workaround**
Removed log files and cleaned up disk space up. Issue didn't appear afterwards.
**Impact**
AGW was crashed
**Triaging Steps**
Removed log files and cleaned up disk space up.
**Reproduction Steps**
Not able to reproduce.
**Expected Behavior**
If external network is down AGW shouldn't have crashed without having memory and disk space issues

**Internal Task:** T110366050

**Comment by uri200** [comment]
Syslog rotation and size is controlled by settings in 
```
/etc/logrotate.d/rsyslog
```

Maybe you can reduce the values so the logs rotate earler

**Comment by Radula76** [comment]
Hi,  Can we use this issue for our similar fault?
https://partners.facebook.com/fbc/support/question/321193863341409/

Sujay from our team has this analysis: When the orc8 connectivity is broken with AGW, all services continuously try to connect to Or8r and fails. Most of the messages are from magma and td-agent-bit. When the network down is for more than ~1 hour, td-agent-bit process continuously starts dumping the below message in large quantity thereby filling up the disk.

Mar 16 18:58:13 agw-r200 td-agent-bit[738989]: accept4: Too many open files Mar 16 18:58:13 agw-r200 td-agent-bit[738989]: accept4: Too many open files Mar 16 18:58:13 agw-r200 td-agent-bit[738989]: [2022/03/16 18:58:13] [error] [input:tcp:eventlogs] could not accept new connection

The reason for this is because td-agent-bit process has opened over 1024 file descriptor (max limit set). In stable case the number of fds used by this process is around 60-70.

The increase in number of fds is due to continuously opening of UDP sockets by td-agent-bit process.

sudo ls -l /proc/1850956/fd shows lot of following type of entries.

lrwx------ 1 root root 64 Mar 23 06:14 90 -> 'socket:[2220713682]' lrwx------ 1 root root 64 Mar 23 06:14 91 -> 'socket:[2220713839]' lrwx------ 1 root root 64 Mar 23 06:14 92 -> 'socket:[2220715083]'

These sockets seem to be opened towards dns.google.

agw11@agw-r200:/var/log$ sudo lsof -i -a -p 1850956 td-agent- 1850956 root 57u IPv4 2209535685 0t0 UDP 172.30.224.60:45180->dns.google:domain td-agent- 1850956 root 58u IPv4 2210060485 0t0 UDP 172.30.224.60:60018->dns.google:domain td-agent- 1850956 root 59u IPv4 2220702193 0t0 UDP 172.30.224.60:35663->dns.google:domain

**Comment by Radula76** [comment]
Our Customer Comsol has lost access to its remote site Durban due to flooding breaking the fibre links.  we now suspect that this AGW will fill its disk and crash.  we need to find a way of stopping the AGW from filling its disk when the connection to the Orc8r goes down.

**Comment by uri200** [comment]
This may be an issue with [td agent bit](https://docs.fluentbit.io/manual/v/1.0/installation/td-agent-bit) itself. 

You can see the config and enable debuting  logs at 
```
/var/opt/magma/tmp/td-agent-bit.conf
```

Note that config file is generated using this template
```
vim /etc/magma/templates/td-agent-bit.conf.template
```

**Comment by Radula76** [comment]
Hi @uri200,
  We can see the throttle configuration which looks ok, set to 1m which is quick but would resolve a small outage.  
maybe its the retry-on-failure config? should we try setting 'Retry_Limit' to true or set it to 512 or something? this should stop it trying 1024 times and running out of ports?
how do we know what is and what isn't being sent without retry?
thanks,  Mark.

**Comment by uri200** [comment]
Hey @Radula76  this seems to be a known issue for fluentid

https://github.com/fluent/fluent-bit/issues/2950
https://groups.google.com/g/fluentd/c/h-xK5OZ8ytM

You can try caping to 512. You may lose some metrics, but your AGW will work. 


Maybe it would be good to add some logs in this line and play with the try and with clausle to see if the sockets are closed properly
http://github.com/magma/magma/blob/master/orc8r/gateway/python/magma/eventd/rpc_servicer.py#L71-L71

Maybe @andreilee  can also add some insight on fluentbit

**Comment by andreilee** [comment]
@themarwhal iirc you might have some relevant knowledge here, but otherwise I'll take a look at this

**Comment by Radula76** [comment]
From Sujay 
The issue is the connection to DNS server. If I add an entry to fluentd server in /etc/hosts, then I do not see UDP sockets getting created.  Need to explore on how this code is handled.  The reason we are not seeing issue in Dev orc8r is the presence of entry of server in /etc/hosts files.

**Comment by qoderwork** [comment]
i have the same problem

**Comment by alledpaiva** [comment]
I also have this same issue.

**Environment**

**Version:** 1.6.340-1649331350-ba62f81c9 amd64
**Affected Component(s):** AGW
**Affected Sub-Component(s):** AGW Disk Memory issue
**Deployment Environment:** Bare-metal AGW

**Issue:**

Wrong fluentd configuration at "var/opt/magma/configs/control_proxy.yml" (to simulate that it have some internet connection problem); After this is was running normal.


May 25 15:51:25 4G-cluster-node-3 td-agent-bit[393331]: [2022/05/25 15:51:25] [ warn] [net] getaddrinfo(host='fluentd-wrong.core.xxxx.gm'): Unknown error
May 25 15:51:25 4G-cluster-node-3 td-agent-bit[393331]: [2022/05/25 15:51:25] [error] [output:forward:forward.1] no upstream connections available
May 25 15:51:25 4G-cluster-node-3 td-agent-bit[393331]: [2022/05/25 15:51:25] [ warn] [engine] failed to flush chunk '393331-1653493880.479264067.flb', retry in 8 seconds: task_id=0, input=tail.3 > output=forward.1 (out_id=1)
May 25 15:51:25 4G-cluster-node-3 smsd[393230]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, 


The messages start at 25 May, 15:51:25.

The error that increase the size of the syslog starts at 26 May, 03:24:18.

May 26 03:24:15 4G-cluster-node-3 td-agent-bit[393331]: [2022/05/26 03:24:15] [error] [upstream] connection #-1 to fluentd-wrong.core.insistnet.gm:24224 timed out after 10 seconds
May 26 03:24:15 4G-cluster-node-3 td-agent-bit[393331]: [2022/05/26 03:24:15] [ warn] [net] getaddrinfo(host='fluentd-wrong.core.xxxx.gm'): Unknown error
May 26 03:24:15 4G-cluster-node-3 td-agent-bit[393331]: [2022/05/26 03:24:15] [error] [output:forward:forward.1] no upstream connections available
May 26 03:24:15 4G-cluster-node-3 td-agent-bit[393331]: [2022/05/26 03:24:15] [ warn] [engine] failed to flush chunk '393331-1653535450.516867734.flb', retry in 11 seconds: task_id=899, input=syslog.0 > output=forward.1 (out_id=1)
May 26 03:24:18 4G-cluster-node-3 control_proxy[393271]: 2022-05-26T03:24:18.937Z [127.0.0.1 -> streamer-controller.core.insistnet.gm,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 2251bytes 0.023s
May 26 03:24:18 4G-cluster-node-3 magmad[393084]: /usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py:1226: RuntimeWarning: ignoring FileNotFoundError(2, 'No such file or directory') for file '/sys/class/hwmon/hwmon0/temp1_input'
May 26 03:24:18 4G-cluster-node-3 magmad[393084]:   warnings.warn("ignoring %r for file %r" % (err, path),
May 26 03:24:18 4G-cluster-node-3 magmad[393084]: /usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py:1226: RuntimeWarning: ignoring FileNotFoundError(2, 'No such file or directory') for file '/sys/class/hwmon/hwmon0/temp2_input'
May 26 03:24:18 4G-cluster-node-3 magmad[393084]:   warnings.warn("ignoring %r for file %r" % (err, path),
May 26 03:24:18 4G-cluster-node-3 magmad[393084]: INFO:root:Processing config update cluster-node-3
May 26 03:24:18 4G-cluster-node-3 td-agent-bit[393331]: accept4: Too many open files
May 26 03:24:18 4G-cluster-node-3 td-agent-bit[393331]: accept4: Too many open files
May 26 03:24:18 4G-cluster-node-3 td-agent-bit[393331]: [2022/05/26 03:24:18] [error] [input:tcp:eventlogs] could not accept new connection
May 26 03:24:18 4G-cluster-node-3 td-agent-bit[393331]: [2022/05/26 03:24:18] [error] [input:tcp:eventlogs] could not accept new connection

It is possible to see, that in less than 2 minutes the syslog increase almost 2.975 milion lines in the file. 
This total file have 340 MB. It can increase so fast, until get the full size of the Disk and make the AGW crashes.

Solution:

Inside the "/var/opt/magma/tmp/td-agent-bit.conf" it is possible to see the Retry_Limit False. 

Looks like we can edit this file here and set some value to makes the Retry quantity be 512, and not false, as it was configured.

@andreilee @uri200  What is the difference when retry is set to 512 ? What will happen when it reach 512 retry ? Just this change on the configuration file can solve this issue ?

**Comment by uri200** [comment]
Hey @alledpaiva since td agent is using fluent bit I think it would be better to post at that project mutineers repo https://github.com/fluent/fluent-bit

**Comment by crbertoldo** [comment]
Perhaps the following, not teste, can help:
```
sudo sed -i '14 i LimitNOFILE=20000' /etc/systemd/system/magma@td-agent-bit.service
sudo systemctl restart magma@magma@td-agent-bit
```
https://github.com/fluent/fluent-bit/issues/5460#issuecomment-1134530751
