### ISSUE TITLE
[IPV6] IPv6 traffic is failing 

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11761]
-Version:
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: bare-metal (AGW)-VM based

### Describe the Issue
1. Trigger PDU-Session with session type as IPV6.
2. Trigger traffic over gtp-tunnel created with source and dst address as IPv6.
3. Check the sessions and traffic.

**Expected behavior**
Check that sessions are coming up successfully and traffic is also working fine.

**Additional context**
Logs and pcaps
[https://app.zenhub.com/files/170803235/dbcebe0f-0cd1-4adf-beb2-3fac91ca9bf5/download](https://app.zenhub.com/files/170803235/dbcebe0f-0cd1-4adf-beb2-3fac91ca9bf5/download)
![ipv6tvmcaptur](https://user-images.githubusercontent.com/91061578/156309063-1aa641b7-cf43-4c1a-a698-5723f0381901.PNG)

**Comment by moinuddin1980** [comment]
Here is the analysis from the IPV6 traffic failure analysis.

1. Address assigned by mobilityd is 
  magma@TVM3-SA:/var/log$ sudo cat syslog | grep "INFO:root:Allocated IP"
  Mar  2 03:23:29 TVM3-SA mobilityd[2314676]: INFO:root:Allocated IP **fdee:5:6c:1607:b1e9:a58d:645c:1f79** for sid IMSI222456000000101 for apn internetv6
2. Same info is passed properly to sessiond and pipelined
  Mar  2 03:37:20 TVM3-SA **sessiond**[2314685]:           ue_ipv6: "**fdee:5:6c:1607:b1e9:a58d:645c:1f79**"
  Mar  2 03:37:20 TVM3-SA **pipelined**[2314763]:         ue_ipv6: "**fdee:5:6c:1607:b1e9:a58d:645c:1f79**"
3. During the PDU session establishment accept message preparation, **only the interface identifier is encoded in PDU address information and not the full ipv6 address **.
   Address sent to UE in PDU session establish accept is "**::b1e9:a58d:645c:1f79**"
![ipv6addr](https://user-images.githubusercontent.com/93516965/156356525-c40ead55-64c2-4bbe-8964-39e3466b5956.jpg)
4. Based on the script's own interpretation of the bytes before :: it sends the source IP as "**fe80::b1e9:a58d:645c:1f79**" 
    As this entry is not present in the fast-path tables the traffic cannot go through.
![ipv6addr-solicitation](https://user-images.githubusercontent.com/93516965/156356824-ef4fba40-1460-44a0-a4ae-f9f900a9fbe4.jpg)

**Comment by moinuddin1980** [comment]
Currently IPV6_INTERFACE_ID_LEN is defined as 8 which is correct as per TS24.501 Table 9.11.4.10.1
file:"lte/gateway/c/core/oai/common/common_types.h" 
// IPv6 Interface Identifier length in bytes
#define IPV6_INTERFACE_ID_LEN 8
Because of this the PDU address IE length field is set to 9 and thus only the interface identifier part of the address is sent in the pdu session establishment accept.
![TS24501-IPV6-ADDR-IE](https://user-images.githubusercontent.com/93516965/156379562-d1d0f8d7-c024-4e3b-8901-228c8b58d653.jpg)

Further investigation has to be done in the following area.
1. How the script is going to prepare the UE address based on the link local interface identifier sent in the PDU session establishment accept and send the router solicitation with proper UE ipv6 address?

**Comment by NeelimaKalpana** [comment]
Hi Arun,

Please share working Pcpas of IPV6 with traffic from TVM-Core .

**Comment by NeelimaKalpana** [comment]
Still waiting for Fix.
