### ISSUE TITLE
Observing Uplink and downlink traffic issue when we attach the policy to the subscriber 

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11867]
magma version: 1.7.0-1645582388-d3289720

Pipelined was not able to update the configured Policy AMBR values, Hence we are observing Uplink and Downlink Traffic issue. Please check the attached logs and pcaps for the same.

 [https://app.zenhub.com/files/170803235/d48eae21-4e0a-4083-9798-eb13950fe70a/download](https://app.zenhub.com/files/170803235/d48eae21-4e0a-4083-9798-eb13950fe70a/download)

**Comment by GANESH-WAVELABS** [comment]
@NeelimaKalpana and @rupa455wavelabs ,

From the syslogs I could see in `policy_1` `ip_src` and `ip_dst` are configured wrongly, due to this python throwing ValueError: invalid ipblock as listed in below image:
![image](https://user-images.githubusercontent.com/70899516/156221844-4354487d-2bba-4da2-952b-6476c4a67777.png)

In python `ipaddress` module method `IPv4Network` default parameter for `strict` always set to true.  Please refer below python documentation:
![image](https://user-images.githubusercontent.com/70899516/156222694-aa715e6a-de10-4c0c-badc-c80562b89843.png)

So, If you mention character `/` after any IP address then it will treat it as sub net mask. generally it used for network not for hosts.  If you mention `/` and try to set host bits in python it will treat as invalid address and throws `ValueError.` as shown below:
![image](https://user-images.githubusercontent.com/70899516/156223142-e816a9ac-ea39-4324-a4e3-3c326a11b6d6.png)

So, Could you please remove the subnetmask in `policy_1` and try to execute the PDU session establishment and let me know the result?

**Comment by NeelimaKalpana** [comment]
Hi Ganesh , 

Please find the requested logs for the actual issue reported in the bug.

We are seeing Traceback in the Pipelined , and traffic is not flowing when a policy is applied.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/147d8ee1-293f-4171-81da-103055b7d3ac)[https://app.zenhub.com/files/170803235/0f033ef9-be78-4603-8871-db3cb68849c4/download](https://app.zenhub.com/files/170803235/0f033ef9-be78-4603-8871-db3cb68849c4/download)

**Comment by NeelimaKalpana** [comment]
Tested different flow controls with Permit/Deny for IP and UDP traffic types . Observed that flow rules are getting updated at sessiond and pipelined properly but traffic flow is not matching with the rules configured.
Please find the logs attached for reference.

[https://app.zenhub.com/files/170803235/ffb9ec22-a4c9-4b31-9039-7094d7e89289/download](https://app.zenhub.com/files/170803235/ffb9ec22-a4c9-4b31-9039-7094d7e89289/download)

**Comment by GANESH-WAVELABS** [comment]
[21-March-2022 : Ganesh . I] : From the syslogs observed that while sending PDR information towards UPF, sessiond is not filling `flow_list` message in case of `UPLINK` for `static policies`. In case of `dynamic policies` `flow_list` message sending properly. Below is the GRPC message which explains this behavior.:
![image](https://user-images.githubusercontent.com/70899516/159340150-8d57e2b5-463a-499e-a0da-32924bec6e4e.png)


Where as in case of `DOWNLINK` sessiond is filling `flow_list` message properly for both static and dynamic policies:
![image.png](https://images.zenhubusercontent.com/608a39d761f99431f5047a77/9ac12d4d-5f19-4be9-823d-181c412f7ebe)

Root Cause : For static policies In `PipelinedClient.cpp` file below mentioned `if` block is not executing for `UPLINK` case so sessiond is not filling this for `UPLINK` case towards Pipelined.
![image.png](https://images.zenhubusercontent.com/608a39d761f99431f5047a77/3e17c095-cfb0-4986-878b-715d773f0e7f)
I have kept some more prints in TVM setup for pipelined below screen shot explains there is no flowlist for static policy and we can see flow_list is reflected in default dynamic rule.
![image.png](https://images.zenhubusercontent.com/608a39d761f99431f5047a77/5fd5df8d-3298-474e-a4ec-4d249f87332a)

NOTE: with stub pipelined_cli.py issue is not reproducing because stub is sending data as dynamic policy so both `UPLINK` and `DOWNLINK` were receiving `flow_list` message.

Solution : Sessiond should send `flow_list` message in `UPLINK` scenario as well.

**Comment by NeelimaKalpana** [comment]
Thanks Ganesh for the update . We Will wait for the fix.

**Comment by NeelimaKalpana** [comment]
This issue is not observed .
Please find attached logs.
[https://app.zenhub.com/files/170803235/d04f83ab-db3c-4b2e-823f-d297939d8618/download](https://app.zenhub.com/files/170803235/d04f83ab-db3c-4b2e-823f-d297939d8618/download)
