### ISSUE TITLE
[S1ap tests] test_ics_timer_expiry_with_mme_restart.py is failing

### ISSUE THREAD

**Issue by rsarwad** [magma/magma#11902]
test case, test_ics_timer_expiry_with_mme_restart.py is failing on master codebase

### Your Environment

- Version: Latest master code base
- Affected Component: Access Gateway
- Affected Subcomponent: MME service
- Deployment EnvironmentVagrant (AGW)

### Describe the Issue
On latest master codebase, test case, test_ics_timer_expiry_with_mme_restart.py is failing
**To Reproduce**
Execute test case, test_ics_timer_expiry_with_mme_restart.py on latest master codebase

**Comment by ssanadhya** [comment]
This failure seems to have skipped CI since the test case eventually passes, in a little over 600 seconds. This is true even for local setup, if you let it run for that long. The test case is not failing since the MME misses ICS timer expiry, but it gets mobile reachability timer expiry, then runs Implicit Detach timer and eventually sends a UE context release indication, which is expected by the test case.

I see similar runtime of this test case on https://docs.google.com/spreadsheets/d/1bukVQpXW_CH4qTXUeiFdRAhkUlHmbapaeSVi_OTc-Cw/edit#gid=907239386 
cc: @VinashakAnkitAman

**Comment by VinashakAnkitAman** [comment]
Github Issue id #11894 points to same issue and both the issues should be closed after PR #11909  merge
