### ISSUE TITLE
Pin docker image versions with the sha hash

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#11928]
## Intention

This issue was created as a documentation effort of the discussion about docker image stream tag strategies [in Slack](https://magmacore.slack.com/archives/C02HRAXJEBB/p1646274228887789).

## Current state

In a phase of rapid development it is advantageous to have a rolling release scheme for docker images to benefit of newest additions and fixes. Thus for the `magma/devcontainer` image, the tag `latest` is used.
Also see https://github.com/magma/magma/pull/11831, please.

## Issue

The ability to repeat testing on historical PRs / bisect the PR tree to investigate failures in the past, as well as possible long standing feature branches might see an issue with the rolling release strategy.

## Solution

Change the image pull image stream tag (back) to a hash based tag. The following places are relevant:
- https://github.com/magma/magma/blob/bdf1938ebe7b75d76da88ad2ce8b25ffbc42a957/.devcontainer/devcontainer.json#L33
- https://github.com/magma/magma/blob/bdf1938ebe7b75d76da88ad2ce8b25ffbc42a957/.github/workflows/magma-build-3rd-party.yml#L51

All other previous places were replaced by the bazel-base container.

## Additional comments

One might want to re-discuss this matter and re-evaluate also different docker image stream tag strategies, which might be able to well combined the different requirements, once that time has come.

**Comment by jheidbrink** [comment]
Some advantages of exact references over floating references:
* A Git commit can always point a to a know compatible version of a docker image. Older commits or commits on other branches won't break due to a backwards-incompatible container image upgrade. This specifically also protects release branches from breaking
* Updates to docker images can easily be tested on a branch before propagating to the master branch
* Docker image upgrades are visible in the Git history and thus transparent to developers
* The `latest` tag doesn't always work smoothly. For example, VS Code will keep using the Devcontainer that was downloaded when VS Code was first started. This has led to [errors in the Devcontainer image](https://github.com/magma/magma/issues/1422) being undetected for months
* * There is an [attempted workaround](https://github.com/magma/magma/blob/e5a78b21b10091db000d9d8d4a3c5b3d5b633d58/.devcontainer/devcontainer.json#L32), but it doesn't resolve the problem, and additionally prevents starting VS Code altogether when there is no internet connection
* Exact references can serve as unambiguous identifiers for build environments, for example to use correct cache keys for Bazel builds: https://github.com/magma/magma/issues/13361
