### ISSUE TITLE
Improve eNodeB configuration consistency

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#1219]
**Current implementation:**
It appears eNB parameters can be set in 4 places, which do not appear to synchronise:
1.    Directly in eNB UI
2.    In “Configure” view under “Network Configuration” tab
3.    In “eNodeB Devices” view in edit mode
4.    In “Gateways” view in edit mode under “LTE” tab

**Expected result**
These should be consolidated in to single configuration page and/or synchronised so conflicts can’t exist.

**Comment by 119Vik** [comment]
@ulaskozat @lionelgo  would be cool to get your feedback regarding this improvement

**Comment by xjtian** [comment]
Hey @119Vik, radio configuration happens in 3 places kind of by design. Not necessarily good design, but here is the rationale for how this works today:

- Most parameters are set at the network level (the "Configure" page) and apply across the entire network (i.e. to all gateways and radios). These are designed to be "set and forget" when you create a new network.

- We allow some of these parameters to be overridden on a per-radio basis. This is the set of fields in the enodeB configuration which also appear in the network configuration. We don't make this clear in the NMS, but if those fields are left blank, they will inherit values from the network configuration.

I think we can probably get rid of the gateway RAN configs (PCI, transmit enabled) and delegate those entirely to the enodeb configuration. There's another action item on our end to make the NMS config flows better which we're already looking into.

**Comment by andreilee** [comment]
This has been on our backlog for a while. Thanks for reporting this though, so now we have better awareness on the issue's visibility.

**Comment by jpad-freedomfi** [comment]
Hi Jacky, 
Thanks for the background. I get the tiered config approach. I think it is good. 2 requests/comments on it:
1. Can we add a text note or hover over info button in the eNodeB config window that says something like "Configurations here will supersede settings configured at the network level" or something to that effect. 
2. Can we check that a sync flow is working and clear to the user. Like what is the source of truth, Magma or device. Sounds to me like sync flow currently is intended to be MG_eNodeB -> MG_configure_network -> device. Is that correct?

Also, my views may be skewed by the fact that we are using a partially support eNB at this time. So perhaps getting TR-069 working smoothly with the Baicells 436Q will address the sync issues we are seeing.

**Comment by ekowtaylor** [comment]
Stale
