### ISSUE TITLE
[AMF]AMF is not sending proper reject for periodic-Registration  sent with Missing S-TMSI value.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#12401]
Version: 1.7.0-1647033962-eabc2f80
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: bare-metal (AGW)-VM Based

Describe the Issue
[AMF]AMF is not sending proper reject for periodic-Registration  sent with Missing S-TMSI value. Both Decoding and Encoding are failing here.

To Reproduce:
Please send Periodic registration with missing S-TMSI IE.

**Expected behavior**
Proper reject message should be sent to UE.

**Screenshots**
Pcap Screenshot
Failure cases:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/054b8e4c-4676-4c9b-9082-49053faf880a)

Pass Case:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/20932e36-3c9e-46d7-87ea-5f772b0de510)

Please find pcaps for reference.
[https://app.zenhub.com/files/170803235/21002376-cf8a-4814-b583-e70c6f7ef346/download](https://app.zenhub.com/files/170803235/21002376-cf8a-4814-b583-e70c6f7ef346/download)

**Comment by Sathyaj27** [comment]
Observations : 

1) Abot is sending wrong value in the script. As discussed with Neelima the issue seems to be in parsing. Even though value seems to be filled in her script. It is not reflected in pcap.
 -> mcc , mnc value is missing in nas pdu
-> Security capability length is filled as 0.( minimum required length is 2)

2) Since security capability length is filled as 0 and from code we are expecting a minimum fixed length 2 .
<img width="686" alt="decode_issue" src="https://user-images.githubusercontent.com/94469973/162938831-0013db68-76e5-4579-b0b3-27709b3971bb.PNG">
Due to this next ie value which is 2f is skipped and taken as 1 (adding length as 2).
This is causing decode failure.
3) From Logs I observe reject being triggered. But encoding fails as the values in pcap are mismatching.


Fixes required:
1) Scripts need to fixed on abot side.
2) Decode should not assume the length as 2 and skip 2 bits for next ie. 
3) Decode failure should return proper error cause.

**Comment by NeelimaKalpana** [comment]
Validate the Issue .
Logs attached for the same.[https://app.zenhub.com/files/170803235/cfee6eb9-7500-4539-8ee0-36f8af59a3d0/download](https://app.zenhub.com/files/170803235/cfee6eb9-7500-4539-8ee0-36f8af59a3d0/download)
