### ISSUE TITLE
Cleanup Github actions tab

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#13199]
### Describe the Issue

- **Current status:**
The [Github Actions tab](https://github.com/magma/magma/actions) is untidy and cluttered by a lot of workflows, which are outdated, abandoned, only used on forks, only used on branches, only used short term for testing, always broken, etc.
That makes it difficult to find the correct job, if searching for a specific workflow or action.
- **Actions from forks:**
Anyone can implement a new action on his fork. Given that this individual also creates a PR against the Magma repository, those newly defined workflows will also show up in the Github Actions overview. The current development policy does not allow to restrict this behaviour. Thus one will have to live with new workflows poping up once in a while and becoming outdated at some point.
- **Actions from branches:**
Same as for forks, but with the addition, that branches on Magma were once in the past the way to develop but are not any more. Still there exist some and contributers do in principle have the ability to create new branches.

### Describe the Target State

The [Github Actions tab](https://github.com/magma/magma/actions) should be tidy. This can be rephrased as
- Unused workflows should be removed.
  - Workflows are seen as unused after **90 days of inactivity**.
  - Inactivity means that a specific workflow had no execution in a time interval.
- A cleanup process should be implemented. The cleanup process should be automatic.

### Additional information

- The workflows themselves cannot be removed. They could only be disabled.
- Any workflow run can be removed.
- A workflow with no workflow runs will be removed from the display in Github Actions automatically. (Or they will not be displayed in first place, if they did never run.)

**Comment by LKreutzer** [comment]
I don't understand the point about workflows on forks. E.g. I have a bazel LTE integ test workflow on my fork which I use a lot. There is also a [draft PR for an older version](https://github.com/magma/magma/pull/12963/files). But I do not think that this will show up anywhere in the magma/magma actions since it lives in the LKreutzer/magma actions. So maybe I misunderstood, but without a merge I do not think this is relevant.

**Comment by Neudrino** [comment]
> E.g. I have a bazel LTE integ test workflow on my fork which I use a lot. There is also a [draft PR for an older version](https://github.com/magma/magma/pull/12963/files). But I do not think that this will show up anywhere in the magma/magma actions since it lives in the LKreutzer/magma actions.

Due to the configured triggers in the mentioned workflow it was never run on Magma repository so far. But you could just decide to add a new trigger (e.g. on push) and trigger that one (push to the branch). Then it would show up in the list.

**Comment by jheidbrink** [comment]
I don't see that removing older workflow runs is a remedy to the issues you describe. Given that in the default view the runs are ordered by date, removing older runs will only cut the tail of the runs you see or show you less pages to click through. It will not resolve the fact that you see runs from forks and branches that you are not interested in. I don't think that having a longer list of displayed runs is confusing per se.

On the other hand, I think it is a nice feature to be able to access older workflow runs. We retain workflow logs and artifacts for 90 days. I would prefer to keep workflow runs at least that long so that we can easily access those retained logs. Personally I wouldn't remove workflow runs at all, at least not for reasons of increased clarity which I think is not achieved by deleting. Chances are that it will turn out helpful to look back in time at the results of old workflow runs.

Before implementing a deletion policy, we should probably discuss this with a wider audience. Developers that don't read all Github issues might be surprised by deletions, especially with a grace period of 30 days.

**Comment by Neudrino** [comment]
Discussed the with @jheidbrink offline to clarify the topic and boundary conditions of this cleanup again.
The main point is, that it is not about the table of workflow runs on the right hand side of the actions page, but about the list of workflows itself on the left hand side.

**Comment by Neudrino** [comment]
Within a discussion in the community as alternative also a whitelist solution was discussed.

Following points were made:
- There are no money costs involved with preservation of workflow history.
- There are two adversary cost aspects:
  1. *Not* deleting workflows brings cognitive and time costs of developers to live and work with a possibly untidy workflow overview.
  1. Deleting workflows brings the potential "virtual costs" of unavailable workflow run data in future.

:balance_scale: The majority of the discussion participants favoured the path of **not deleting workflows**.

It was further discussed that
- a manual cleanup should happen, whenever one sees the need for it.
  - a non-CI script could be used to support this.
- no responsible person or groups should be assigned.

I.e. this means that this issue will be closed, without action, keeping the status quo.
