### ISSUE TITLE
Unclear link descriptions in Contributor Guide home

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#13407]
### Your Environment

This pertains to the Contributor Guide home page at https://github.com/magma/magma/wiki 

### Describe the Issue

The nav items listed in the text of the page are named and described inconsistently. As a result users looking for information may have trouble navigating available resources. 

#### To Reproduce

1. Go to https://github.com/magma/magma/wiki 
2. Scroll down to "For more information consult one of the following resources."
3. Try to predict which link will lead to which information using only the text, and not previous experience.

In practice, the link text doesn't describe the type of information available. A person looking for information will likely end up hunting at random. 

#### Expected behavior

A person looking for information should be able to understand what kind of information a link will yield before clicking.

#### Screenshots

<img width="721" alt="image" src="https://user-images.githubusercontent.com/111581/180795387-1d7a6fa1-3265-47f4-ad31-e16098b1b6d3.png">

**Comment by lucasgonze** [comment]
I propose the following:

---

- [Home](https://magmacore.org/): top-level landing page for the project as a whole
- [Operation](https://docs.magmacore.org/docs/basics/introduction.html): deployment and usage help
- [Development](https://github.com/magma/magma/wiki/Contributor-Guide): contributor guide (this subsite, a wiki in Github)
- [Workstreams](https://wiki.magmacore.org/collector/pages.action?key=HOME): meeting notes and project management (also called "Confluence")

**Comment by ildikov** [comment]
Thanks @lucasgonze for looking into this.

In my opinion most of the current link names in that list are intuitive and give enough information for people to know what to expect when they click on them.

Reflecting on your proposal in more details:
- Home: When using this link you are providing the readers of a website the option to easily navigate back to the landing page. Using 'Home' for a link that is pointing to another website is confusing and therefore I would recommend not to use it here. 'Magma website' is a sufficient link text to help people to get to the project's website.
- 'Operation': This term is restrictive as technically it does not include installation, configuration, etc. Using 'Magma project documentation', in my opinion, is sufficient, we can add some clarifying text such as 'deployment, configuration and usage of the platform'
- 'Development': Using this term excludes a good chunk of the Contributor Guide's content, since the word 'development' indicates software development and that is not the only form of contribution. Referring to the Contributor Guide by its name as the link text is a clear choice. We can always add some clarifying text to say something like 'information about tools and processes to contribute and participate in the community'.
- 'Workstreams': I don't think that this term is widely used in the community and it is also not very descriptive in terms of what's on the other end of the link. I would use 'Magma Wiki' here and point to Confluence.

As a summary, I would have:
- [Magma website] (https://magmacore.org/)
- [Magma project documentation] (https://docs.magmacore.org/) (Deployment, configuration and usage information)
- [Magma Contributor Guide] (https://github.com/magma/magma/wiki/Contributor-Guide) (Information about tools and processes to contribute and participate in the community)
- [Magma Wiki](https://wiki.magmacore.org/collector/pages.action?key=HOME) (Meeting notes and project team resources)

**Comment by lucasgonze** [comment]
Closed by fixing in the wiki. This ticket was open after the fact.
