### ISSUE TITLE
[enabler] rules_docker is documented for magma usages

### ISSUE THREAD

**Issue by nstng** [magma/magma#13549]
out of scope goal: magma setup via container is coming

here:
* try out bazel docker rules, e.g., [rules_docker](https://github.com/bazelbuild/rules_docker)
* build an image (can just be an example) and present in team
* optional (if easy): take one of the service Dockerfile containing a bazel-build and create it with bazel
* create follow up issues for using bazel for the containerized agw setup

Timeboxed

**Comment by jheidbrink** [comment]
[rules_docker](https://github.com/bazelbuild/rules_docker/) is "_a set of rules for pulling down base images, augmenting them with build artifacts and assets, and publishing those images_".

In the POC #13574 we used rules_docker to build a docker image for the C-service liagentd and for the python services directoryd, subscriberdb, enodebd and ctraced. We verified that those images can be run in the docker-compose setup. We also verified that the containers can be built and run on an ARM architecture using a T4g EC2 instance, similar to the test plan described in #12877.

**We found that using rules_docker produces well-structured and easy to read build recipes. We didn't encounter any major hurdles.**

rules_docker can build docker images without requiring a docker setup. However, this is only true as long as we don't need to execute commands inside the container, like apt-get in order to install packages. In our case we need to install packages, so we do require a docker environment. For our tests inside the devcontainer, we exposed the docker socket of the host to the devcontainer.


**Rejected approach:**

There is an approach to installing packages without running commands inside the container by using the `deb_file` parameter of `container_image` as done in https://github.com/GoogleContainerTools/distroless/blob/e6e90e55f677def0fb6fd86db11d86ff93cf15ed/base/base.bzl#L24-L28
This approach "installs" the deb files simply by unzipping them, and without running the pre- and post-install scripts.

This approach worked, but required us to manually specify all transitive dependencies of the .deb files we want to install. Furthermore it produces images that are broken from `apt-get`'s point of view, and thus are harder to customize.
