### ISSUE TITLE
Mypy errors not reported in all relevant files in PRs

### ISSUE THREAD

**Issue by voisey** [magma/magma#13935]
The reviewdog mypy action, which is used in [this workflow](https://github.com/magma/magma/blob/master/.github/workflows/reviewdog-workflow.yml#L194), is not reporting errors in all relevant files. See [this issue](https://github.com/reviewdog/reviewdog/issues/1211) for a full description of the problem in the reviewdog repo.

**Comment by mpfirrmann** [comment]
The feedback given by the reviewdog maintainers was, to 
> 
>     * make sure you have reporter as "github-check" or "github-pr-check"
> 
>     * make sure your github token is properly passed to reviewdog and that it has permissions to write to the checks api
> 
Otherwise we may be stuck with 10 error annotations, https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md#limitations.
While I do believe, we are passing the github token properly, we currently use `reporter: github-pr-review` instead of the recommended `reporter: github-pr-check` (which would also be the default).
May be worth giving it a try.
