### ISSUE TITLE
`test_3485_timer_for_default_bearer_with_mme_restart` is flaky

### ISSUE THREAD

**Issue by voisey** [magma/magma#14054]
I analysed the last 15 times the [lte-integ-test](https://github.com/magma/magma/actions/workflows/lte-integ-test.yml) workflow failed and most failures (6) were due to this test, specifically numbers 4279, 4284, 4286, 4288, 4290, 4291.

[4284](https://github.com/magma/magma/runs/8581342581) is due to:

`AssertionError: 14 != 28`

The rest, e.g. 
[4291](https://github.com/magma/magma/actions/runs/3148198287/jobs/5118478607), [4300](https://github.com/magma/magma/actions/runs/3161998010), [4292](https://github.com/magma/magma/actions/runs/3148778711), [4291](https://github.com/magma/magma/actions/runs/3148198287), [4290](https://github.com/magma/magma/actions/runs/3142870045), [4288](https://github.com/magma/magma/actions/runs/3141952716) are due to:

`AssertionError: Timeout (60 sec) occurred while waiting for response message`

The failures should be analysed in more detail so that we can come up with a fix.

Hint: Possibly helpful documentation with information about the 3485 timer.
https://www.etsi.org/deliver/etsi_ts/124300_124399/124301/09.02.00_60/ts_124301v090200p.pdf

Ideas:
Maybe the MME restart takes too long and messages are dropped in that case? The timer is only repeated 4 times / 32 seconds?

Tasks:
- [ ] Improve test stability.
- [ ] Prepare internal review meeting.

**Comment by wolfseb** [comment]
Looking through the logs of the failing runs, the first of the three failures (-> flaky retry) is always due to `Assertion Error: 14 != 28`

**Comment by wolfseb** [comment]
After some testing on the github runner, and locally, we found the following:
* If the time between initiating the mme restart and the `get_response` is longer than 30s, the tests fails with `14 != 28`
* On the CI, when this time is 27s, it sometimes fails and sometimes doesn't, so this is not the issue (although sometimes it goes beyond 30s, so some test failures may be caused by this)
* The mme logs suggest that pipelined is fully loaded, so this cannot be the culprit either
