### ISSUE TITLE
[AGW Docker Containers Build Issues] Port 3333 not open 

### ISSUE THREAD

**Issue by frmess** [magma/magma#14137]
### Description
The port 3333 on the AGW host is not open,, so the pipelined service is not listening on this port, hence LTE integ tests and FEG integ tests are failing with this message error: 
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.60.142', port=3333): Max retries exceeded with url: /stats/switches (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc4bbe3460>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
### Scenarios
This is the case in the FEG Integ Tests
- RUN 702: https://github.com/magma/magma/actions/runs/3227519111 with these tests:
test_sctp_abort_after_auth_req with error.py
test_duplicate_attach with error.py 
test_attach_missing_imsi with error .py
test_attach_detach_after_ue_context_release with error .py
test_nas_non_delivery_for_auth with error.py
test_attach_emergency with error .py
test_attach_esm_information_wrong_apn with error.py
test_no_auth_response with error .py

### Solution 
When deploying the AGW containers with the compose file `docker-compose.yaml` you should also run the file `docker-compsoe.dev.yaml`

```bash
docker-compose [--env-file .env] -f docker-compose.yaml -f docker-compose.dev.yaml up -d [--force-recreate]
```

**Comment by kimberqiqi** [comment]
Since magma had removed the file docker-compose.dev.yaml, I touched it and copy the contents in this file.When I run this commond:docker-compose --env-file .env -f docker-compose.yaml -f docker-compose.dev.yaml up -d --force-recreate, I have received this error:
![image](https://user-images.githubusercontent.com/109064396/196096591-25cc173c-a9f8-4199-b7ed-499f98fc8d81.png)

**Comment by kimberqiqi** [comment]
What process it ienvoy_controller. Was it replaced by control_proxy?

**Comment by frmess** [comment]
@kimberqiqi You need to check if the service pipelined is running and listening on the port 3333
```
systemctl status pipelined
netstat -nlptu | grep 3333 
telnet localhost 3333
```

**Comment by kimberqiqi** [comment]
Thank you for you replay, I have found the solution from here: https://docs.magmacore.org/docs/next/lte/dev_notes#developer-notes.

**Comment by frmess** [comment]
Yeah, that documentation is a good one!

**Comment by nstng** [comment]
The integration tests running vs the containerized agw in CI - see https://github.com/magma/magma/actions/workflows/agw-build-publish-container.yml. This means pipelined on 3333 is accessible. I assume this was fixed in the mean time.
Will close for now - if I misunderstood then feel free to reopen this issue.
