### ISSUE TITLE
Investigate using Go to get Radius dependencies instead of copying code into the repository

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#14184]
The folder https://github.com/magma/magma/tree/master/feg/radius/lib/go/radius contains a lot of vendored dependencies, especially ./radius  is a fork of https://github.com/layeh/radius. It is unclear why we do not just pull them from upstream via go. That would also give us 3 years worth of patches and fixes.

Necessary steps:
* Look at the history of the radius folder and figure out if it was only for xwf. If yes, we do not need these changes.
* If changes are not necessary, remove the folder and pull radius as a regular go dependency. Get the build and tests green again.
* If the changes turn out to be necessary after all, document it and close this issue. See also #13671.

Tasks:
* ~~[ ] Find out what the services are doing that are related to authentication and authorization, like aaa, eap, eap_aka, uesim, radiusd~~
* [x] Try to remove components that still use radius and that are only related to xwf and no longer needed.
* [x] For all other usages (e.g. rfc...), try to replace the checked in radius by the official radius from Go repositories.
* [x] If everything works, delete the radius folder. If it doesn't work, document the issues and discuss with the team.
* [ ] Prepare internal review

**Comment by wolfseb** [comment]
@MoritzThomasHuebner and I found the following:
Radius is not quite straightforward to remove / exchange. The main points are:
* There are several custom additions in the radius folder that need the Radius code locally for go to generate code (otherwise the types don't match). These are:
  * Expresswifi (which is deprecated anyway)
  * Ruckus (which appears to be tightly linked with expresswifi)
  * COA (which might be mostly linked to expresswifi)
* The code is referenced in other parts of the repo, e.g. `sse_listener`, which seem to be used only for the xwf as well
* For the rest of the packages (in the format `rfc****`), we need to check if it can just be replaced
