### ISSUE TITLE
Analyze current large cached artifacts and add them to no-cache mechanics

### ISSUE THREAD

**Issue by nstng** [magma/magma#14444]
Analyze what currently are large artifacts that are transfered from/to the remote cache.
* see if the no-cache tag actually works (used in .deb related artifacts)
* add more large targets that can easily be build on-the-fly

**Comment by vktng** [comment]
Build-buddy was used for the cache analysis. The list of large targets were collected by building everything (`bazel build //...`) with disk cache and then collecting the data with the following commands:
```
find .bazel-cache/cas/ -name '*' -type f -exec du -s {} \; | sort -n -r > cache_sizes.txt
for f in $(cat cache_sizes.txt | head -155)
do
    if [[ $f == ".bazel-cache"* ]]
    then
        HASH=$(basename $f)
        echo $HASH
        timeout 60 strings $(grep -r "$HASH" | grep 'Binary file' | awk '{print $3}') | grep "bazel-out" >> larger_than_5mb.txt
    fi
done
```

The `--experimental_allow_tags_propagation` flag was used to ensure that the `no-cache` tag is not ignored. The `agw_of` and `mme_oai` targets were not included in the blocked list.

Results from Build-buddy:

1. `bazel build //...` on master
   * used data: 4453.4 MB
2. `bazel build //...` with ~50 largest targets blocked
   * used data: 3684.9 MB
   * saved: 768.5 MB
3. `bazel build //... --config=asan` on master
   * used data: 5778.5 MB
4. `bazel build //... --config=asan` with ~50 largest targets blocked
   * used data: 4302.2 MB
   * saved: 1476.3 MB
5. `bazel build //... --config=production` on master
   * used data: 5219.5 MB
6. `bazel build //... --config=production` with ~50 largest targets blocked
   * used data: 3675.2 MB
   * saved: 1544.3 MB
7. `bazel build //lte/gateway/c/core:agw_of` on master
   * used data: 685.1 MB
8. `bazel build //lte/gateway/c/core:agw_of` with `no-cache` tag
   * used data: 571.2 MB
   * saved: 113.9 MB
   * note: only the `cc_binary` allows the use of the tag, `cc_library` throws an error.


Plan: create PR with the largest artifacts blocked. Tests should be excluded from the blocked list, because the results are also cached and running them could significantly increase the build times. PR should be run multiple times in CI to get an accurate picture of the runtimes. Adjust as needed.

**Comment by vktng** [comment]
A new [GitHub Wiki page](https://github.com/magma/magma/wiki/Bazel-cache-analysis) was created to documents how to debug cache related issues.

**Comment by vktng** [comment]
Without the tests being excluded from the caches the saved data is between 400 and 500 MB-s for every build.
