### ISSUE TITLE
Exactly specify bazel-base container versions

### ISSUE THREAD

**Issue by jheidbrink** [magma/magma#14450]
Instead of referencing the bazel-base container image version with the floating `latest` tag, reference the image by it's sha256. This allows to

* test changes on a branch before merging them to master
* gracefully roll out backwards-incompatible changes
* make sure that the image keeps working on release branches
* use the image hash as unique cache key for Bazel in #13361

This is related to #11928 where it was done for the devcontainer.

**Comment by LKreutzer** [comment]
Most workflows now use the bazel Docker cache images, which are rebuild weekly at the moment. It seems unpractical to have one PR per week to update the SHAs of these images in the workflows.

I would suggest to close this as not planned at the moment, due to the current Docker cache setup. Would you agree @nstng ?

**Comment by nstng** [comment]
> I would suggest to close this as not planned at the moment, due to the current Docker cache setup. Would you agree @nstng ?

I agree - I will close this
