### ISSUE TITLE
Check 1.8.0 release branch for regression

### ISSUE THREAD

**Issue by mpfirrmann** [magma/magma#14873]
Run tests with the 1.8 branch / 1.8 release artifacts to ensure the functionality with respect to 3rd party changes.

- [x] Set up and tests containerized AGW with 1.8 release images by manually adding the LF artifactory as `DOCKER_REGISTRY` and 1.8 as `IMAGE_VERSION` in `lte/gateway/docker/.env`.
- [x] Install and test 1.8 debian package on a bare-ubuntu machine (similar to the CI tests, can also be done locally with the setup script to mimic production).
- [ ] Run package job (Magma Build & Publish) #15049 
- [x] Test helm charts
- [x] Ensure that the backporting process is functional and all relevant workflows are enabled
  - [x] Related to this is https://github.com/magma/magma/issues/14937, but this may be out of scope and handled separately.

**Comment by LKreutzer** [comment]
Updated the title and content of this issue after discussion with @nstng.

**Comment by LKreutzer** [comment]
It might be worth back-porting the CI fixes for the [`save-state` phase-out](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). I can see warnings on the v1.8 branch, e.g. here
![Screenshot from 2023-02-02 10-28-54](https://user-images.githubusercontent.com/34488763/216285413-11ed5780-ecab-4985-b29e-a506ad946285.png)

**Comment by LKreutzer** [comment]
FYI: I saw many failures of this job https://github.com/magma/magma/actions/runs/4074215488/jobs/7020519837, something might be broken for the Make AGW unit tests.

**Comment by MoritzThomasHuebner** [comment]
Update: I worked on this with @wolfseb who is currently on vacation.

- [x] Install and test 1.8 debian package on a bare-ubuntu machine (similar to the CI tests, can also be done locally with the setup script to mimic production). -> We managed to get a machine running and checked the logs for any smoking gun errors. All error messages we found are also present on a magma_dev machine built from master.
- [ ] Run package job (Magma Build & Publish). -> We executed the steps locally and we obtain a magma*.deb. However, there are still some issues. When building the magma*.deb, some python dependencies are up we obtain an incomplete of magma dependencies. We did not yet manage to install it on a bare magma_deb machine for testing.
- [ ] Test helm charts. -> This point is still somewhat unclear. We started by going through the [minikube deployment](https://magma.github.io/magma/docs/orc8r/dev_minikube#deploy-on-minikube) steps and successfully deployed the orc8r on the host machine. However, this is not yet the complete set of helm charts. We did not yet succeed in deploying the lte-orc8r helm charts. There are also helm charts in other components such as the feg which we have not yet deployed/tested.
- [ ] Ensure that the backporting process is functional and all relevant workflows are enabled -> We created a [dummy backport PR](https://github.com/magma/magma/pull/14948) that would trigger all relevant workflows.

**Comment by MoritzThomasHuebner** [comment]
> FYI: I saw many failures of this job https://github.com/magma/magma/actions/runs/4074215488/jobs/7020519837, something might be broken for the Make AGW unit tests.


@LKreutzer on my backport branch it looks ok. Maybe the test is just flaky?
https://github.com/magma/magma/issues/14873#issuecomment-1413839446

**Comment by LKreutzer** [comment]
> > FYI: I saw many failures of this job https://github.com/magma/magma/actions/runs/4074215488/jobs/7020519837, something might be broken for the Make AGW unit tests.
> 
> @LKreutzer on my backport branch it looks ok. Maybe the test is just flaky? [#14873 (comment)](https://github.com/magma/magma/issues/14873#issuecomment-1413839446)

Thank you for checking - yes it is quite possible that the Make tests are flaky. It is probably okay as it is - if you want to go in more depth I suppose we could run the tests locally repeatedly, but this may not be necessary.

**Comment by LKreutzer** [comment]
> > > FYI: I saw many failures of this job https://github.com/magma/magma/actions/runs/4074215488/jobs/7020519837, something might be broken for the Make AGW unit tests.
> > 
> > 
> > @LKreutzer on my backport branch it looks ok. Maybe the test is just flaky? [#14873 (comment)](https://github.com/magma/magma/issues/14873#issuecomment-1413839446)
> 
> Thank you for checking - yes it is quite possible that the Make tests are flaky. It is probably okay as it is - if you want to go in more depth I suppose we could run the tests locally repeatedly, but this may not be necessary.

Update:
I suspect that the `sessiond_integ_test` is flaky. This is where the Make workflow is failing. In the Bazel workflow this test fails 2/3 runs. But in Make there is no retry logic.
```
//lte/gateway/c/session_manager/test:sessiond_integ_test                  FLAKY, failed in 2 out of 3 in 60.0s
```

**Comment by MoritzThomasHuebner** [comment]
Some intermediary findings after running `fab dev package` locally without the LF artifactory. Some packages were only found locally and some only on the artifactory. Still needs more investigation:


Packages only found in LF artifactory:
- typing-extensions -> Can probably download the correct version?
- openvswitch -> Not sure, might be a special case
- systemd-python -> Can probably download the correct version? Also possible confusion with systemd package/
- attrs -> Can probably download the correct version? Also confusing because override section says build 19.3.0 and 20.3.0 is built.
- aioeventlet -> Can probably download the correct version
- click -> Can probably download the correct version
- json-pointer -> Can probably download the correct version

Packages only found locally:
- sortedcontainers -> Newer version
- hpack -> Newer version
- isort -> Newer version
- async-timeout -> Newer version
- js-regex -> Unclear. Same version artifact exists on focal-1.8.0 if we use the search bar, but I cannot find it in  https://linuxfoundation.jfrog.io/ui/native/magma-packages/focal-1.8.0/
- wrapt -> Unclear, package does not exist on focal-1.8.0 on artifactory
- frozenlist -> Unclear only appeared recently on the LF artifactory, lockfile did not have the entry before running pydep
- lazy-object-proxy -> Unclear, package does not exist on focal-1.8.0 on artifactory
- aiosignal -> New dependency
- hyperframe -> Unclear, does not exist on focal-1.8.0
- msgpack -> Unclear, does not exist on focal-1.8.0
- toml -> Unclear, does not exist on focal-1.8.0

**Comment by MoritzThomasHuebner** [comment]
Update:
I went through the following steps

- Start `magma` dev v1.8
- Disable lf artifactory && sudo apt-get update
- run `pydep` and `build-magma.sh` via modified fabfile
- Start `magma_deb` on master without installing magma
	- In lte/gateway/deploy/roles/magma_deploy/tasks/main.yml comment out 129-141 (magma install)
- Disable LF artifactory && `sudo apt-get update`
- Install created packages (sudo apt-get install ./*.deb)
- For each missing package
	- make sure the missing package exists in the ubuntu artifactory
	- if not: we need to have a closer look
	- elif yes: sudo apt download package
	-> Try again

Results:
- The `python-*.deb` packages seem to be self consistent. We can run `sudo apt-get install ./python3-*`.
- `td-agent-bit` and `magma-sctpd` can also be installed
- Trying to install `magma_1.8.0*.deb` fails due to the following missing dependencies:
```
         Depends: grpc-dev (>= 1.15.0) but it is not installable
         Depends: python3-aioeventlet but it is not installable
         Depends: libsystemd-dev but it is not going to be installed
         Depends: magma-cpp-redis but it is not installable
         Depends: libfolly-dev but it is not installable
         Depends: getenvoy-envoy but it is not installable
         Depends: sentry-native but it is not installable
         Depends: td-agent-bit (>= 1.7.8) but it is not installable
         Depends: bcc-tools but it is not installable
         Depends: oai-asn1c but it is not installable
         Depends: oai-gnutls (>= 3.1.23) but it is not installable
         Depends: oai-nettle (>= 1.0.1) but it is not installable
         Depends: prometheus-cpp-dev (>= 1.0.2) but it is not installable
         Depends: liblfds710 but it is not installable
         Depends: libczmq-dev (>= 4.0.2-7) but it is not going to be installed
         Depends: oai-freediameter (>= 0.0.2) but it is not installable
         Depends: magma-libfluid (>= 0.1.0.7) but it is not installable
         Depends: libopenvswitch (>= 2.15.4-9-magma) but it is not installable
         Depends: openvswitch-switch (>= 2.15.4-9-magma) but it is not going to be installed
         Depends: openvswitch-common (>= 2.15.4-9-magma) but it is not going to be installed
         Depends: openvswitch-datapath-dkms (>= 2.15.4-9-magma) but it is not installable
```
- After adding `magma.list` back to `/etc/apt/sources.list.d/` and running `sudo apt-get update`, we are able to install `magma_1.8.0*.deb`.
- Running `magma-start` does start all the services
- All services appear to be running

**Comment by panyogesh** [comment]
Closing it as 1.8 is released
