### ISSUE TITLE
Open vSwitch Kernel Module Unsupported Past Kernel 5.8.x

### ISSUE THREAD

**Issue by analogtypist** [magma/magma#14894]
### Your Environment

- **Version:** 1.8.0
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** SGW/PGW functionality, other functionality involving GTP
- **Deployment Environment:** bare-metal AGW

### Describe the Issue

The Open vSwitch Kernel module is not supported on kernel versions past 5.8.x, per upstream policy (see https://docs.openvswitch.org/en/latest/faq/releases/), as the Linux OVS tree datapath is deprecated starting with OVS 2.15 which magma currently ships. As Ubuntu 20.04 defaults to a rolling kernel update model with Ubuntu 20.04 where the kernel version is periodically updated to newer versions by default, the kernel version on a standard fully patched Ubuntu 20.04 system will be newer than the last version that supports the OVS kernel module and will thus experience issues with trying to use GTP since it is only supported in the userspace datapath without the patched version of the open vswitch kernel module that Magma ships.

Since this dependency is not noted in the installation instructions for the AGW nor addressed in the installation script, this means that GTP and the SGW/PGW components of the AGW do not work since the GTP interface cannot bind to the Open vSwitch Bridge created by the installer.

#### To Reproduce

1. Install Ubuntu 20.04 on a system
2. Apply all relevant package updates
3. Attempt to install the AGW components (either using the dockerized AGW or bare-metal AGW installation)
4. gtp0 interface fails to bind to open vswitch bridge which prevents GTP traffic (and thus SGW/PGW functionality) from working

#### Expected behavior

gtp0 interface binds properly to open vswtich bridge allowing GTP traffic (and SGW/PGW functionality) to work.

**Comment by Radula76** [comment]
I had an AGW ubuntu 20.04.5 with kernel 5.15 which I had to rollback to kernel 5.4.0-100.  running ovs-kmod-upgrade.sh to build ovs for that kernel worked.
Ideally we could uplift ovs to 3.0, this would then allow us to upgrade ubuntu to 22 (with increased driver and security patches).  its a lot of work.  alternatively we can look into eBPF: https://magma.github.io/magma/docs/lte/ebpf_datapath   which seems to have stalled post 1.7?

**Comment by btsimon97** [comment]
Open vSwitch does have a Linux Upstream datapath which uses a Linux kernel module that ships with the kernel instead of the out-of-tree module used by Linux OVS tree datapath currently being used by Magma. The Linux OVS tree datapath is the one that's deprecated in 2.15 and capped at Linux kernel 5.8.x, whereas the Linux upstream datapath is still fully supported per their FAQ.

Is it feasible to port the existing patches applied to the Linux OVS Tree Kernel module so that they land in a future upstream kernel release? Although it likely be difficult, this would have the advantage of no longer needing to do out-of-tree builds and ensuring that a stock kernel would eventually be able to run Magma without modifications.

In the short term though, the install documentation for the AGW needs to be updated to reflect the dependency (as its currently undocumented), and the install scripts may eventually need to be updated to handle the kernel downgrade if automating is desired.

**Comment by Radula76** [comment]
This is a good community question for the new CI/CD team? "CI/CD - Focused on the improvements and stabilisation of the CI/CD pipeline"

**Comment by panyogesh** [comment]
We have created OVS patches for Kernel version 5.15 (for 22.04) and performed the basic sanity. Based on community feedback will take it post 1.9
