### ISSUE TITLE
Document artifactory

### ISSUE THREAD

**Issue by voisey** [magma/magma#14920]
As far as I can tell, the [artifactory](https://linuxfoundation.jfrog.io/ui) is undocumented. A page should be added to the [wiki](https://github.com/magma/magma/wiki) including sections like:
* How is it hosted?
* How does the structure work with regards to different types of artifacts, e.g. CI and release?
* How does it work with Docker images, Helm charts, blob storage?
* What role does the artifactory play with regards to dependencies?
* How are these dependencies kept up to date?

**Comment by nstng** [comment]
First draft for the artifactory documentation - still unfinished and WIP

-------------------------------------------------------

# Magma Artifactory

This page documents the usage and the structure of the Magma artifactory located at https://linuxfoundation.jfrog.io/.

# Usage

The artifactory holds Magma artifacts and third party dependencies. This includes Debian artifacts, Docker images, Helm charts and general blobs (e.g., Go is uploaded for caching reasons). All artifacts are published by CI workflows. The artifactory is not intended for the manual publishing of artifacts. The artifacts are used in CI for testing and the setup of environments, in local development and in production environments.

# Hosting and Support

The artifactory is hosted by the Linux Foundation and is a [JFrog](https://jfrog.com/) instance. Write access tokens are configured as GitHub secrets in the Magma GitHub account. These tokens are not distributed for local usage. All write access must happen via GitHub workflows running on the Magma GitHub account. The artifactory is shared by multiple parties. Magma related sections are prefixed by `magma-` (see Structure for details)

General support can be queried via the Magma Slack at [#questions-to-linux-foundation-it](https://magmacore.slack.com/archives/C03TN1LM8CB) but this should usually be accompanied by opening an issue in the Linux Foundation [service desk](https://jira.linuxfoundation.org/plugins/servlet/desk).

# Structure

A general structural overview can be found at https://linuxfoundation.jfrog.io/ui/repos/tree/General. All Magma related sections are prefixed by `magma-`. JFrog has a concept of "Virtual Repositories", i.e., a virtual repository can hold a number of physical repositories. This is, virtual repositories are not only aliases for physical repositories, but can also hold a union of multiple physical repositories. In general it is a good practice to only use virtual repositories in code, so that physical repositories can be renamed or more repositories can be added.

## Debian Artifacts

Magma Debian artifacts include the Magma access gateway, sctpd, the dhcp CLI and third party dependencies (packaged python dependencies and patched or self compiled libraries).

Note: there are a couple of artifacts that will contradict the following documentation. These should be cleaned-up at some points. This includes unsupported architectures (e.g., some artifacts are labeled as `i386`, but seem to be unused), inobservence of folder structures, etc.

An apt sources entry for Magma has the following form:
```
deb https://linuxfoundation.jfrog.io/artifactory/<repository> <distribution> main
```
This is, only `deb` is supported and no, e.g., sources. The only available component is `main` and no, e.g., further staging. Usually, the architecture of artifacts is labeled as `amd64`, `arm64` or `all`. The different repositories and distributions are described in the following.

### Repositories

#### magma-packages-test

This repository is used for CI, local development and for testing releases. Important distributions are "focal-ci" and "focal-1.x.y" (e.g., "focal-1.8.0"). Note that the distributions are located in a sub-folder "pool" (e.g., https://linuxfoundation.jfrog.io/ui/native/magma-packages-test/pool/focal-ci/). This is different to the production repository (see below).

The repository "focal-ci" holds artifacts that are published directly from the current master. These artifacts are used in CI and in local development for testing.

The distributions "focal-1.x.y" are used to test release branches. Usually when a release branch is created, all publishing endpoints are switch from "focal-ci" to "focal-1.x.y". The CI then creates the artifacts in the new repository. These artifacts can now be used to test the release candidate.

#### magma-packages-prod

This repository is for production use. In comparison with magma-packages-test, no "pool" sub-folder is used and there is no "focal-ci" distribution. When a release candidate was tested successfully then the respective distribution becomes promoted to magma-packages-prod, i.e., artifacts are copied and not build and published.

The virtual repository "magma-packages" contains only "magma-packages-prod".

## Docker Images

## Helm Charts

## Miscellaneous

# Access

## Read

## Write - CI Workflows

NO ARM WORKFLOW

### Publish Test Artifacts

### Promote to Production Artifacts

**Comment by nstng** [comment]
Reviewer: please edit the comment above for small changes. Reach out for larger issues in Slack or via comment here.

Please write a comment if you are OK with the state at that time - will be seen as accepted review.

**Comment by LKreutzer** [comment]
Fixed some typos - lgtm! :+1:

**Comment by nstng** [comment]
Published to https://github.com/magma/magma/wiki/Magma-Artifactory
