### ISSUE TITLE
Linter: check for 404 errors in documentation links

### ISSUE THREAD

**Issue by mpfirrmann** [magma/magma#14962]
Links to external websites in the docs may lead to 404 errors from time to time. Introducing a CI job to check for this could prolong the time it takes for the docs to become outdated.

**Comment by LKreutzer** [comment]
This job should go into the `.github/workflows/docs-workflow.yml` workflow.

**Comment by MoritzThomasHuebner** [comment]
I was thinking about this today, I don't think this is a good idea. On the plus side, we would immediately be notified about a changed/broken link, however:
-  We would constantly have red runs during temporary third-party website outages.
- Writing a script to correctly extract all valid URLs from the documentation is relatively hard. Some URLs end before an underscore for example because they appear italicized in the docs.
- Some URLs are only meant to be used locally or are example URLs such as "http://yourdomain.com".

I wrote a small script for #15121 to identify broken links. I think running this manually from time to time and going over the retrieved items might be a better option.
