### ISSUE TITLE
Segmentation fault in Magma

### ISSUE THREAD

**Issue by MarioKrenn6240** [magma/magma#15083]
I enconter an segfault when running Magma.

### Your Environment
- Version: 2.27-5
- Machine type: intel64-linux
- Initial seed: 295558599
- Time to this point: 7929.95
- Memory usage: 136764.12MB
- Segmentation fault

### Describe the Issue

I get the following error message:

Magma V2.27-5     Fri Feb 17 2023 17:47:54 on zp03     [Seed = 295558599]
Type ? for help.  Type <Ctrl>-D to quit.

Loading file "g43_lift.magma"
Number of generators in B: Infinity
Time: 0.000

Magma: Internal error

Please mail this entire run [*** WITH THE DETAILS BELOW ***]
    to magma-bugs@maths.usyd.edu.au

You can print the entire input by entering:
%P

Version: 2.27-5
Machine type: intel64-linux
Initial seed: 295558599
Time to this point: 7929.95
Memory usage: 136764.12MB
Segmentation fault

Total time: 7929.949 seconds, Total memory usage: 136764.12MB

#### To Reproduce

1. Run the attached magma code.

#### Expected behavior

No Seg-Fault.

#### Additional context

Add any other context about the problem here (e.g. logs).
[g43_lift.magma.txt](https://github.com/magma/magma/files/10828756/g43_lift.magma.txt)

**Comment by MoritzThomasHuebner** [comment]
Hi @MarioKrenn6240, I think you are posting this in the wrong code repository. This project is code for a mobile code network. I think you are looking for a way to report a bug for the CAS magma, which is completely unrelated to our project.

You probably want to report your bug here http://magma.maths.usyd.edu.au/magma/faq/bugs
