### ISSUE TITLE
BUG(Integ_test): Failing testcase test_attach_detach_setsessionrules_tcp_data

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#15187]
### Environment
Magma Vagrant setup for integ_test 

- **Version:**: Latest Master (as of April-27th)
- **Affected Component:**  Access Gateway
- **Affected Subcomponent:** Integ_test
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

Integration test failure: test_attach_detach_setsessionrules_tcp_data

#### To Reproduce

1. Execute the integration test

#### Expected behavior

The testcases "test_attach_detach_setsessionrules_tcp_data" should pass

**Comment by Balaji-Jatla** [comment]
Please find the test logs below
[test_attach_detach_set_session_rules.log](https://github.com/magma/magma/files/11344141/test_attach_detach_set_session_rules.log)

**Comment by Balaji-Jatla** [comment]
``` 
Reproduced the issue in latest master and test case is passing successfully, Please find the the log below.
```
[set_session_rules.log](https://github.com/magma/magma/files/11399229/set_session_rules.log)

**Comment by maxhbr** [comment]
No PR linked? how was it resolved?

**Comment by Balaji-Jatla** [comment]
> No PR linked? how was it resolved?

Hello @maxhbr 

We encountered a failure in the test case when running it on our local system initially. However, upon further investigation and multiple subsequent runs, we observed that the test case passed successfully. The first time it got failed because of issue with local system. Due to this intermittent behavior and considering the test case as passing, we made the decision to close the related issue. Please note that if we notice the test case failing again upon observation, we will promptly reopen the issue for further investigation.

Thank you.
