### ISSUE TITLE
Magma integration with IMS Core for VoLTE

### ISSUE THREAD

**Issue by aseaudi** [magma/magma#15182]
I have an IMS Core up and running and tested with commercial samsung smartphone, but with Open5GS.

I am trying to replicate the scenario with magma, however, i noticed magma does not behave in a similar way.

Here's what i did to try to integrate with the IMS Core:
* I add another APN to the subscriber called IMS with the correct QCI=5, in addition to internert APN with QCI=9,
* and update the PCSCF address by the MME to be sent as a PCO to the UE
* also modified the "IMS over PS supported" from yes to no in mme.conf to be sent to the UE
 
But it didn't work:
* in the attach procedure, magma sends an activate bearer request to the EU for the IMS APN instead of internet APN
* then the UE tries to send PDN request using internet APN, however, magma sends error like "multiple pdn not supported on the same APN"
* after several attempts, i now have a UE with 2 bearers for internet and IMS, however, they are allocated in the same subnet 192168.128.0/24.
* Also, the UE does not start the SIP registration procedure as expected

If I remove the IMS APN from the subscriber:
* The UE properly receive Activate bearer request for internet APN, gets IP Address, and internet is OK
* UE then send PDN request for IMS APN, which is expected to start IMS procedure, so far so good
* Magma replies with "unknown APN", which is expected, since I removed IMS APN from the subscriber

What is the correct way to integrate magma core with and IMS core ?

**Comment by Radula76** [comment]
I had a go at getting a Samsung S21 an ipv4 'internet' APN address and an ipv4v6 'ims' APN address which seemed to work. I had non-NAT AGW configured.  the internet and ims APN both had IP addresses from the same ipv4 pool, the ipv6 was from the ipv6 pool.  the routing in my network wasn't correct so there was no payload back to the Ue.  I'll have to re-configure it again to test.
fadmin@rtcoreftx:/var/log$ mobility_cli.py get_subscriber_table
SID             IP              APN
IMSI999999000000103     192.168.128.12  internet
IMSI999999000000103     192.168.128.13  ims
IMSI999999000000103     fdee:5:6c:1477:7b38:95be:f9f9:b8ed      ims

the configuration needs IMS over PS support turned ON.
the internet APN has QCI 9/15 and ims 5/9, this is needed to separate the traffic tunnels because they are the same subnet.  I think the ims one could be lower, because ims signalling could be 5/1 but voip traffic 1/2 GBR.  PTT is 69/0.5.  it will depend on radio support?

try with different QCI for the 2 bearers and check again.

**Comment by aseaudi** [comment]
Yes, I am using QCI 9 for internet and QCI 5 for ims.

After you got the ip addresses, did the UE register for VoLTE, do you see the VoLTE icon on the top status bar on the mobile screen ?

**Comment by Radula76** [comment]
it tried to register for VoLTE but failed due to networking issue in our lab. the icon does pop up.

**Comment by javieraubert** [comment]
Hi @aseaudi are you using NAT or NON-NAT?

**Comment by javieraubert** [comment]
I'm trying to do the same experiment, but this is only going to work on Non NAT AGW, as the UE is the one who starts the SIP register and the pcscf needs to know the real IP of the UE to establish the identity, so far my UE get IP from the IMS network, it start the registration to the IMS, the UE receive the message of Challenge UE and start the ESP communication, but I'm failing here.

**Comment by aseaudi** [comment]
> it tried to register for VoLTE but failed due to networking issue in our lab. the icon does pop up.

Hi @Radula76, could you tell me which commit you are using for magma agw ?

**Comment by aseaudi** [comment]
> I'm trying to do the same experiment, but this is only going to work on Non NAT AGW, as the UE is the one who starts the SIP register and the pcscf needs to know the real IP of the UE to establish the identity, so far my UE get IP from the IMS network, it start the registration to the IMS, the UE receive the message of Challenge UE and start the ESP communication, but I'm failing here.

Hi @ javieraubert, could you tell me which commit you are using for magma agw ?

**Comment by Radula76** [comment]
we are using base 1.8, but modifications from RADTONICS, most of these patches are available in the latest master branch 1.9,  enabling the S21 to connect to the network easier.

**Comment by javieraubert** [comment]
I'm using 1.8

**Comment by aseaudi** [comment]
Thanks for the feedback, 

after some modifications, I was able to run a VoLTE call between 2 COTS UE Samsung S21 Ultra and Samsung A23.

The demo video is on youtube: https://youtu.be/lupEK5LdG3o

**Comment by panyogesh** [comment]
Closing the ticket as its not active any more.

**Comment by fbiyohne** [comment]
Hi @aseaudi, please can discuss with you for a private project advise please?
