### ISSUE TITLE
Proposal: voting by plurality within a time window

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#15375]
# Problem

Some of the matters that call for TSC votes are time-sensitive, but TSC voters may be too busy to vote. In such cases the community bogs down and business items get behind.

# Solution

1. TSC votes are by a plurality within a fixed time window.
  a. There is a two week window from the time a vote is called
  b. If a vote has been concluded but no action has been taken, there is a one-week window for late voters to weigh in. 
  c. Quorum is two voters
  d. If the time window expires without a quorum or plurality, the time window will stretch until there is a quorum or plurality
2. Every vote should have a Github issue. It might be a dedicated issue only for the vote, or some other. The issue should have the text "vote" somewhere (for findability). Any community member can record the issue.
3. Votes may be by email, Slack, voice vote in the TSC call, or within the Github issue. 

# Implementation

Modify Governance at https://github.com/magma/community/blob/main/Governance.md

# Non-goals

Amending the structure of the TSC apart from this

**Comment by jordanvrtanoski** [comment]
My comments:
1) We all agreed on the beginning of last year that we will have prompt voting boxed in a time-window, so I agree, boxed time window should be mandatory. The quorum to pass a vote should not be lowered to two voters since this is quorum to put thing is motion. The quorum should be set to 3 (one more from the vote needed to put thing in motion) and the vote is passed by "simple majority" of the voters who voted (example, if 5 voted, we need 3 votes to pass).
2) Agreed, this will allow us to keep the history of the conversation as well.
3) Let the vote be only in GitHub, this way it will be easy to know who voted. If the vote is taken on the TSC call, we will transcribe the votes in GitHub.

**Comment by lucasgonze** [comment]
I agree with your point on setting quorum to 3.

I am good with the Github issue for recording votes.

**Comment by lucasgonze** [comment]
Som, Jim, Yogesh are +1 on consensus.

**Comment by lucasgonze** [comment]
In the event of a tie, the measure should fail.

**Comment by lucasgonze** [comment]
Motion: Lucas
Second: Jordan
+1: Yogesh and Raphael

The motion is carried.

**Comment by lucasgonze** [comment]
Action item: modify the governance documents.

**Comment by lucasgonze** [comment]
Implementation of this ticket will be through https://github.com/magma/magma/issues/15390

**Comment by lucasgonze** [comment]
https://docs.google.com/document/d/1MD7-JTxxXlkvrjr6SAnIjrJ5SkA68n79Zd9etnPey84/edit?usp=sharing

**Comment by lucasgonze** [comment]
Accepted
