### ISSUE TITLE
[WIP] New TSC structure

### ISSUE THREAD

**Issue by lucasgonze** [magma/magma#15376]
### Problem

The [Magma Governance charter](https://github.com/magma/community/blob/main/Governance.md) calls for 

> The Committers of the project will elect 5 of their members to serve as a Technical Steering Committee (TSC) for the project. 

### Solution

The core elements of the solution, presented concisely, targeting an audience with high-breadth but low-depth understanding of Magma

### Non-goals

Anything specifically excluded from the concept

**Comment by lucasgonze** [comment]
Proposed timeout on membership.

**Comment by jordanvrtanoski** [comment]
We need to define the participation in a vote properly. Not participating in a vote as a form of statement (ex. the member is so agains something so he dosn't want to vote in order not to contribute to that motion at all) is a valid way to express disagreement. This form of not participating should not lead you to disqualification from TSC, therefore maybe we should consider if there was activity not only formal vote. Also, we need to make sure we give enough time for the TSC member to be active on the vote, so just saying  not participating in three votes without adding a perspective of a timeline can lead to automatic disqualifications. Ex: we call for 3 votes in a single day and all 3 are voted (pass of fail), the people who had not voted are on this issues will be automatically subject of the rule of not participating in 3 votes since there is no time frame.

**Comment by Som-BARNS** [comment]
1. How long can the seat be vacant?
2.  If a TSC member is on timeout - can (s)he be reinstated?
3. What happens to the quorum rules when a TSC membership is cancelled and there are less than 5 members?

**Comment by lucasgonze** [comment]
Proposal: add abstention to vote options. 
- Abstention preserves TSC seat. 
- Abstention doesn't count in quorum.

**Comment by lucasgonze** [comment]
If there is consensus on above points with no additional changes, the next step is a draft of the new charter incorporating the above items. Do we have a volunteer to do that writing?

**Comment by lucasgonze** [comment]
We may not always have 5 active contributors interested in serving. In that case we should be able to function with fewer. Is there a sensible way to have a flexible quorum of 3-5 members?

**Comment by lucasgonze** [comment]
Relevant documents:
* https://github.com/magma/magma/blob/master/CONTRIBUTING.md has the detailed rules for TSC operations
* https://github.com/magma/community/blob/main/Governance.md is fairly vague and unspecific

**Comment by lucasgonze** [comment]
# Proposal: Governance Reset

## Problem

Magma governance is mainly obsolete cruft. It was originally structured to fit a Meta-centric orientation. In the shift to independence and a proper open source community the governance has not kept up.

## Solution

Revisit every aspect of governance:

- Rewrite charter
- Rewrite all github.com/magma/community documents
- Proposed new structure for the TSC, including quorum changes
- Ensure compliance with legal constraints
- Shepheard votes by current TSC to put changes into practice

## Non-goals

Changes to the formal non-profit

## Funding

I am asking for $4,000 to implement the changes described above.
