### ISSUE TITLE
ORCR8 Metrics

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#215]
Is prometheus missing from the docker setup in orcr8 as documented here?

> https://facebookincubator.github.io/magma/docs/orc8r/docker_setup

Is the metrics designed to be part of the controller container services or a separate container altogether?

Looking at getting the NMS UI pulling metrics pushed from the gateway in a test/prod environment assumming a docker-based deployment.

**Comment by xjtian** [comment]
Prometheus should be in a separate container, but we are divesting from prometheus metrics at the moment due to some issues we've had running it in prod. We've decided on https://graphiteapp.org/, and are just about ready to roll out support for the end-to-end pipeline here.

@Scott8440 @rckclmbr r.e. metric collection in the docker setup

**Comment by bmurithi** [comment]
Noted! I'll close this.
