### ISSUE TITLE
[mme] MME allocating same m-TMSI to multiple UEs

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#2434]
### Your Environment

- **Version:** Master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** TeraVM

### Describe the Issue

MME’s subscriber handling seems to have a leak in regard to pTMSI reallocation:

There are situations where MME assigns the same pTMSI to multiple UEs during the same time (!) which leads to unpredictable behavior.

The following example may illustrate this. 2 UEs (IMSIs = ..115 and ..131) performing the same steps, watch the pTMSI reallocation:
1/           131:       09:04:09,920457              Attach-Accept                   pTMSI=0x00.1e.c8.00
2/           115:       09:04:42,570187              Attach-Accept                   pTMSI=0x00.1e.c8.00
3/           131:       09:04:42,860662              Attach-Request                 pTMSI=0x00.1e.c8.00
4/           115:       09:04:42,871083,             UEContextReleaseCmd
5/           131:       09:04:44,528459              Attach-Accept                   pTMSI=0x00.1e.a0.00

At 2/ MME assigns the same pTMSI to UE=115 that was already assigned to UE=131 at 1/ but UE=131 still sticks to this pTMSI and performs another Attach at 3/.

Now MME stumbles over its own mistake: It takes UE=131 for UE=115 and cleans up previous resources (S1-Context) assigned to UE=115 (!) at 4/.

Between 3/ and 5/ UE=131 (disguised as UE=115) does more damage and UE=115 paying the price – and  vice versa.

Attached filtered call-flow for both UEs 115 and 131 plus the full S1 trace for all 32 UEs running TC04.

[pcaps.zip](https://github.com/magma/magma/files/5106978/pcaps.zip)

**Comment by rsarwad** [comment]
Scenario-1: Referring to pcap, gx04_f_115.pcap, in frame number 10, m-tmsi (0x001ec800) is allocated in Attach Accept for which enb_s1ap_id is 1039 and mme_ue_s1ap_id is 1014. For this UE, neither the Attach Request nor the Identity Response messages are captured in this pcap, so not getting IMSI for the UE.

In frame number 15,  MME sends UE Context Release Command whose enb_s1ap_id is 1039. Since MME didn't receive Attach Complete, MME releases the UE contexts.

In frame number 34, new Attach Request is received for which m-tmsi (0x001ec800) is allocated in Attach Accept in frame number 43. As part of new attach procedure, new mme_ue_s1ap_id is allocated, i.e 1077

Conclusion: So same m-tmsi is not allocated at same time for two different UEs.
Scenario-2: 
Referring to same pcap file and frame number 47, new Attach Request is received with GUTI that was allocated previously whose mme_ue_s1ap_id is 1077. Since the UE with mme_ue_s1ap_id, 1077 is stiil in EMM_Registered state. Suspecting that MME may trigger Implicit detach for the previously allocated UE(1077). Due to which MME is sending Ue Context Release Command to eNB in frame number 50.
For this scenario, debug logs would be more helpful.

Query 1: Even though Attach Request received in frame number 47 has same GUTI as previously allocated UE whose mme_ue_s1ap_id is 1077. But IMSI received in Identity Response are not same. How is IMSI differing for UEs with mme_ue_s1ap_ids  as 1077 and 1105

**Comment by rsarwad** [comment]
Referring to pcap, gx04_f.pcap; filtered for m_tmsi set to 0x001ec800. 
For mme_ue_s1ap_id 1014, m-tsmi is allocated in Attach Accept message and as part of detach procedure, UE contexts are deleted.
In frame number 459, Attach Request is received with GUTI previously allocated, different GUTI is sent in Attach Accept. 
In frame number 812, m-tmsi 0x001ec800 is allocated as it was freed. Later this is also freed as part of detach procedure
Once again Attach Request is received for which same GUTI is allocated in Attach Accept in frame number 1098 but there is no Detach Request received for this UE, whose mme_ue_s1ap_id is 1077. On reception new Attach Request with same GUTI for previously registered UE. MME performs Implicit detach for previous UE contexts, so MME sends UE Contexts Release Request and assigns new GUTI. 
Conclusion: So same m-tmsi is not allocated at same time for two different UEs.

**Comment by pedroamfarias-cpqd** [comment]
Hi! I started the testes with Magma and found same issue here. The issue is easilly reproduced with a second UE attach, when UE uses GUTI instead of IMSI. Using UE simulator with 64 UEs, when UE 32 start the initial attach with previously TMSI (that was attributed to UE 31 in previously attach) the EPC send NAS-Detach to UE 31 and UE 32 receives new TMSI. and in sequence the UE 33 trigger the NAS-detach of UE 30 and so on. 
![image](https://user-images.githubusercontent.com/74007352/98255791-9019e300-1f5c-11eb-8223-852d25bb8062.png)

**Comment by uri200** [comment]
Hi @pedroamfarias-cpqd  that is awesome! thanks for finding this.

So just to understand you test, you attach UE 1 to 31, then detach UE 31 and attach ue 32.  You see that UE 31 and 32 have the same TMSI. Is that correct?  See we currently provide the TMSI based on the memory address the UE context have on MME. So I am trying to understand when that context is released and memory becomes free again.

Unfortunately GitHub must have reduced your picture to a small size so I can see it properly

**Comment by pedroamfarias-cpqd** [comment]
Hi @uri200 ! 
In case I keep the UE 31 online and the UE 32, at initial attach, send same TMSI that UE 31 received (and UE 32 received this same TMSI at first attach). I'm uploading again the image (now is good?) and sending pcap file.
There is another step that this issue happens too. I will reproduce again, save the logs and asap I will share here. 
I'm tested you solution also. I will post the result in #3563 ok?

Scenario: Amarisot UE Simulator + Tropico eNB 250Mhz + Magma EPC 1.3.0 (bare metal install but installed at VM...)

The steps of test:

1. Connects the 64 UEs in sequence.
    1. At this point, the UEs use the IMSI as initial attach instead of GUTI
1. Disconnects the 64 UEs in sequence (Detach - Switch off)
1. Connects the 64 UEs again
    1. At this point, each UE will use GUTI with previously TMSI at initial attach
        1. UE 31 received TMSI 0x0008ac00
        1. UE 32 initiated the initial attach with same TMSI 0x0008ac00
            1. When UE 32 send the initial Attach, the EPC send NAS-detach to UE 31
        1. Start to happen with all UEs from now until 64


[s1ap_magma_1.3.zip](https://github.com/magma/magma/files/5501517/s1ap_magma_1.3.zip)



![image](https://user-images.githubusercontent.com/74007352/98371510-0c72fb80-201b-11eb-9766-bf801e27f9c5.png)

**Comment by uri200** [comment]
@pedroamfarias-cpqd Thanks again for raising your concern, all the logs you provided, and a simple way to reproduce the issue! 🙏

Several members of the Access Gateway have been discussing this issue during the last two days and we have concluded the following:  

It looks like the reuse of TMIS causes some cnfusion but they never overlap. If you check the picture below, you will see that the UEs try to reuse the old timsi. However, AGW does not allow its usage and assigns that UE new IMSI. So eventually both UEs ends up with a TIMSI that is not being currently used. 

*However*, since reuse of TMSI has no benefit and it causes confusion and potential trouble at eNb, we are going to go ahead with this PR and use random assingment. With this system the TMSI will not be reused after `INT_MAX` (2147483647) attaches.



![image](https://user-images.githubusercontent.com/16157139/98425772-3f34e800-204b-11eb-9412-707b07ce3c89.png)
