### ISSUE TITLE
[CI/CD] Prepare deployment manifests for Magma Orc8r with NMS using standard Magma Orc8r helm chart on top of Kubernetes.

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#2616]
Prepare deployment manifests for Magma Orc8r with NMS using standard Magma Orc8r helm chart on top of Kubernetes.

For the larger context for the issue see [Roadmap](https://docs.google.com/document/d/1cu4XGxfW7e0n84Fm82-Se_0DuKmTb2_3Qvk0vg6jVUs).

**Comment by mattymo** [comment]
I have started work on un-Terraforming the deployment of Orc8r. The work is going to be broken down into the following steps:
1 - generate certificates
2 - generate Helm values file with the following required values:
  - Docker repo
  - magma version
  - external DNS hostnames
  - storage class
3 - install dependent charts
  - elasticsearch
  - elasticsearch-curator
  - fluentd
  - kibana
  - MariaDB (since PostgreSQL doesn't work currently)
4 - Precreate persistentVolumeClaims for orc8r since it cannot create its own currently (https://github.com/magma/magma/issues/2894 will solve this later)
5 - deploy all orc8r helm chart
6 - set up admin user
