### ISSUE TITLE
Automate provisioning of access gateway on bare metal

### ISSUE THREAD

**Issue by ghost** [magma/magma#288]
Please provide an ansible script producing an Ubuntu artifact targeting Ubuntu 18.04 LTS and kernel v 4.15.
Related to #193 
@amarpad

**Comment by ghost** [comment]
@amarpad, I just spoke to @sarathbrp and he had to modify an OVS source file to get OVS to compile on Debian bare metal host in Packet. The issue *may* belong to this ticket as well. @sarathbrp will provide more detail either here or in slack.

**Comment by tmdzk** [comment]
Hey @mzelenov-federatedwireless, hope you're doing great, thanks for raising this issue a couple a months back.
[The Access Gateway automation v1](https://facebookincubator.github.io/magma/docs/lte/setup_deb) has been out for a few weeks now so I'll close this. 
A quick note: the Access Gateway can't run on Ubuntu for now. It only runs on Debian 9 Strect (kvers 4.9.0-9-amd64) due to custom ovs patches we created. 

Please if you have any struggle using the automation, fell free to raise an issue and ping me.
