### ISSUE TITLE
[AGW] Fix UE context clearing on S1 link down

### ISSUE THREAD

**Issue by pshelar** [magma/magma#3178]
### Your Environment

- **Version:** master
- **Affected Component:** AGW
- **Affected Subcomponent:** MME/SPGW
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

UE IP address not release on S1 link down.

**To Reproduce**
I got Steps to reproduce from VNL:
1. UE Attached
2. S1 Interface Down, by EnodeB Lock operation.
3. At AGW, Observation from CLI (`mobility_cli.py list_allocated_ips`), IP was not deallocated. It was assigned to UE.

**Expected behavior**
UE IP address shld be released.

**Additional context**

[ipInfo.txt](https://github.com/magma/magma/files/5363243/ipInfo.txt)
[mme.log](https://github.com/magma/magma/files/5363244/mme.log)

**Comment by pshelar** [comment]
After s1 link up,  Tracking area rejected with EMM cause "Information element non-existent". We also need to investigate it.

[mme_s1_link_up.log](https://github.com/magma/magma/files/5366883/mme_s1_link_up.log)

**Comment by ssanadhya** [comment]
@pshelar Looking at the MME logs in mme_s1_link_up.log, the first Tracking Area Update Request was rejected for UE ID =0x00002d with cause 99 as the UE initially attached with EPS attach type and now is sending a TAU with combined TA/LA update type, indirectly requesting for non-EPS services which are not enabled in this deployment.

The second TAU reject for UE ID = 0x000035 is because a UE which is not registered, sent a TAU with GUTI. This is most likely because the UE did not realize that MME went down due to the S1 link failure and held on to the GUTI from previous registration, before the MME restarted. Once that TAU was rejected, I see an immediate Attach Request (most likely the same UE), which is successful.

**Comment by ssanadhya** [comment]
@pshelar , for the original issue where UE context is not released, the logs in "mme.log" how that the S1-U bearer count has gone down to 0 after the UE context release complete happened. As seen in "ipInfo.txt" Mobilityd does not release the IP address for this UE as the UE is still registered, only radio bearers and S1-U bearers are released. This is expected behavior.

**Comment by ulaskozat** [comment]
Can we close on this issue?
