### ISSUE TITLE
Default IP block in NMS NAT config is a /32 - DHCP to UE fails

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#324]
UEs will fail to attach on IP allocation errors.

The IP block on NMS is only editable when the NAT flag is disabled, then re-enabled, then saved to take effect and propagate to the gateway.

The default should be something reasonable and editable.

**Comment by xjtian** [comment]
I think if NAT is disabled, the IP block param should be ignored. Let me see what's going on here. The default should probably be a /24 anyways

**Comment by xjtian** [comment]
The default IP block is a /24 for me on NMS - is this not the case for you? We limit the IP block editing when NAT is enabled because technically you shouldn't care about the block that gateway IPs are allocated within when running as a NAT.

![Screen Shot 2019-08-26 at 3 43 38 PM](https://user-images.githubusercontent.com/3249794/63729158-39266300-c81b-11e9-889a-339ac60d2b6f.png)

**Comment by bmurithi** [comment]
@xjtian this will be true for installs that have already been configured.

The UX issue is when adding a new gateway - by default NAT is disabled and when enabled, the default IP Block will be rejected by Magma - and is a /32

![Selection_156](https://user-images.githubusercontent.com/6918709/63761059-266a6780-c8c9-11e9-826b-433a75d2d77b.png)

**Comment by xjtian** [comment]
Fixed on master - keep an eye out for a v1.0.0-beta release tag early next week which will include this fix.
