### ISSUE TITLE
[XWF-M] Orc8r errors observed when pushing more than 500000 metrics

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#3298]
orchestrator stderr | E1015 08:14:39.041450      35 exporter_servicer.go:105] error pushing to pushgateway: [non-200 response code from pushgateway http://orc8r-prometheus-cache:9091/metrics: Not accepting push of size 952. Would overfill hub limit of 500000. Current hub size: 499981
orchestrator stderr | ]
orchestrator stderr | E1015 08:15:09.039261      35 exporter_servicer.go:105] error pushing to pushgateway: [non-200 response code from pushgateway http://orc8r-prometheus-cache:9091/metrics: Not accepting push of size 476. Would overfill hub limit of 500000. Current hub size: 499981
orchestrator stderr | ]
orchestrator stderr | E1015 08:15:39.048490      35 exporter_servicer.go:105] error pushing to pushgateway: [non-200 response code from pushgateway http://orc8r-prometheus-cache:9091/metrics: Not accepting push of size 952. Would overfill hub limit of 500000. Current hub size: 499981
orchestrator stderr | ]
orchestrator stderr | E1015 08:16:09.039359      35 exporter_servicer.go:105] error pushing to pushgateway: [non-200 response code from pushgateway http://orc8r-prometheus-cache:9091/metrics: Not accepting push of size 476. Would overfill hub limit of 500000. Current hub size: 499981
orchestrator stderr | ]

**Comment by Scott8440** [comment]
In the `prometheusCache` values section there's a `limit` value which I believe is defaulted to 500000. If you set that to -1 it will be unlimited, otherwise you can set it to a higher value. 

The purpose of this value is to prevent the prometheusCache from just filling up forever and OOMing if the prometheus scrape isn't working. These pushes look kinda small so I'm not sure if there are just a ton of pushes that are overfilling the cache before it gets scraped, or if the scrapes are failing for some reason causing the cache to never get emptied eventually leading to this situation

**Comment by karthiksubraveti** [comment]
@ymasmoudi can we close this issue, if @Scott8440 suggestion worked for you ?

**Comment by ymasmoudi** [comment]
@karthiksubraveti yes let's close it for now. thanks
