### ISSUE TITLE
Redirection not working in teravm

### ISSUE THREAD

**Issue by uri200** [magma/magma#3401]

**Comment by koolzz** [comment]
![image](https://user-images.githubusercontent.com/11281728/98434630-9e0f5700-2075-11eb-9b35-fff1a66b2300.png) Eh this took me way longer than it should have as I was looking for routing issues but the real issue is this PSH ACK pkt from client, this doesn't look like norma HTTP GET request to me(its just some garbage text rn). This is most likely why the server responds with HTTP 400 bad request, please adjust the test to either send an ACK and then HTTP get or set pshack data better.
@uri200

**Comment by uri200** [comment]
The redirection happens through the http header. The UE is in fact the one responsible to fwd the packets to the new IP. This issue has been resolved on the test level
