### ISSUE TITLE
[Inbound Roaming][test] TeraVM testbed setup

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#3746]
As discussed under Testing Plan in https://docs.google.com/document/d/1zJZpt5dCBjy54ODQ5DzbJZ2HufJgLxAIoVPyZPZL5UY/edit#heading=h.whixyckhvwrl, we need a TeraVM setup which emulates both MNOH (Home) and MNOV (Visiting) network.

**Comment by uri200** [comment]
License for a new PGW has been set up on Teravm

The set up has been tested only for s6a + neutral host. Now we are able to authetnicate through two different HSS

Basic test on PGW has been done with S8_proxy and we confirm that Create and Delete session worked.

No test has been done with MME s8_task + s8_proxy because mme is not ready yet

For now this task can be considered done. We will open new taks in case we need to do changes on Teravm architecture to support testing

**Comment by uri200** [comment]
closed

**Comment by uri200** [comment]
(Reopening this issue to capture the changes on teravm architecture)

Teravm right now has a separated scenario for inbound roaming case and for regular magma case. We want o have just one single scenario were we can test any case. 

We are also including 3 test cases for inbound roaming that can be seen on this document

https://docs.google.com/document/d/11m6VF4Grg0yPjjhoXdxJ-kVhvxrbW6Lk0iIue3d-814/edit#heading=h.czv0vpn4mw66
