### ISSUE TITLE
[CI][Jenkins]Log files addition.

### ISSUE THREAD

**Issue by Vyas20** [magma/magma#3882]
Describe the Issue
Test run returns incomplete log files and no wireshark traces.

Expected behavior
Magma logs after CI runs should consist of Log files with status of all the services running on magma-dev VM, magma-run status, Detailed logs from  S1AP tester (for both agw_of and s11 variant), logs from trf server for traffic tests and Wireshark traces from S1AP-Tester VM (For both agw_of and s11 variant). 

Additional context
Zip file titled 2nd December consists of all the logs which are required but are missing from the present CI run.

[2nd Decemeber.zip](https://github.com/magma/magma/files/5636759/2nd.Decemeber.zip)

**Comment by mattymo** [comment]
@Vyas20 We discussed this during the Magma Engineering weekly meeting yesterday. Of those present, nobody raised any interest in seeing these logs separate from the Jenkins job logs. No data has been lost because it's all in the Jenkins job output still.

In the interests of this HTML report, I will restore integration test logs to this report, but logs relating to vagrant destroy, apt-get update, apt-get install, etc do not need to be stored in separate files.

If you want to know the output of magma service status, please just read the Jenkins job log. It's all there.
