### ISSUE TITLE
Add metric for UE's connected per ENB

### ISSUE THREAD

**Issue by mpgermano** [magma/magma#4044]
For FWA HA we need to know when an ENB has users connected to it. Currently we are using ENB throughput to determine this. This is an issue as throughput can be 0 when all users are in IDLE state. To better determine this we want to a metric for each user connected to each ENB.

**Comment by karthiksubraveti** [comment]
@mpgermano I'm curious to know more about this usecase. I'm also interested in knowing the number of users behind a eNodeB(for phone home usecase), but wondering if metrics is the right way to identify this ? @ardzoht How will the gateway make the determination on this parameter ? Will MME have this state ?

**Comment by ardzoht** [comment]
@karthiksubraveti We decided this makes more sense if this is included as the reported state of the eNB, instead of a metric. In this case, the owner for the state is MME as it contains the state of each eNB and the amount of UEs connected to each, and enodebd will be reporting the state to Orchestrator, expanding on the same process we were using to report states for unmanaged eNodebs

**Comment by karthiksubraveti** [comment]
@ardzoht  can you subscribe me on this PR. Is this landing in this sprint ?
