### ISSUE TITLE
[CI] CI pipeline with DSTester

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#4075]
Dockerized pipeline with Magma MME + OAI HSS + OAI CUPS SPGW

- Test NSA
- Test 4G

**Comment by rdefosse** [comment]
The idea is to follow the same pattern as the `https://jenkins.magmacore.org/job/magma_integration_tests/` job.

We will build an image using a base image containing all means to re-build `mme` and `sctpd` executables. That process only takes 1 minute compared to 25+ to build an image from scratch.

Once we have the image, we will deploy an EPC w/ docker-compose with parameters compatible w/ our current DsTester testsuite

The framework is already adapted to run w/ MAGMA-MME container instead of OAI-MME container

Then upon success, we will trigger a child pipeline that will deploy a eNB container image with SDR and a real UE to attach and do traffic test.

**Comment by ssanadhya** [comment]
@rdefosse , could you please comment what is pending here? Are there any open PRs to be reviewed/merged?

**Comment by rdefosse** [comment]
@ssanadhya 

**What has been done:**

- Image builder job: `https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/`
   * Triggered on any new commit on any pull request
       - Pipeline analyzed list of modified files and decide to run full pipeline or bypass
   * Triggered every French Morning (8:30AM CET) and build on the latest version of `master` branch
- Integration Test job: `https://jenkins-oai.eurecom.fr/job/MAGMA-MME-OAI-DsTester/`
   * Triggered when the builder job is successful
   * Deploy an EPC w/ MAGMA-MME and OAI-** containers
   * Test w/ DsTester framework w/ 4G and 5G-NSA scenarios

**What is still missing:**

- A secondary integration test job:
  * Deploy not only a EPC but also OAI RAN components and attach commercial UE and do traffic test
  * No associated PR yet
- In the builder job, we want to add a `RHEL8` component
  * Initial PR: `https://github.com/magma/magma/pull/5438`
  * Build RHEL8 image in parallel of the Ubuntu18 image
  * Push to our OpenShift cluster and test it there
  * That will require one or two additional PR(s) to modify the pipeline
