### ISSUE TITLE
Fix initflags breaking Go test runner output

### ISSUE THREAD

**Issue by hcgatewood** [magma/magma#4444]
The initflag.go file is being implicitly imported throughout the gateway+cloud codebase, meaning its init() function is being run in basically every executable. This introduces some unhappy side effects, mainly: it breaks test tool output.

![Screen Shot 2021-01-19 at 10.06.29 PM.png](https://images.zenhubusercontent.com/5f849d6a14e26c440377c914/1a6d589e-e63f-4364-8b37-1a15c975d8b0)

We have added a workaround for this, but it's brittle and ready to cause a hidden bug in production as the hack keeps growing. Instead, we need to remove initflag.go's automatic flag parsing.

This will have the temporary side effect of causing certain glog logs to contain the "flags not parsed" annotation, but that will only occur where (a) logging occurs in an init function (which we shouldn't be doing anyway) or (b) the source executable didn't flag.Parse (which it should).

**Comment by emakeev** [comment]
Are there any concrete examples of failures? I run the tests specified by the issue above on current master & all seems to work fine.![Screen Shot 2021-01-20 at 11.47.39 AM.png](https://images.zenhubusercontent.com/6008867997c63c0e462f476c/7ed23b16-bd34-4676-98fe-a310924986c0)

![Screen Shot 2021-01-20 at 11.45.12 AM.png](https://images.zenhubusercontent.com/6008867997c63c0e462f476c/2c699c5a-3e6a-4fdf-ae6a-9970b9b9344a)

**Comment by hcgatewood** [comment]
It seems Oriol's latest initflag PR has resolved the issue for now. But it's also increased the degree of hackiness -- we're now checking executable name as well as all args for magic values.

In that light, I still favor removing the auto flag parsing. Thoughts?

**Comment by emakeev** [comment]
Unfortunately completely disabling initflag will not only introduce some initial error messages from glog, but will also break stdout redirection and Magma's syslog support.

Since we currently do not have any ongoing issues with the feature, I added an option to disable it completely on debug & test IDE builds if needed: https://github.com/magma/magma/pull/4644 
If required, IDE settings can be updated with the tag to disable initflag's parsing permanently on all project's tests & debugging builds.
