### ISSUE TITLE
[docs] Provide details on how to install older stable versions of FEG

### ISSUE THREAD

**Issue by karthiksubraveti** [magma/magma#4689]
Current docs only provide information on how to install latest FEG. Provide a section on installing older stable version and also fix scripts if necessary to enable this. 

https://magmacore.slack.com/archives/C0191LLL03S/p1612188096032700

**Comment by uri200** [comment]
Per the comments the user left on our channel the issue was more related on how to switch between versions of Magma than building Feg

Since FEG uses docker, the only prerequisite is to have docker and run the `docker-compose` command, which was already on the guide. What we were missing is some kind indication on how to get magma (from github) and how to switch between releases. 

The attached PR should add some clarity.
