### ISSUE TITLE
[lte][agw] Add GRPC tracing support on AGW

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#4826]

**Comment by uri200** [comment]
The initial idea is to have at least grpc messages (and its content) visible on the syslog. This feature has proven very useful when debugging sessiond.

Since GRPC messages can be long and frequent the visibility should be controlled independently from the log level. Also we should use lazy logging to avoid parsing GRPC message in case the function is disabled.

Sessiond and Pipelined already have a feature to display GRPC messages on the log `MAGMA_PRINT_GRPC_PAYLOAD=1`. The idea is to do the same with as many services as we can on AGW. 

Mobilityd and Directoryd are the two first candidates since those two services do not provide much verbosity on their logs.

Log messages will look something like
```
Feb 09 16:49:36 agw sessiond[14208]: I0209 16:49:36.026278 14278 GrpcMagmaUtils.cpp:38]
Feb 09 16:49:36 agw sessiond[14208]:   magma.lte.UpdateTunnelIdsRequest {
Feb 09 16:49:36 agw sessiond[14208]:       sid {
Feb 09 16:49:36 agw sessiond[14208]:         id: "IMSI999991234567810"
Feb 09 16:49:36 agw sessiond[14208]:       }
Feb 09 16:49:36 agw sessiond[14208]:       bearer_id: 5
Feb 09 16:49:36 agw sessiond[14208]:       enb_teid: 33554432
Feb 09 16:49:36 agw sessiond[14208]:       agw_teid: 2
Feb 09 16:49:36 agw sessiond[14208]:   }
```
