### ISSUE TITLE
install_gateway.sh can not install specific versions

### ISSUE THREAD

**Issue by uri200** [magma/magma#4950]
When we try to use `install_gateway.sh` with feg on a specific release (for example `v1.3`), the script fails.

It seems the issue is `magma/feg/gateway/docker/.env' needs the tag `latest` to build whatever is checked out locally, but instead it uses v1.3

Note the idea is to build v1.3 locally.

```
if [[ $IMAGE_VERSION == *"|"* ]]; then
  GIT_HASH=$(cut -d'|' -f2 <<< "$IMAGE_VERSION")
  IMAGE_VERSION=$(cut -d'|' -f1 <<< "$IMAGE_VERSION")
fi
if [ "$IMAGE_VERSION" != "latest" ]; then
    git -C $INSTALL_DIR/magma checkout "$GIT_HASH"
fi
```

from 
https://magmacore.slack.com/archives/C0191LLL03S/p1613179334123000?thread_ts=1612188096.032700&cid=C0191LLL03S

**Comment by MGAbdElKhalek** [comment]
We can use the same version for for code checkout and the docker images. For example "v1.3" in this case we need only to change the code so that it doesn't checkout the default master as in GIT_HASH. Also GIT_HASH will not be used and the | separator format also. 
For example:

```
if [ "$IMAGE_VERSION" == "latest" ]; then
    git -C $INSTALL_DIR/magma checkout master
else
    git -C $INSTALL_DIR/magma checkout "$IMAGE_VERSION"
fi
```

For more flexibility we can use the | separator but we will need to rewrite the .env after parsing so the docker-compose can understand the image tag. Accordingly the installation script will be changed also

```
if [[ $IMAGE_VERSION == *"|"* ]]; then
  GIT_HASH=$(cut -d'|' -f2 <<< "$IMAGE_VERSION")
  git -C $INSTALL_DIR/magma checkout "$GIT_HASH"
  sed "s/"$IMAGE_VERSION"/$(cut -d'|' -f1 <<< "$IMAGE_VERSION")/g" .env > .docer_env
fi
...
...
...
...
cp .docer_env /var/opt/magma/docker/.env
rm .docer_env
```

This is a quick script. I can do  pull request with any of the 2 solutions after testing

**Comment by uri200** [comment]
Hey @MGAbdElKhalek, since this is only for install, let's put all the logic on the install script. Also we need to use `latest` on our .env file to be used during development and in CI.
So what you mentioned on checking out the version seems good to do the job here.

**Comment by ranj8work** [comment]
Hi @uri200 

I am not sure if this issue is fixed but I think in the file _**orc8r/tools/docker/install_gateway.sh**_ below lines should help to install specific versions (ex: IMAGE_VERSION=1.3.2|6240e4c838495b41695428e5535ba16e231f6627). 
If IMAGE_VERSION=latest it will build from master else it will build from the desired hash commit tied to the specific version.

if [[ $IMAGE_VERSION == *"|"* ]]; then  ## 1.3.2|6240e4c838495b41695428e5535ba16e231f6627
  GIT_HASH=$(cut -d'|' -f2 <<< "$IMAGE_VERSION")
  IMAGE_VERSION=$(cut -d'|' -f1 <<< "$IMAGE_VERSION")
fi

if [ "$IMAGE_VERSION" == "latest" ]; then
    git -C $INSTALL_DIR/magma checkout master
else
    git -C $INSTALL_DIR/magma checkout "$GIT_HASH"
fi

If you are okay with these lines of code change, I will go ahead and make them and send a pull request.

**Comment by uri200** [comment]
Thanks
Can you test the changes running the script please?
https://docs.magmacore.org/docs/feg/deploy_install
Leave the .env file as it is. Docker should build locally the images with that .env file

**Comment by ranj8work** [comment]
Absolutely. I am working on it. Will keep you posted.
