### ISSUE TITLE
HOST [magma]$ cd lte/gateway HOST [magma/lte/gateway]$ fab register_vm

### ISSUE THREAD

**Issue by pcminitech** [magma/magma#50]
![gateway](https://user-images.githubusercontent.com/35584824/54080386-52167880-42bc-11e9-8821-7ec2c5571f9f.PNG)

**Comment by xjtian** [comment]
`fab register_vm` uses a cached client operator cert to authenticate with the cloud API. The 401 means that the cloud certifier service was unable to locate the serial number of this cached cert, potentially because it hasn't been registered with the cloud yet.

Assuming your cloud and datastore VMs are running, you can do this:

```
CLOUD-VM$ make -C ~/magma/orc8r/cloud restore_admin_operator
```

This will re-register the cached operator client cert with the certifier service. This can happen if for e.g. you nuke your datastore VM, or if it wasn't up the first time you did `make run` on cloud.

This should fix this fab command for you - if it doesn't, feel free to follow up on discord for more real-time help.
