### ISSUE TITLE
[CI] Benchmark Github action: Docker environment 

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#5071]

**Comment by tmdzk** [comment]
## Summary 

We have a couple of jobs that run inside a dockerized environment. 
The goal of that task is to simply benchmark if Github Action can do that. 

Example of a job to migrate: 
[cwag-precommit](https://github.com/magma/magma/blob/master/.circleci/config.yml#L645)
Runner spec: circleci/golang:1.13-buster-node-browsers-legacy (lightweight image with go)

## Ressources 
[Circle CI images ressource](https://circleci.com/docs/2.0/circleci-images/)

**Comment by jwagantall** [comment]
Working on this issue under: https://github.com/jwagantall/magma/actions

**Comment by jwagantall** [comment]
Currently, I have 3 jobs written in GHA which are the precommit, xwfm-test, and integration tests. 
These are written in separate workflows for now to get them tested but will connect them the same way Circle CI has them in their pipeline. 

My current issue is with the keys hosted in Circle CI's secrets. Looking into how we should host those so that GHA can use them. 

https://github.com/jwagantall/magma/actions

**Comment by jwagantall** [comment]
Updated the workflow to reflect job dependency. Latest run:
https://github.com/jwagantall/magma/actions/runs/655961113

**Comment by jwagantall** [comment]
Updated now the CWF workflow.. this one is passing: https://github.com/jwagantall/magma/actions/runs/659673786
