### ISSUE TITLE
[AGW] Vagrant Ubuntu 20.04 

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#5156]

**Comment by jeremy-donson** [comment]
I expect to run this comment by Ekow to ensure that it gets into the 1.5 epic properly.

We are to use single script for agw on both debian and ubuntu vms.
I am doing what I can to NOT change the scripts.

There is a list of issues I can raise towards improving quality regarding ubuntu20vm.
Example:  https://github.com/magma/magma/issues/5621

None of these issues block hitting deadline,
yet they ought to be listed and scheduled so that deadlines are hit AND quality goes up.

There are general questions about managing  stable, legacy, and emerging magma deps with fab over time.
There are specific questions about how to support two distros at once.

Defining dev environments needs to be more explicit.
Some discussions about local physical agw setups and testing would help.

Do we have a local dev install readme that only runs on vbox vms?
     (Otherwise, it is not local dev.)

There is a wrapper script I suggest we review for agw local dev on osx.
Some discussions about upgrade strategies would help.

Final Note:
For me, ubutu20VM + upgrades + private/public docs are foremost concerns.
