### ISSUE TITLE
[NMS] Not getting metrics on master domain for bare metal

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [magma/magma#5348]
Metrics not showing on NMS master page
Source: https://github.com/magma/magma/discussions/5322

**Comment by karthiksubraveti** [comment]
The problem lies here - 
https://github.com/magma/magma/blob/ff5adfaaabd3cfc997a753dd749b2403535483f8/nms/app/packages/magmalte/app/components/master/Index.js#L111

When magma was open sourced some of the libraries moved to fbc-js-core repo which is also open sourced
https://github.com/facebookincubator/fbc-js-core/blob/70c1f40079e4cf3f071e0958dbf593e5263aaea1/fbcnms-packages/fbcnms-ui/master/CloudMetrics.js

The CloudMetrics component is possibly referencing a metric which isn't valid. If you can triage this further it would be great. Let me know if you have any questions. Thanks.
