### ISSUE TITLE
[feg + sessiond] Add 5G NSA IEs in Credit Control Requests and Answers

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#5676]
Replicate the work in https://github.com/magma/magma/issues/5675 for a federated network

**Comment by ulaskozat** [comment]
@uri200 can you add what changed have you done on this front?

**Comment by uri200** [comment]
> @uri200 can you add what changed have you done on this front?

Hey @ulaskozat, I am sorry but I am not in the loop for any of those features. This issue has been assigned to me just today.

Is there any epic, design doc or list of issues where I can see if there is any other work to be done on FEG side?

**Comment by ulaskozat** [comment]
@uri200 This is part of the NSA epic. Sorry for the sudden drop of the issue; it is to make sure that you are in the loop as I noticed you were not. We may need your support on this as I am not sure if any changes are needed on CCR/CCA side. Do we support extended AMBR AVPs on Gx/Gy?

**Comment by uri200** [comment]
I thought this would be just addition of AVPs but I see different challenges here:

1- Go Diameter does not implement Extended-APN-AMBR or Extended-Max-Requested. So that needs to be added to that external repository.

2- It looks like Update Location Answer it includes, not only Feature list id 2 but also Extended-Requestd_Bandwith. That was not implemented in here https://github.com/magma/magma/pull/6234 . So it is missing on s6a
![image](https://user-images.githubusercontent.com/16157139/117901353-0555d000-b280-11eb-9270-6bb07f43fa09.png)
https://www.eventhelix.com/5G/non-standalone-access-en-dc/en-dc-secondary-node-addition-core-network-details.pdf

3- Credit control request may need Extended-APN-AMBR, Extended-GBR, Extended-Max_requested_BW (none of them are supported by Go Diameter
![image](https://user-images.githubusercontent.com/16157139/117900932-1e11b600-b27f-11eb-83d0-40c0cfb14301.png)
page 75 at https://www.etsi.org/deliver/etsi_ts/129200_129299/129212/15.09.00_60/ts_129212v150900p.pdf

**Comment by uri200** [comment]
Added this first PR to `go-diameter` to support those AVP
https://github.com/fiorix/go-diameter/pull/156

**Comment by uri200** [comment]
@Vyas20 @ulaskozat here https://github.com/magma/magma/pull/5749 there were a change on protocols were we added a field called `apn_ambr_bits_unit_t`. Does it mean that MME will not consume a structure like the one below, 

```
type AMBR struct {
	MaxRequestedBandwidthUL uint32 `avp:"Max-Requested-Bandwidth-UL"`
	MaxRequestedBandwidthDL uint32 `avp:"Max-Requested-Bandwidth-DL"`
	ExtendMaxRequestedBWUL uint32 `avp:"Extended-Max-Requested-BW-UL"`
	ExtendMaxRequestedBWDL uint32 `avp:"Extended-Max-Requested-BW-DL"`
}
```

But FEG will have to set `apn_ambr_bits_unit_t` to `KBPS` when it receives `Extended` AVPs?

**Comment by ulaskozat** [comment]
@uri200 yes, when the unit is set as KBPS we will convert to/from AMBR by utilizing Extended AVPs. Note that the other field in AVP also needs to be filled up to their maximum value of 4294967295 (on bps).

**Comment by uri200** [comment]
@ulaskozat, so to clarify, when mme sends something like this to feg :

```
message Ambr {
  	uint64 br_ul = 1000
  	uint64 br_dl = 2000
	br_unit = Kbps
}
```

We have to convert it into an avp like this
```
type AMBR struct {
	MaxRequestedBandwidthUL uint32 = MaxUint32
	MaxRequestedBandwidthDL uint32 = MaxUint32
	ExtendMaxRequestedBWUL uint32 = 1000
	ExtendMaxRequestedBWDL uint32 = 2000
}
```


Reverse operation will also apply the same logic



> When the IP-CAN session is being established, if the PCEF supports the Extended-BW-NR feature and for bandwidth values higher than 2^32-1 bps, AVPs representing bitrate in bps (i.e. APN-Aggregate-Max-Bitrate-UL/DL AVPs) shall be provided with value set to 2^32-1 bps and bandwidth AVPs representing bitrate in kbps (i.e. Extended-APN-AMBRUL/DL AVPs) shall be provided with the actual required bandwidth.

**Comment by ulaskozat** [comment]
@uri200 yes indeed.

**Comment by uri200** [comment]
@ulaskozat In the link below you can see AVPs supported so far in FEG on Gx. As you can see it looks like `Qos-Information` (1016) AVP has never been supported. That means APN qos is always been set up by HSS. PCRF has never been able to change the Qos because we are not implementing that.

So the question is, is Gx support for `Qos-Information` on this 5g  feature really needed? or are we good with s6a support for the definition of AMBR?


https://github.com/magma/magma/blob/master/feg/gateway/services/session_proxy/credit_control/gx/definitions.go#L169-L184

![image](https://user-images.githubusercontent.com/16157139/120417521-d4633b00-c313-11eb-8574-5cf277eaac7c.png)

**Comment by ulaskozat** [comment]
@uri200 I think we should be alright for now. For now extending subscriberdb, mme, sessiond and pipelined with the extended AMBR stuff would be sufficient.

**Comment by uri200** [comment]
adding this issue for Pipelined https://github.com/magma/magma/issues/7278
