### ISSUE TITLE
failed to relay S6A to Feg

### ISSUE THREAD

**Issue by jacqueline0124** [magma/magma#576]
I want to connect the AccessGateway to HSS using S6A proxy,  but when user  attach the autentication failed with logs as follows:
 Aug 20 17:44:28 agw mme[14235]: [INFO] Sending S6A-AUTHENTICATION_INFORMATION_REQUEST with IMSI: 454280000000001
Aug 20 17:44:28 agw control_proxy[12988]: 2019-08-20T17:44:28.096+08:00 [127.0.0.1 -> s6a_proxy-controller.magma.test,8443] "POST /magma.feg.S6aProxy/AuthenticationInformation HTTP/2" 400 0bytes 0.019s
Aug 20 17:44:28 agw mme[14235]: [ERROR] 5: Unable to retrieve cellular config for AG network: test
Aug 20 17:44:28 agw mme[14235]: [ERROR] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 454280000000001; Status: Unable to retrieve cellular config for AG network: test; ErrorCode: 0

 the magma version is release 0.3.72

**Comment by mpgermano** [comment]
If you haven't done so already, you need to provide LTE network configs for the LTE network and FeG network configs for the FeG network. In the LTE network configs there's a field called `feg_network_id` that should be set to the networkID of the FeG. Inside the FeG network configs there's a field called `served_network_ids` that should include the networkID of the LTE network. This creates a link between the two networks so that the orc8r can properly relay the requests.

**Comment by jacqueline0124** [comment]
Thank you very much for you help, it' OK when I configured the feg_network_id and served_network_ids.

**Comment by vik2595** [comment]
> Thank you very much for you help, it' OK when I configured the feg_network_id and served_network_ids.

Hi @jacqueline0124 @mpgermano 
Where we need to configure feg_network_id   and served_network_ids ? Into NMS dashboard ?
