### ISSUE TITLE
Misssing openvswitch dependencies | 0.3.77-1565583831-c244a678

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#583]
**EDIT**

This is not an issue - refer to:

> https://github.com/facebookincubator/magma/blob/master/docs/readmes/lte/setup_baremetal.md
> OVS needs to be built for the target env

Magma version `0.3.77-1565583831-c244a678` does not install openvswitch dependencies.

As a result, `magma@mme` and `magma@pipelined` fail to start.

Manual installation of `openvswitch` dependencies as spec'd in previous releases resolves this.

    sudo apt install openvswitch-switch openvswitch-datapath-module-4.9.0-8-amd64 python-openvswitch

**Comment by amarpad** [comment]
Hi @bmurithi can you check the instructions in https://github.com/facebookincubator/magma/blob/master/docs/readmes/lte/setup_baremetal.md and let us know if it is confusing?
We will fix the debian dependency packaging thing once we have cleaned up more of the build to automatically fail the magma deb install if the ovs debian isn't there

**Comment by bmurithi** [comment]
@amarpad I thought I did respond to this earlier./

This works fine - it would do with perhaps a change to split builds from deployment.
@tmdzk mentioned he was working on improvements to thi.

It just needs to be clear whether this completely supplants the apt-based install of magma going forward. In our case, we had already instrumented this as deployment approach.

**Comment by bmurithi** [comment]
@tmdzk @amarpad my take would be a metapackage would make sense for anyone installing magma with a well-known Kernel - that would pull the versions you guys have pushed to the repo.

Then have installation of magma for all other cases to be flexible.

**Comment by tmdzk** [comment]
Hey @bmurithi thanks for your feedback and taking the time. I work on the AGW automation. 

You're right, split build from deployment is a good practise, and that's what we did (https://github.com/facebookincubator/magma/commit/4d686fde38f88910b255c4bd59d34bc3f60bcbde) However in the current state you need some slight config changes in order to build on a target, transfer build to another target and run deployment playbook. A v2 will come out and add more flexibility. 

The new doc : https://facebookincubator.github.io/magma/docs/lte/setup_deb
