### ISSUE TITLE
If I want to refer to magma-libfluid and magma-cpp-redis packages,where can I download the source code?

### ISSUE THREAD

**Issue by chenhao5651** [magma/magma#604]

**Comment by tmdzk** [comment]
Hey @chenhao5651, thanks for taking the time to create that issue. 

_"where can I download the source code?"_
We use those different repositories in order to build those packages. 

- _magma-cpp-redis_ : 
    **cpp_redis** https://github.com/Cylix/cpp_redis (deprecated moved to https://github.com/cpp-redis/cpp_redis) checkout to tag 4.3.1

- _magma-libfluid_: For this one we use 2 repositories in order to build the package
    **libfluid_base** https://github.com/OpenNetworkingFoundation/libfluid_base.git commit `56df5e20c49387ab8e6b5cd363c6c10d309f263e` (with for now one custom patch)
  **libfluid_msg** git clone https://github.com/OpenNetworkingFoundation/libfluid_msg.git commit `71a4fccdedfabece730082fbe87ef8ae5f92059f` (with for now one custom patch)

One thing you might want to keep in mind, I've been working on open sourcing how we build all our third_party dependencies (+all the patches we made), and magma Itself, please stay tuned, should be shipped in a few days (you'll see a `/third_party` popping up)

Hope I answered all your question, I'm closing this

**Comment by chenhao5651** [comment]
Thank you very much, I see the /third_party

**Comment by chenhao5651** [comment]
> Hey @chenhao5651, thanks for taking the time to create that issue.
> 
> _"where can I download the source code?"_
> We use those different repositories in order to build those packages.
> 
> * _magma-cpp-redis_ :
>   **cpp_redis** https://github.com/Cylix/cpp_redis (deprecated moved to https://github.com/cpp-redis/cpp_redis) checkout to tag 4.3.1
> * _magma-libfluid_: For this one we use 2 repositories in order to build the package
>   **libfluid_base** https://github.com/OpenNetworkingFoundation/libfluid_base.git commit `56df5e20c49387ab8e6b5cd363c6c10d309f263e` (with for now one custom patch)
>   **libfluid_msg** git clone https://github.com/OpenNetworkingFoundation/libfluid_msg.git commit `71a4fccdedfabece730082fbe87ef8ae5f92059f` (with for now one custom patch)
> 
> One thing you might want to keep in mind, I've been working on open sourcing how we build all our third_party dependencies (+all the patches we made), and magma Itself, please stay tuned, should be shipped in a few days (you'll see a `/third_party` popping up)
> 
> Hope I answered all your question, I'm closing this

Thank you very much , I see the /third_party
