### ISSUE TITLE
draft a proposal for alternative implementation to the current python code

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6600]

**Comment by prabinakpattnaik** [comment]
PyPy is an alternative implementation of the Python programming language to CPython. PyPy often runs faster than CPython because PyPy is a just-in-time compiler while CPython is an interpreter. PyPy is a very compliant Python interpreter, almost a drop-in replacement for CPython 2.7.10 and 3.3.5. It’s fast due to its integrated tracing JIT compiler.

Recently PyPy3 v5.5.0 was released, it improves compatibility with Python 3.3 (3.3.5).

This release supports:

x86 machines on most common operating systems except Windows (Linux 32/64, Mac OS X 64, OpenBSD, FreeBSD),
newer ARM hardware (ARMv6 or ARMv7, with VFPv3) running Linux,
big- and little-endian variants of PPC64 running Linux,
s390x running Linux.

PyPy doesn't have full compatibility with the CPython ecosystem but trying to compatibility with Python 2.7 and 3.6 syntax, and 3.7.
It is also highly compatible with some of the most used libraries that can be used in Python.

We need to create a prototype for how pypy can set with magma and ecosystem.

**Comment by prabinakpattnaik** [comment]
C++ or Golang is the best approaches right now.
