### ISSUE TITLE
Magma Orc8r Public Cloud Resources Cost Analysis

### ISSUE THREAD

**Issue by arunuke** [magma/magma#6657]

**Comment by bbarritt** [comment]
A bunch of SI and OEM partners that we're working with are saying that the current orc8r cost ($30/day) is too high for them to enter into target markets.  It's so high that they are pushing for a on-prem orc8r model.

Rather than pushing too hard / pivoting to on-prem, we should first try to optimize cost and see how much we can optimize.  If it's 50% or greater, we could preserve cloud orc8r as our baseline without having to pivot so hard to on-prem orc8rs.

**Comment by arunuke** [comment]
Proposal complete and available from https://docs.google.com/document/d/1CE6tO7w9UatAgIl_oF4ftkGdWjcVmvZH3f0SiYxTRRg/edit. Targeted for v 1.7
