### ISSUE TITLE
AMF is returning protocol error when registration is tried with Invalid IMSI

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#7205]

**Comment by sureshgorijavolu** [comment]
need to attach pcap or a screenshot of pcap and narrate expected behavior.

**Comment by Balaji-Jatla** [comment]
https://drive.google.com/drive/folders/1zqijZTRS0zMXaJphOr-TfNyafD8Vo0Ke 

The pcap name is  - INVALID_IMSI.pcap

**Comment by rupa455wavelabs** [comment]
Expected behaviour: Protocol error due to cause 111,
If the decode for m5gs_mobile_identity.mobile_identity.imsi from UE registration Init request fails, then AMF sends failure message to UE with AMF_CAUSE_PROTOCOL_ERROR 111.

Tested the usecase with Invalid IMSI value receiving protocol error due to cause 111.

Reference - 3GPP TS 24.501 version 15.6.0 Release 15, Figure 9.11.3.4.3, Page No: 358

**Comment by Balaji-Jatla** [comment]
https://drive.google.com/drive/folders/1ai_2KcE4ctGM-G9QThigtaBbdaqkUCyt

We can Find the scenario file for INVALID_IMSI from the above link named 
Support _For_Inavlid_IMSI.xml
