### ISSUE TITLE
MAC Failure support is not added in AMF

### ISSUE THREAD

**Issue by Balaji-Jatla** [magma/magma#7297]
Fix has been added and Tested on NGAP Tester.
code available at magma-5G branch

**Comment by Balaji-Jatla** [comment]
configure DStester with a pair of Key & OP that does not match with what AMF has. Run the registration procedure from DStester. 

Expected Behaviour: Authentication procedure initiated by AMF sends MAC to UE. The MAC computed by UE differs from what AMF has sent.  UE sends Authentication failure with 5GMM cause #20. 

Actual Behaviour:  AMF is expected to terminate Authentication procedure.

**Comment by rupa455wavelabs** [comment]
Expected behaviour: MAC failure 
If the UE finds that the MAC code supplied by the core network in the Key and op(c) parameters are invalid, then the UE shall send an AUTHENTICATION FAILURE message to the network, with the 5GMM cause #20 "MAC failure". The network may initiate an identification procedure to obtain the IMSI from the UE or may also decides to terminate the authentication procedure

Reference 3GPP TS 24.501 version 15.6.0 - section 5.4.1.3.7 Page No: 113

https://drive.google.com/drive/folders/1ai_2KcE4ctGM-G9QThigtaBbdaqkUCyt
Scenario file: Authentication_Failure_cause #20.xml

**Comment by VinayKumar1591** [comment]
[https://app.zenhub.com/files/170803235/058fde98-32d4-4902-a92a-12ad853c1389/download](https://app.zenhub.com/files/170803235/058fde98-32d4-4902-a92a-12ad853c1389/download)
