### ISSUE TITLE
Security capabilities mismatch support is not added in AMF

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#7323]

**Comment by Balaji-Jatla** [comment]
Current AMF code doesn't supporting IA3 and EA3 security capabilities. When I tested with IA3, EA3 security capabilities using dstester by default AMF is taking IA0,EA0.

https://drive.google.com/drive/folders/1zqijZTRS0zMXaJphOr-TfNyafD8Vo0Ke
Pcap name : 5GMM_cause#20.pcap

**Comment by Balaji-Jatla** [comment]
https://drive.google.com/drive/folders/1ai_2KcE4ctGM-G9QThigtaBbdaqkUCyt
Find the scenario filre"Unsupported_UE_Security_Capabilities.xml" from the above drive link

**Comment by Chandhu-Wavelabs** [comment]
Expected Behavior : By default AMF should support ue security capabilities IA0 to IA3 and EA0 to EA3. If AMF receives registration request with any of these capabilities, it should initiate SMC with received capabilities or any of received capabilities based on preference.

If the UE detects that the received Replayed UE security capabilities IE has been altered compared to the latest values that the UE sent to the network, **the UE shall set the cause value to #23 "UE security capabilities mismatch". Upon receipt of the SECURITY MODE REJECT message, the AMF shall stop timer T3560. The AMF shall also abort the ongoing procedure that triggered the initiation of the NAS security mode control procedure.**

**Comment by Chandhu-Wavelabs** [comment]
Need to add support for security_command_reject handling in AMF

**Comment by Chandhu-Wavelabs** [comment]
Adding support for handling secure mode reject message.  

Upon receipt of the SECURITY MODE REJECT message, the AMF shall stop timer T3560. The AMF shall also abort the ongoing procedure that triggered the initiation of the NAS security mode control procedure.

**Comment by Chandhu-Wavelabs** [comment]
PR #8333 raised.

Tested with UERANSIM, working fine. Need to test with DS-Tester/TVM.

**Comment by Chandhu-Wavelabs** [comment]
Need to shift the PR #8333 from magma-5g branch to master branch

**Comment by Chandhu-Wavelabs** [comment]
Closed PR #8333 and raised new PR #8597. Need to add unit test case for decoding security mode reject message.

**Comment by Chandhu-Wavelabs** [comment]
Unit test case added
