### ISSUE TITLE
AMF is not correctly handling Registration requests for unsupported security capabilities

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#7324]
Current AMF code doesn't support IA3 and EA3 security capabilities. When UE sent a registration request with IA3 & EA3, AMF is initiating SMC with IA0,EA0. needs to be fixed.

**Comment by rupa455wavelabs** [comment]
https://drive.google.com/drive/folders/1zqijZTRS0zMXaJphOr-TfNyafD8Vo0Ke
Pcap name is 5GMM_Cause#23_1.pcap.

**Comment by rupa455wavelabs** [comment]
Expected Behaviour: Cause #23 – UE security capabilities mismatch
Refrence 3GPP TS 24.501 version 15.6.0 Release 15 - section Annexure A.3, Page No: 452

Current AMF code doesn't support IA3 and EA3 security capabilities. When UE sent a registration request with IA3 & EA3, AMF is initiating SMC with IA0,EA0. needs to be fixed.

https://drive.google.com/drive/folders/1ai_2KcE4ctGM-G9QThigtaBbdaqkUCyt
Scenario file: Authentication_Failure_cause #23.xml

**Comment by Chandhu-Wavelabs** [comment]
By default AMF should support IA0, IA1, IA2 and IA3, EA0, EA1, EA2 and EA3.  for now AMF is not supporting IA3 and EA3.

We fixed the selection of algorithms based on preference, If UE supports IA0 to IA2 and EA0 to EA2, AMF responds with IA2 and EA0, Because preference order is {IA2, IA1, IA0} and {EA0, EA1, EA2}.

If UE sends request with none of the above algorithms, AMF responds with its default algorithms IA0 and EA0. then UE should reject the security procedure with cause **#23 ue security capabilities miss match**. then AMF handles the rejection.

Need to add the support for handling security mode reject.

**Comment by Chandhu-Wavelabs** [comment]
In PR #8522 we covered this issue, AMF rejects the initial registration if UE sends initial registration request without any combination of algorithms from IA0 to IA2 and EA0 to EA2 with cause #23(ue security capabilities miss-match).
