### ISSUE TITLE
AGW bare metal build control of which sub release within the TAG branch

### ISSUE THREAD

**Issue by pkapatsos-blinq** [magma/magma#7727]
We are not sure if its a bug or feature so placing here to track. It relates to using bare metal scripts and the APT or Artifactory repo images used and how to control which is used if possible.

### Your Environment

- **Version: R.1.5 or 1.4 or 1.3 etc ( we'll focus on R1.5 )
- **Affected Component: Access Gateway, 
- **Affected Subcomponent: 
- **Deployment Environment: Bare metal 
### Describe the Issue

**To Reproduce**
1. Build base OS via https://docs.magmacore.org/docs/lte/deploy_install#install-access-gateway-bare-metal
2. Then run su
wget https://raw.githubusercontent.com/magma/magma/v1.5/lte/gateway/deploy/agw_install_ubuntu.sh
or 
wget https://raw.githubusercontent.com/facebookincubator/magma/v1.5/lte/gateway/deploy/agw_install.sh
3. We use the tag or GIT repo version of 1.5 however once scripts complete they use whatever is the latest or placed in the Aritfactory location for that tag.  more below.
4. No error rather how do we control using the scripts or other wise.

**Expected behavior**
the scripts above use 1.5 tag and the AGW builds 1.5.1 release bases that the source list has this entry
deb https://artifactory.magmacore.org/artifactory/debian focal-1.5.1 main
prior releases it was APT source list 

apt policy magma shows 1.5.1 ( which is OK but how can we control this sub version or which would be build ?)
![image](https://user-images.githubusercontent.com/61711855/123115486-23315b80-d40e-11eb-8192-6cb4974ee93c.png)

![image](https://user-images.githubusercontent.com/61711855/123116563-034e6780-d40f-11eb-89f0-a01582b49ad7.png)

How would we indicate or control which of the above 1.5.1.x would be build rather than always the candidate ?

Example of 1.4 
![image](https://user-images.githubusercontent.com/61711855/123118329-89b77900-d410-11eb-9732-d4026c5e7d09.png)

How would we say build release in red box vs candidate or default in a script ?
 ![image](https://user-images.githubusercontent.com/61711855/123118574-c1262580-d410-11eb-9c75-36c18c02981e.png)

**Additional context**
We can share install logs  however this an ask at how to control what's coming from artifactory  or packages repo ? as it will overwrite if updated to a newer release ,

**Comment by tmdzk** [comment]
Hello @pkapatsos-blinq 
Thanks for the issue. 
I understand the current system is a bit confusing. But let me walk you through our release process/installation.

As you pointed out, we have a few steps in order to install an agw, those step will always point to our latest stable release (current one is `1.5.1`, we'll soon have `1.5.2` and then `1.6.0`). That's why we have multiple versions and multiple distributions (`stretch-1.5.1` etc..)

`"the scripts above use 1.5 tag and the AGW builds 1.5.1 release bases that the source list has this entry"`
This is not 100% correct, you don't "build" the agw, you just download the .deb from artifactory.magmacore.org and use apt to install it. For that you need to connect to the registry and tell it which package you desire `distribution` `component` `architecture`. in your case stretch-1.5.1 main amd64

`apt policy magma` list all the packages that are available in your configuration, on your screenshot we can see all the magma packages inside stretch-1.5.1 that you can install. By default apt will take the latest and you don't have to specify any package in order to get the latest packages with the most recent packages. apt uses the timestamp in order to define the latest package. 
 1.5.1-1624485681-ae972900 = <VERSION>-<TIMESTAMP>-<COMMIT_HASH>

So you don't really have to bother which package to pick as apt will do it for you. I understand It can be confusing when you execute `apt-cache policy magma`

Note: when you execute your installation scripts, we automatically detect your OS and point you to the right distribution, so in your case either `stretch-1.5.1` or `focal-1.5.1`

Note2: in your last screen shot the .deb that has been installed and is the best candidate is the one with the `**` because it's simply the latest. 

Please if you need any more information feel free to contact me or the DevOps Team here or on Slack, we're eager to hear your feedback in order to improve/make our installation process smoother. 

I'm closing this for now as It's not a "bug" but I'll keep the discussion open

**Comment by pkapatsos-blinq** [comment]
@tmdzk  thanks Tim yes agreed not a BUG and the clarification on how we get these downloaded based on OS then apt installs.
I can confirm with this exception the install process has become seamless and very smooth.
Simply then we can NOT control the apt versioning or what comes from deb or airtifactory .. You will always control this correct ? it will always be the latest package for that release? Am I wrong or not understanding ? 

Here is the background and why we are asking, we have had releases in 1.3 , 1.4 and 1.5 . where we build a bare metal AGW run test cases  with our enb/cpes . Then a few weeks or some times days later build another bare metal server and get a different sub release which is 1.x.y-(sub release#) Ok and we have been changing the major releases as they come due to the enhancements.
Also most times usually better experience with the latest's or fixes applied however when issues arise or say we get a fix for a release which the latest later breaks it . We had this in 1.4 when we needed an IE added to the MME to pass Testing . Then we had to start over in new sub releases broke it then the build move to 1.5 .I wont get into the issues here.
 We are about to go into customer trials so its around using the same versions for all customers exceptions for major releases.  
 We don't want one to have R.1.5.1-111111 and the other to have R.1.5.1-222222  or we want to be building the verison we validated and passed our testing with then keep building that release unless we want another version( this is the AGW apt version not GIT tag).
Can we accomplish this is or is it possible ?

**Comment by talkhasib** [comment]
I discussed this with @tmdzk and decided on the following
Going forward we will enforce a single antifactory image per release version. Thus, the minor version will get bumped up anytime a new build is uploaded to the registry for the same release.
This is applicable to the production registry. The test registry might have multiple images with same version number.

**Comment by pkapatsos-blinq** [comment]
@tmdzk and @talkhasib sorry for the delay was on vacation thank you  understood. I think ..lol.
