### ISSUE TITLE
Export control path network metrics

### ISSUE THREAD

**Issue by waqaraqeel** [magma/magma#8028]
# Export Control Path Network Metrics

## Problem

Services running on the access gateway communicate with the orc8r and generate
control traffic. We do not have visibility into the amount, patterns, and
service-level breakdown of this traffic. As we try to minimize control plane
bandwidth consumption for our deployment partners, especially those with
satellite backhaul, visibility into control path bandwidth consumption is crucial.

## Solution

- Use eBPF on the access gateway to monitor network traffic going out.
- Maintain per-service, per-destination (`ip:port`) byte and packet counters in the eBPF program.
- Create a new Python service to load the eBPF program into the kernel, read its counters and expose those counters as Prometheus metrics.
- Let `magmad` collect those Prometheus metrics and upload them to the orc8r so they are available in the NMS.

## Non-goals

- Change collection/export methods for existing data-path metrics.

**[Design doc](https://magma.github.io/magma/docs/next/proposals/p018_control_network_metrics)**

**Comment by amarpad** [comment]
Nice!

**Comment by electronjoe** [comment]
@waqaraqeel do you mind posting a PR for the design doc to Magma's repo, tagging this GH Issue in the description? I'll stamp it for merge (discussion will occur here) but that versions your design doc and allows conversation here on well defined document versions.

**Comment by waqaraqeel** [comment]
> @waqaraqeel do you mind posting a PR for the design doc to Magma's repo, tagging this GH Issue in the description? I'll stamp it for merge (discussion will occur here) but that versions your design doc and allows conversation here on well defined document versions.

Added in #8040.

**Comment by electronjoe** [comment]
Thanks Waqar!  Dropping feedback on the proposal revision here.

## Proposal

> Every magma service running on the orchestrator will get a separate Prometheus Gauge by the name `{service}_bytes_sent` and `{service}_packets_sent`

For this style of metric, the advice is to use a [Counter](https://prometheus.io/docs/concepts/metric_types/#counter) type. Any metric that purely increments (omitting restart) should prefer `Counter` type.  What you'll find is that counters decimate much more pleasantly and with fewer surprises (and decimation is a common need for both querying, and time series database compression in the background). By decimation I mean e.g. taking your reporting interval of every 5 seconds and reducing it to every 20 seconds.  Accumulator style metrics simply discard. Gauges require a policy for decimation and it can get dicey.  And in the event of a telemetry outage (e.g. network disconnection or some such) you are able to capture behavior during the period of outage.

Second comment - where will the enumeration of `{service}` reside (and I guess a mapping to string name)? Is that also a configuration parameter or is it dynamic somehow? One concern I have is that we would like to monitor services possibly not our own (e.g. Linux jobs pulling updates). How does that slot in here w.r.t. service identification?

> For each Gauge, labels will indicate networkID, gatewayID, and dstIP:dstPort.

Do all metrics contain `networkID` and `gatewayID`? I'm not clear why these would be necessary at the kernsnoopd level or even magmad level (I could see them being pinned on at e.g. orc8r)? I probably need to go re-review the "life of a metric" document you are putting together, which by the way would be nice to have a link to in Context above (but maybe isn't ready?).  I assume that `gatewayID` is uniform for all `{service}_*` metrics?  Possibly `networkID` is not? But I don't actually know what `networkID` is - and probably should at this point.

> Once Prometheus Gauge values have been set, they will follow the existing Magma metrics path: the magmad service will read the Gauges from kernsnoopd and upload them to metricsd at the orchestrator every sync_interval seconds.

Larger context question - do the metrics capture the time of measurement and pass that along up the forwarding chain? Or is this `sync_interval` going to cause jitter in perceived metric posting time at NMS.  That is, if a telemetry Counter is updated to value 5 at 1:15 PM local time and `sync_interval` was 2 minutes - would NMS believe the sample was taken at 1:17 PM local time? Or is the timestamp passed through.  Lack of pass-through has caused problems for me in the past (though one cannot rely on any precise timing data using these timestamps either way).

### A Python-Free Future?

I think you could use a brief subsection that clarifies how your work here would be updated in a Python-free AGW future (should that come to pass, overtaken by C++ or Golang for example).  Perhaps you could briefly enumerate what that migration might look like for your Proposal and cite Alternatives below as necessary?

## Alternatives

You might note also that this eBPF solution may be extended for a wide variety of monitoring purposes on the AGW, while many of the `Alternatives Considered` cannot.

Some of the negatives for the alternatives only exist because we intercept prometheus telemetry per-binary and wrap it / report it towards magmad using a custom gRPC API that therefore requires per-programming-language converter functions (which we have today in Python and C++).  This context is missing in the document so far and would be remedied by linking context to your "life of a metric" document and clarifying / re-iterating with a link here?

- nghttpx
  - Presumably cannot capture general traffic outside Magma daemons?

## Cross-cutting concerns

Regarding the performance concerns / open isssues -> good to enumerate possible remedies.  It's important we clarify what experimentation we will use to measure impact and determine if this is a non-concern (or how we mitigate if a problem). Maybe you do this in Open Issues - I'll see shortly.

Nit: close parethensis on `(see Open Issues.`.

Deployment concerns would be good to get feedback from DevOps folks, not sure we have looped them in (e.g. @tmdzk).

### Observability and Debug

I think we'll want some way of exploring the eBPF counter results prior to filtering and prometheus generation - as a form of debug? This could be accomplished by e.g. a GLOG threshold logging statement (requiring process restart with higher GLOG v level) or some other strategy to conditionally enable the logging.

Try to think through the steps you went through to prototype this design, and make them repeatable in your production design somehow (while not being spammy, fragile, etc).  Could even offer a gRPC based API for dumping counters or similar (that might be nice!).

## Open Issues

`Is network utilization on our access gateway usually close to 100%? Are our gateways starving for CPU?` - Yes, but I think no solution you have enumerated for telemetry gathering is free of cost. I think more important is to quantify the impact level by e.g. lab testing (does eBPF as injected on these kernal triggers impact control plane or data plane capacity of the AGW, and if so by how much).  The precise experiment for this should probably be described somewhere and linked here - or a summary provided inline here?  You might check with @ulaskozat or @talkhasib for control plane side test strategy, and @pshelar for the datapath.  We may need to note here however that the present characterization of AGW capability may have jitter that eclipses the impact of the eBPF.

**Comment by electronjoe** [comment]
One more burst of thoughts here.

Magma may not have a consistent naming style for metrics - I'm not sure. But for Counters consider a suffix e.g. `_total` or similar. This makes it clear to the consumer writing queries or looking at a graph, that this is accumulated not an instantaneous value.

Second is a bit more complicated.  Think about how you would want to graph these metrics, or alert on them.  It is likely the case that you might want to sum the traffic across services? Or split in some way like that.  If this is the case, then it is advised to not have a metric-per-service but instead to use a dimension that specifies the service.  This holds for any metric you design broadly - if there is some property you are encoding into the metric name, but for which you might want to make operations across, it is far preferred to use a dimension. If things are split across metrics you then face challenges around decimation and synchronization behavior, and you may easily miss out on newly added values (e.g. new services that are added) - to name a couple reasons.

Read the [Prometheus Metric and Label Naming Best Practices](https://prometheus.io/docs/practices/naming/#metric-and-label-naming).

**Comment by waqaraqeel** [comment]
Thanks @electronjoe for the detailed feedback! It was very helpful!

> For this style of metric, the advice is to use a Counter type

That's right. Changed from gauges to counters.

> where will the enumeration of {service} reside

The `ServiceRegistry` has the enumerations and can be made to provide a port to service name mapping as well.

> Do all metrics contain networkID and gatewayID? I'm not clear why these would be necessary at the kernsnoopd level or even magmad level (I could see them being pinned on at e.g. orc8r)?

`networkID` and `gatewayID` are indeed pinned at the Orc8r. Mentioning them here was confusing so I have removed the mention.

> But I don't actually know what networkID is - and probably should at this point.

A Magma deployment can consist of multiple networks. `networkID` identifies them.

> Larger context question - do the metrics capture the time of measurement and pass that along up the forwarding chain? Or is this sync_interval going to cause jitter in perceived metric posting time at NMS.

Time is [stamped](https://sourcegraph.com/github.com/magma/magma@v1.6.0/-/blob/orc8r/gateway/python/magma/common/metrics_export.py?L34) at the `magmad` service. But that shouldn't be a big problem. It would just introduce a lag between the collection and reporting time and since the counters are monotonically increasing, there shouldn't be any jitter.

> it is advised to not have a metric-per-service but instead to use a dimension that specifies the service.

After looking into this more, I abandoned the per-service metric idea. That would indeed be bad practice. Some metrics also already use the `service_name` label so there's precedence (e.g. UNEXPECTED_SERVICE_RESTARTS)

> But for Counters consider a suffix e.g. _total

Added suffix `_total`.

I have made other modifications from your feedback and pushed the changes in #8140.

**Comment by waqaraqeel** [comment]
A larger question: Previously, we only talked about measuring outgoing traffic and counting bytes/packets keyed by destination IP address and destination port. But now it seems to me that we also care about incoming:

> we would like to monitor services possibly not our own (e.g. Linux jobs pulling updates)

Should we also instrument the receive path?

What useful information do destination IP address and port give us? As labels in a Prometheus metric, their domains are pretty much unbounded and will result in separate time-series data for each `ip:port` pair. So that's a huge overhead. I think we only care about the service or binary that is sending or receiving traffic. In case of traffic going to (coming from) the Orc8r we may also want the destination (source) Orc8r service. Is that right?

**Comment by waqaraqeel** [comment]
Implementation complete and landed. Closing.
