### ISSUE TITLE
sessiond crashed on AGW of Brisanet setup

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#8331]

**Comment by ganeshg87** [comment]
I have replied to Alves, waiting for response:

Ganesh Gedela  13 hours ago
@Gustavo Alves,
- it seems normal mme exit and does not seems to be related mme issue
 - problem statement refers to sessiond, but we could not find information related to it
 - incase if the problem is observed again, can you please share the following information
        1. mme.log(/var/log/mme.log)
		2. syslog(/var/log/syslog)
		3. crash back trace
		4. steps to reproduce
 - our testing setup we tried mentioned scenario and the issue was not seen, so the above logs mentioned were helpful.

**Comment by panyogesh** [comment]
Marking it as closed as no more information is provided.
