### ISSUE TITLE
Sanitize stale session state in Orc8r

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#8621]
Original discussion: https://github.com/magma/magma/discussions/7681

## Problem
As part of AGW state sent to Orc8r periodically, SessionD sends a snapshot of all existing sessions keyed by its IMSI.
As SessionD can only keep track of active sessions in the system, there is no way for SessionD to remove subscriber state in the Orc8r once a subscriber leaves the AGW. As Orc8r does not clean up stale state and NMS also does not check for stale state before displaying it, we end up with a growing number of stale subscribers that show active sessions.

## Possible solutions
1. SessionD sends a per-AGW state as a single object. This way, every state reported has the most updated snapshot of all subscribers. We will need to do indexing on the Orc8r side to enable per-subscriber queries from this state.
2. Orc8r periodically goes through all reported states to remove stale entries.

One caveat here is that with approach 1, we will still have stale state if an AGW goes offline. However, this may be OK if we also display the last checkin time to let the user know the state may be stale. 

## Actions
1. @themarwhal to add an additional SessionD state that encapsulates all subscribers in one object.
2. @hcgatewood to add any Orc8r modifications needed to support the same subscriber state API endpoint.
3. Once we have migrated to the new state, @themarwhal can remove per-subscriber state entries from SessionD's side.

**Comment by ekowtaylor** [comment]
Phase out implementation and land design in this sprint. @themarwhal  to help break this down for tracking in this sprint

**Comment by bhuvaneshne** [comment]
Hello @themarwhal , @hcgatewood ,
I was searching for existing bugs to report this exact issue when I found this thread.
Wanted to check how this is coming along.
Regards,
Bhuvanesh

**Comment by sebathomas** [comment]
Concrete plan for solution 1:
1. Adapt sessiond's `OperationalStatesHandler` to produce a new kind of state with type `gateway_subscriber_state`. This will get the hardware ID as a key and then contain a map of all IMSIs to the corresponding subscriber state. This will ensure that there will also be a state update if the list of subscribers is empty. For the moment, sessiond can send both types of state until the changes on the orc8r side are finished.
2. Add a new table `gateway_subscriber_states` to subscriberdb that will contain the reindexed state. The table will have the following structure:

| Column  | Type |
| ------------- | ------------- |
| network_id  | text  |
| gateway_id  | text (hardware UUID)  |
| imsi | text |
| last_updated_at | int8 (unix timestamp) |
| reported_state | bytea (same as the reported subscriber state before) |

3. Extend subscriberdb's reindexer to also handle the new `gateway_subscriber_state`, split it up into different states per subscriber. Then update all states in `gateway_subscriber_states` belonging to that gateway, i.e. upsert them into the new table and remove all IMSIs that no longer exist.
4. Change the existing GET `subscribers` and `subscriber_state` calls to get subscriber state data from the new table instead of from the state service.
5. Remove the old logic in sessiond that produces individual subscriber states.
