### ISSUE TITLE
[AGW][NMS] Bootstrapping enhancement

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#8676]
### Your Environment (If applicable)

- **Version:** 1.7 or newer
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Boostrapping and checkin
- **Deployment Environment:** orc8r (on-prem or AWS) + AGW (BM/VM)

### Describe the problem

**Description**
To onboard a new gateway to a network, the gateway usually requires a couple of static files to be able to connect to the correct `orc8r`, namely `rootCA.pem` and `control_proxy.yml`. Usually the `rootCA.pem` has to be acquired through some offline means (e.g. get it from the internet for the signing CA or through the administrator deploying the k8s cluster in the case of self-signed certs). Further, the `control_proxy.yml` file requires several manual inputs (bootstrap_address and cloud_address). 

These static files are relatively harder to get the very first time and require manual methods to construct the file, hence increasing the likelihood of potential misconfigurations. 

### Describe your idea(optional)

**Description**
These files do not change as a function of tenants / organizations on the orc8r. Everyone under the same orc8r uses the same rootCA.pem and the same cloud/bootstrapper addresses. The addresses in `control_proxy.yml` are either well known API names (`boostrapper-controller.yourdomain.tld` or `controller.yourdomain.tld`) or something to the effect of `bootstrapper-controller.magma.svc.cluster.local` in the case of on-prem k8s deployments. 

The proposal here is to make these files available through the NMS for every tenant / organization. This may be done in two steps.

Step 1 - Let the administrator pre-define these values from the `master` organization that then makes this content readable to all other tenants in the tenant view and download from there. 

Step 2 - Auto populate this information based on the deployment type and the information gathered during the installation phase. 

The impact will be a cleaner workflow to deploy a new gateway and fewer configuration info the end user has to consciously add.

**Comment by hcgatewood** [comment]
I approve of the sentiment, but I think the implementation will need to be a bit measured

Constraints:

1. We can't auto-populate the rootCA.pem, because that's the only way the AGW has to validate that the controller is authentic (avoid MITM)
2. We can't auto-populate the control_proxy.yml, because that's the only way we can point the AGW to the right controller domain name

That said, here's what we can do (respectively)

1. We can, in the default setup, remove the need for a rootCA.pem by using ACME/Let's Encrypt instead of self-signed certs -- then we can restrict controllers to *only* using publicly-valid certs (either via ACME or traditional methods), so then the AGW can use its OS-provided trust anchors rather than rootCA.pem. We will add this feature as part of the Orc8r Security BetterEng workflow, hoping EOY but tbd
2. Given a controller domain name, we could indeed otherwise auto-populate the control_proxy.yml. So what we could do is reorient the control_proxy.yml values a bit such that the domain name is only provided once, and then the override control_proxy.yml (in /var/opt/magma/configs) can *contain just the `domain: your.root.domain.com` field* and then use the base control_proxy.yml (in /etc/magma/configs) for all the other defaults

With this in hand, provisioning an AGW would be simplified to:

- Install OS + AGW pkgs
- Edit single-line control_proxy.yml to add the controller's root domain name
- Provision AGW via NMS (needs AGW's hwid and long-term secret key)

Future improvements to this workflow:
- Install AGW: should be independent of the OS, and eventually as simple as installing helm charts (this will require moving our datapath from OVS to eBPF, which will be a long-term play cc @pshelar)
- Provisioning AGW via NMS: AGW could generate the curl command to use to provision the AGW -- the operator would just need to run that curl command from a device that has an admin_operator cert

@sudhikan lmk your thoughts 🙂 

cc @ardzoht @markjen

**Comment by sudhikan** [comment]
@hcgatewood thanks for your thoughts. two followup thoughts:

1. Auto populating rootCA.pem and control_proxy assumes an underlying security of having access to the `master` organization. As long as we trust the access to the NMS (tenant or master org), I think creating artifacts where the user  downloads from NMS is relatively secure and avoids MITM (there is a level of trust in the administrator but I think that issue exists regardless). The proposal is not to populate them directly on the gateway, but have these files available for download from the NMS directly so as to not have an out of band mechanism to procure them. 

2. I think just specifying just the domain info for control_proxy will be impactful, but this might cause some issues with on-prem deployments.

**Comment by hcgatewood** [comment]
> @hcgatewood thanks for your thoughts. two followup thoughts:
> 
> 1. Auto populating rootCA.pem and control_proxy assumes an underlying security of having access to the `master` organization. As long as we trust the access to the NMS (tenant or master org), I think creating artifacts where the user  downloads from NMS is relatively secure and avoids MITM (there is a level of trust in the administrator but I think that issue exists regardless). The proposal is not to populate them directly on the gateway, but have these files available for download from the NMS directly so as to not have an out of band mechanism to procure them.
> 2. I think just specifying just the domain info for control_proxy will be impactful, but this might cause some issues with on-prem deployments.

@sudhikan Okay I think I misunderstood the proposal then -- so rather than having the AGW itself ask NMS for these values, you're suggesting the *operator* can grab them directly from NMS (via their own e.g. browser) and then e.g. scp them to the gateway (?)

In this case, why do the values need to be attached to the master NMS tenant? The rootCA will of course be the same across tenants, and the control_proxy.yml will be largely (if not always completely) the same -- but we can still make those those read-only defaults available for download to each respective NMS tenant (?)

I think this is pretty reasonable and a definite value-add then, just probing the requirement that only the master tenant has access

**Comment by sudhikan** [comment]
> ...you're suggesting the operator can grab them directly from NMS (via their own e.g. browser) and then e.g. scp them to the gateway (?)...

Yes. 

so my proposal was more to populate it in the `master` org (btw that name should also change :-)) and have the info be replicated to the tenant organization... I think we are saying the same thing now. 

I only suggested seeding the information from the master tenant as that will be the single point of write access for the cluster administrator.

**Comment by hcgatewood** [comment]
Gotcha. Sounds good to me then!
