### ISSUE TITLE
Update Magma release naming and support committments

### ISSUE THREAD

**Issue by PARitter** [magma/magma#8778]
# Update Magma release naming and support committments

## Problem

Magma currently uses Semantic Versioning for releases (e.g., x.y.z or 1.6.1).  This versioning creates certain problems when coupled with Magma's recent move to a modified Agile release process.  Most particularly, the new release process introduces the possibility of "missing" releases (details below).

In general, Semantic Versioning is considered most appropriate for more mature projects with infrequent releases.

## Solution

The Magma project is moving to more frequent releases co-ordinated with our development sprint cycles.  We propose that the project shift to a CalVer based release nomenclature (e.g., 21.07 for the release made in July of 2021) and will tag each release as "RC" (release candidate) or "Stable", as determined by the project release team and TSC (e.g., 21.07-rc, 21.08-stable, etc.).  The project would then offer bug fixes and support on each "Stable" release back to the last "Stable" release.

In the future, after Magma matures further, we may choose to offer Long Term Support (LTS) releases with an extended support period.  At the current time the codebase is evolving too quickly to make LTS commitments.

## Non-goals

No attempt is being made to dictate the projects release, CI or CD processes.

## Prior Practice (Releases up to 1.6.0)

Prior to release 1.0.0, Magma releases were made when content and/or bug fixes became available and were deemed stable enough to release.

With Magma release 1.0.0, the Magma project team set a target of doing a release approximately quarterly, with minor releases made on an ad-hoc basis for bug fixes or specific user content.  This approach has proved challenging and the results have been inconsistent (though after 1.6 the improving codebase quality and CI tools make this  likely to stabilize going forward).

Magma’s release history, below, demonstrates that the goal of “quarterly” releases has rarely been met.

| Release | Date | Notes |
|--------------|---------------|-----------------|
| 0.3.74 | Jun 24, 2019
| 0.3.75 | Jul 15, 2019 |
| 0.3.76 | Aug 1, 2019 |
| 0.3.77 | Aug 11, 2019 |
| 0.3.78 | Aug 27, 2019 |
| 1.00-apha1 | Sep 7, 2019 |
| 1.0.0-rc1 | Oct 24, 2019 |
| 1.0.0 | Oct 31, 2019 |
| 1.0.1 | Apr 9, 2020 |
| 1.1.0 | May 18, 2020 | 7 months from 1.0.0
| 1.2.0 | Sep 13, 2020 | 4 months from 1.1.0
| 1.3.0 | Oct 11, 2020 | 1 month from 1.2.0
| 1.3.1 | Nov 10, 2020 |
| 1.3.2 | Dec 3, 2020 |
| 1.3.3 | Jan 14, 2021 |
| 1.4.0 | Mar 16, 2021 | 5 months from 1.3.0
| 1.5.0 | Apr 28, 2021 | 1 month from 1.4.0
| 1.5.1 | Jun 4, 2021 |
| 1.5.2 | Jun 24, 2021 |
| 1.6.0 | Jul 6, 2021 | 3 months from 1.5.0

## Why change?

To date, the Magma project has not been successful releasing on a quarterly cycle and release timing has been fairly unpredictable.  We believe that the transition to Linux Foundation's more open development process, the maturing of the Magma codebase, improved CI tools and fundamental changes to the Magma feature prioritization process all conspire to make this less likely to succeed going forward.

The mismatch between the "targeted" release cadence and the actual result creates the impression that the release process itself is broken when in fact the opposite is actually true - the project's release discipline has allowed us to make higher quality releases, better tested and more stable with each release.

At the same time, Magma's internal feature prioritization and development processes have continued to evolve.  The project is currently using a "modified Agile" development process with feature sprints lasting approximately 3 weeks.  Continuously evolving CI practices and testing discipline means we could consider doing smaller, more frequent releases while still achieving an incremental improvement in stability with each release.

## Other project practices

Several other Open Source projects were reviewed to find best practices for release management.

**Ubuntu**.  Ubuntu is Canonical's Linux distribution.  It is well known for having a predictable release process with over 10 years history of on-schedule releases.  Ubuntu releases on a 6-month release cadence (April/October) and declares every 4th release, the October release in even-numbered years, to be a Long Tern Support (LTS) release.  LTS releases of Ubuntu are supported for a period of 10 years from their release date, with new hardware support included for the first 2 years, feature maintenance and backports for 4 years, and security updates for all 10 years.

*Practices to emulate*
- Use of [CalVer](https://calver.org/about.html)-based releases
- Predictable, well known cadence of LTS releases

**Linux Kernel**.  The Linux Kernel development at Kernel.org is one of the highest velocity Open Source projects, with an unusually large base of contributors.  Kernel.org declares releases continuously from a single branch with releases every 2-10 weeks.  Each release is given one of four tags: 'RC', 'Mainline', 'Stable', or 'Long Term'.  Support is offered for the latest Stable release, with each Stable release deprecating support for all prior releases.  Extended support for 6 years is offered for each Longterm release.

*Practices to emulate*
- Support tags for each release

**Kubernetes**.  Kubernetes targets releases every 3 months (4 releases/year) and manages each release cycle on a strict calendar published openly in their github repo (e.g., [Release 1.23](zhttps://github.com/kubernetes/sig-release/tree/master/releases/release-1.23).  Kubernetes uses semantic versioning as detailed at SemVer.org.  Semantic versioning is structured as Major.Minor.Patch, with the major version number being incremented if there is a breaking change without backward compatibility support in any API.  Each release has a support target of 1 year (9 months for releases 1.18 and older).

*Practices to emulate*
- Published release cycle calendars, tight project management against that calendar to ensure predictable releases

**HomeAssistant**.  HomeAssistant (HA) is one of the top "end user" application projects hosted on GitHub with over 45,000 "stars", hundreds of committers and a very dynamic community.  HA maintains a single main branch and releases monthly, with a Stable release issued on the first Wednesday of each month, with one or more patch releases as needed to quickly address issues.  HA uses CalVer release versioning, which maps nicely to their commitment to release each month. Each stable release deprecates support for the prior Stable release.  HA makes no attempt to offer "support" or patches for older releases.  Their effective CI/CT environment allows them to maintain a "green light" on the main branch at all times.  They are able to maintain this release schedule with a largely volunteer "staff" (though a small number of key players are employed by a parent org Nabu Casa).

*Practices to emulate*
- CalVer release versioning
- Strict CI & Test
- Predictable monthly releases

### Release naming

Going forward, we propose that Magma will use [CalVer](https://calver.org/about.html) based release naming formatted as yy.0m (e.g., a release made in July 2021 would be named 21.07).  Additional releases in a single month should be rare, but if needed they will be tagged with a minor release number, yy.0m.n (e.g., a second release in July 2021 would be named 21.07.1).

This release naming convention is chosen to indicate a hard-break from the prior practice and to confirm to other best-practice projects (e.g., Ubuntu, HomeAssistant).

*Future refinement*: Magma should attempt to evolve towards a predictable release cycle.  For example, HomeAssistant commits to a release every month, issued on the first Wednesday of each calendar month.

### Stable and LTS releases

Periodically, as determined by the project Codeowners and TSC, releases will be tagged as "stable" releases.  Stable releases become support commitment points.  Users deploying the Stable release should be able to expect the Magma software to meet its functional, performance and reliability commitments detailed for the release.  Stable releases are eligible for support and bug fixes until the next stable release.  At any given time, the newest “stable” release is considered to be the fully supported release.  Users of releases prior to the last "stable" release may be asked to upgrade to the most recent "stable" release as part of any support commitment.

Each incremental release made after the "stable" release makes offering support more and more difficult to guarantee.  Because of this, we propose that *"stable" releases should be declared no less than every 6 months.*

*Note*: As a practice, Magma should make the "stable" releases more predictable.  The industry practice models that most closely match what is proposed here are HomeAssistant, The Linux Kernel, and Ubuntu.  HomeAssistant makes no attempt to declare stable releases - a practice that makes sense given its hobbyist user base and rapid pace of change.  The Linux Kernel targets every "2-4 releases" as stable but announces which release will be stable at least two releases ahead of time.  Ubuntu, a large and very stable project, has a set cadence where the "yy.04" and "yy.10" releases are pre-defined to be the "stable" release points (and in fact Ubuntu make it difficult to locate the intermediate releases).

*Future Refinement*: As the Magma project matures we will need to offer a Long Term Support (LTS) model.  LTS release branches are maintained for an extended period of time (3-10 years, depending on the project) and a commitment is made to backport important bug fixes, security vulnerability mitigations, and some features into the LTS branch.  This gives users of the platform an extended period to use the software with support without forcing upgrade to the latest stable release.  At this time, however, the Magma codebase is changing too rapidly and the development community is not able to dedicate the resources it would take to offer LTS releases.

### Support Commitments

We propose that the Magma project sets a goal to maintain its repos and CI tools to facilitate “support” back to the most recent "Stable" releases.

We propose that the project support commitment be framed as follows:
* Important bug fixes and/or remediation of security vulnerabilities are backported to the most recent "stable" release, which can then be re-issues as a “minor” release (e.g., if most recent stable is 21.07-stable backported fixes may be released as 21.07.1)
* Users are generally required to upgrade to the next release in order to make use of new features or capabilities contained in that release.  There is no commitment to backport new features/capabilities to the most recent “stable” release.
* Users that require “stable” release support would be encouraged to wait until the next “stable” release to make use of new features/capabilities.

## Alternatives Considered

We considered the alternative of sticking with Semantic Versioning (e.g., 1.6, 1.7, 1.7.1, etc).  Semantic versioning does have several advantages:

* Familiarity - the project is currently versioned this way.
* Updating the “major” release ID can indicate major/breaking changes (e.g., the SemVer.org recommends changing the major version number if/when there are breaking changes in your primary API)

Disadvantages of Semantic Versioning for Magma are:

* Changes in the Magma release process will lead to discontinuous numbering of releases if the release team starts a branch but deems it not releasable for quality or other reasons. In the past, the release team would continue working on and patching a proposed release branch until it was stable enough to release.  This led to the unpredictability of Magma’s release cadence (e,g, the 1.4 release took many months to stabilize leading to the long time lag between 1.3 and 1,4 and also the very short period between 1.4 and 1.5).  With the revised “modified agile” release process if a branch is made and is not releasable before the end of the next sprint cycle it is discarded and the next release attempt made on a new branch.  Note that this “potential” discontinuity has already been  observed in practice as the 1.7 release attempt was not successful.
* Moving to a new release nomenclature at the same time as we adopt the modified Agile release process helps memorialize the change in release philosophy.

**Comment by markjen** [comment]
Note that with a 3 week sprint cadence, approx every other month will have two releases. Also, if we move even closer to CI/CD, release frequency will increase further. 

Should we look at the version strategy of a project like [chrome/chromium](https://www.chromium.org/developers/version-numbers)? They do a modified SemVer w/ release stable/beta/dev channels that might match our development/release style a bit better

**Comment by hcgatewood** [comment]
Hey @PARitter thanks for putting this together, looks great! I have a couple notes

## CalVer quirks

To Mark's point, I think CalVer couples us to the timings of our release. Which, if/as we continue to move to more-frequent releases, would compound the issue Mark mentioned

To me, we need to always reserve the patch version for patches to existing releases -- so e.g. 21.07.1 would be e.g. a security-critical *patch* to 21.07, rather than an additional release. So this makes CalVer a bit awkward if/when we release more than once per month

So if we wanted to stay with CalVer-like, this would be something more like YEAR.BUILD.PATCH

## Additional versioning inputs

I had previously brainstormed on this and come to something like MAJOR.BUILD.PATCH where

- MAJOR means manual action is required to perform the upgrade (aside from initiating it)
- BUILD is the same as BUILD in chrome/chromium
- PATCH is any critical patch we had to add to a particular BUILD

This would have the following affordances

- MAJOR increments mean operators need to perform non-trivial work to complete the upgrade, and/or the upgrade is not downgrade-safe. We will likely have a lot of these at first, with the goal of progressively decreasing their frequency
- BUILD is an ever-increasing number
- BUILD.PATCH is a fully-qualified name for a release, while MAJOR.BUILD.PATCH is the canonical name
- Generally, devs would only care about BUILD. Partner bugs may generate a PATCH, and when we perform each release we determine whether to bump MAJOR

Just my inputs, haven't fully thought through this yet. I agree that semver's default descriptions are somewhat incongruent in our case, since we're releasing an end-product rather than a software library. As mentioned I also am unsure CalVer will solve all our issues, so what I propose above is just an initial input

I do like the LTS idea, I think it could also work with something like^

## Controller-gateway compatibility

I think this proposal is the right place to also bring up an initial discussion of explicitly specifying controller-gateway compatibilities. Do we want to enforce that they can only diverge by 1 BUILD version?

Or maybe we enforce that they can only diverge by at most 1 LTS version

The thing I'm trying to avoid is a blanket "controller will never break backward compatibility for a gateway", because that will trap us into never being able to refactor old/dead code. I think something like 1 LTS version seems reasonable, but I think this proposal is a good place to explore that 🙂 

cc @PARitter @markjen

**Comment by arunuke** [comment]
Fully agree on the calendar based naming (over the semantic naming). One additional that I really liked is the LTS model which is a proven model. My only concern is the 6 month stable release cycle though. 

RH and Ubuntu (picking these two since they have been doing this successfully) have 2-3 years between stable releases. However, they do have six monthly interim releases which include features that, when relevant, will be back-ported to the major release.

OpenStack tried the six month stable release to not so great results, especially when it came to vendors building enterprise supported versions off of it. The same challenge of having to patch every stable release was one of the major challenges.

An additonal input is around the "safe harbor release" which is the last release we will back-port our changes to. For example, once 22.04 comes out, Ubuntu does not have to back-port to 18.04 and will only conditionally to 20.04 back-ports (or some such). This will also help us from having to go way back.

**Comment by arunuke** [comment]
Minor correction on the k8s release cadence : The k8s community has now [switched](https://kubernetes.io/blog/2021/07/20/new-kubernetes-release-cadence/) to a three-releases-per-year model with clearly identified weeks when a release will be cut and specifically allowing for holidays and kubecon and other events.

**Comment by hcgatewood** [comment]
@PARitter any updates on this proposal?

cc @talkhasib and @markjen for whether this is still a priority

**Comment by hcgatewood** [comment]
@PARitter let's plan to either have a presentation on updates to this proposal at the Nov 1 TSC meeting, or mark it as currently abandoned. Lmk your thoughts!

http://bit.ly/MagmaPublicCalendar
