### ISSUE TITLE
[NMS] Simpler NMS initial setup for organizations and users

### ISSUE THREAD

**Issue by andreilee** [magma/magma#8890]
### Summary
Initial setup on the NMS is difficult to understand from a user perspective. The quickest gap to bridge here is making "empty states" easier to understand - when no organization has been created, when no user has been created, or network. Such states are difficult to understand currently, and there are missing CTAs for the NMS user in these states.

### Reference Links
[1-Pager](https://docs.google.com/document/d/1NQ3inn0zn9cxhnejJkq5c_iuaRax75vBZX0rZzrOsog/edit?usp=sharing)
[Final Mockup](https://www.figma.com/file/EUkpGE9qCh7k8XeNc4xLkT/?node-id=176%3A6473)

### Design Proposal

- Add tutorial flags to guide the user through the onboarding steps
- Add instructional description about multi-tenancy concepts
- Change terminologies (Master Portal -> Host Portal; Master Organization -> Host Organization; Users -> Host Users)
- Show user lists for the organizations on the host portal

**Comment by jingtien** [comment]
**P2**
Marking as P2 because we think we're focusing on existing users more in Magma, but we're not sure

**Reach**
High, any new Magma user, but we don't know how many new users setup up Magma at any given time 

**Impact**
New users: Fewer support tickets, more users to complete the setup process when evaluating it as a solution.  These new users may not even be reaching out to us when they have a problem.  Existing users: Not as affected

**Confidence level**
Med-High, but we're not sure

**Eng effort**
1-2 weeks for empty states + links to other platforms, ~3-4 weeks for larger redesign

**Comment by jingtien** [comment]
Next steps
- Explore the [Main platform](https://master.nms-staging.magma.etagecom.io/master/organizations)
- Find from Andrei, figure out the difference between Admin and tenant
- List out all issues around adding an organization and user
- Scope out project
