### ISSUE TITLE
Extension to Orc8r SubscriberDB

### ISSUE THREAD

**Issue by anusha-konda** [magma/magma#8904]
# Extension to Orc8r SubscriberDB
## Problem

UE doesn't have access restrictions to "EPC" or "5GC" network currently. 
This proposal is to extend below support for 5G subscribers, 
 1. Enabling options for operators, to map subscribers to the respective network type.

## Solution

CoreNetwork Type restriction is enabled during subscriber addition, defining the access restrictions. AMF/MME validates the details from SubscriberDB and take an action for NAS signaling procedures.

## Non-goals

This proposal only includes the detailed changes in Orc8r.  AGW changes are not specified in this proposal, it is referenced wherever required.

[Design doc](https://docs.google.com/document/d/1V7wK5OxVxv9fmDiF1_6IbCXr5hnyLDT0/edit)

**Comment by hcgatewood** [comment]
Hi @anusha-konda! Thanks for opening this. Based on the design doc, I don't think this type of change needs to be a proposal -- since it doesn't need top-down community alignment or blessing

Instead, for forward-compatible changes such as this, feel free to work directly with the relevant tech lead (@ulaskozat or @uri200, for example) on the shape of the change, then put up a draft PR and I can give you more actionable Orc8r-related feedback

Let me know if you have any questions, happy to answer here or have a quick chat 🙂

**Comment by anusha-konda** [comment]
> Hi @anusha-konda! Thanks for opening this. Based on the design doc, I don't think this type of change needs to be a proposal -- since it doesn't need top-down community alignment or blessing
> 
> Instead, for forward-compatible changes such as this, feel free to work directly with the relevant tech lead (@ulaskozat or @uri200, for example) on the shape of the change, then put up a draft PR and I can give you more actionable Orc8r-related feedback
> 
> Let me know if you have any questions, happy to answer here or have a quick chat 🙂

Hi @hcgatewood . can close the PR as said by you. Anyways PR 9161 (Orc8r changes) and PR 9165 (NMS Changes) are under review by Andrei Lee.
