### ISSUE TITLE
feat(orc8r): reconcile secondary indexes with state 

### ISSUE THREAD

**Issue by uri200** [magma/magma#8925]
(more about [state indexers here](https://docs.magmacore.org/docs/next/orc8r/dev_indexers#state-indexers))

Right now, when we add an new state on ocr8r, some of the services create a secondary indexes out of that state. For example orcr8r service has a secondary index that creates teid-hwid index out of this state record.

For example, right now we have almost 3M orphan indexes on our staging deployment

```
magma=> SELECT count(*) FROM directoryd_blobstore WHERE type='sessionid_to_imsi';
  count
---------
 2872606
```

```
magma=> SELECT count(*) FROM directoryd_blobstore WHERE type='sgwCteid_to_hwid';
 count
-------
  2977
```

When we delete a state we never delete the associated secondary index. That causes stale indexes to exist on our database forever. 

Reconcile the indexes would allow us to use state and secondary indexes for centralization purposes like providing unique IDs: for example,  TEID-hwid secondary index could be use to know if that TEID is being used by any AGW in the network. 

**Possible solutions**

Right now indexers implement `Index` which creates secondary index out of a state request. Those indexers are triggered when we run `ReportStates` at state service [here](https://sourcegraph.com/github.com/uri200/magma/-/blob/orc8r/cloud/go/services/state/servicers/servicer.go?utm_product_name=IntelliJ+IDEA&utm_product_version=IntelliJ+IDEA#L104:27). An example of what that index do can be seen [here](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Auri200%2Fmagma.git&branch=master&file=orc8r%2Fcloud%2Fgo%2Fservices%2Forchestrator%2Fservicers%2Findexer_servicer.go&editor=JetBrains&version=v1.2.1&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2.2&start_row=66&start_col=31&end_row=66&end_col=31). In this case, the Index creates two secondary indexes (`sgw_c_teid` and `session_id`) on `directoryd_blobstore` table. 

The purpose solution is to do the same when we run `DeleteStates` at state service. To do that we will need to implement a `de-indexer` on the secondary triggered `DeleteStates` [(here)](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Auri200%2Fmagma.git&branch=master&file=orc8r%2Fcloud%2Fgo%2Fservices%2Fstate%2Fservicers%2Fservicer.go&editor=JetBrains&version=v1.2.1&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2.2&start_row=108&start_col=32&end_row=108&end_col=32) request.  

That `de-index` function will have to remove whatever the `index` function did.

Note that `DeleteStatesRequest` only includes the keys to find the state. But not its content. The `de-indexer` will need to parse the content to know what key they have to delete. However, not all indexes will implement `de-index`. That means each `DeleteStatesRequest` will force us to read the entire record and pass it to the de-indexer. We can try to find some ways to optimize this.

Some data from staging: we currently have 3M index left behind that are only deleatable by hand accessing to the database.

**Comment by hcgatewood** [comment]
Here's the todo for this: https://github.com/magma/magma/blob/c2a53b10cc00d5a4eb9339f7a011c8b4fe607956/orc8r/cloud/go/services/state/indexer/indexer.go#L60-L62

We haven't gotten around to it because (a) this problem can usually be solved another way (see below), and (b) gateways currently almost never use the "delete state" functionality (as far as I can tell), and (c) state indexers are meant to be / implemented as "best effort" anyway -- whereas adding `IndexRemove` support would start treating secondary state as "reliable" rather than best effort

Here's what we end up doing right now for reverse maps:

- Say e.g. primary state is `sid -> teid`
- Indexer creates the reverse map, on a best-effort basis, as `teid -> sid`
- Some other process consumes the reverse map in 2 steps
    1. Start with teid, use the `teid -> sid` reverse map to get sid
    2. Check the original map (`sid -> teid`) with the found sid to determine whether the found sid is still valid according to the state service

Using this pattern allows indexers to remain best-effort, while still consuming their output with high confidence

If you believe this pattern is insufficient for certain use-cases, please provide additional information on how it's insufficient and we can work forward from there 🙂 

cc @uri200 @electronjoe

**Comment by uri200** [comment]
Hey @hcgatewood the first comment of issue has a description of the need, but as a summary: Core networks see magma as a single entity (either sgw or pgw) that requires some identifiers (like teid) to be unique across different AGW. Right now AGW assign those identifiers randomly which may cause collisions between subscribers on different AGW. Having a reliable index will allow us to pick an available identifier.

Note there are other benefits of reliable indexing like index not growing infinitely, or reliable reverse look up for the FEG

So a possible solution is to create reverse functions (`de-indexer`) that remove the data when a record is set to be deleted

**Comment by ekowtaylor** [comment]
@uri200 story points required https://app.zenhub.com/workspaces/magma-5fac75d3e2cd890011f1677a/issues/magma/magma/8925

**Comment by hcgatewood** [comment]
@uri200 I'm happy to have a 1-1 if you want to deep dive into this. Like I mentioned I think adding this functionality will have a strong negative externality. It may be worth accepting that externality, but I'd love to go through our other options before committing to it

**Comment by uri200** [comment]
Hey @hcgatewood, in the benefit of time, can you please leave a brief description of that externality you see so I can factor in your suggestions before our meeting

**Comment by hcgatewood** [comment]
@uri200 the specific issue is state indexing is inherently an edge-triggered event. And we don't provide infra to make this reliable (e.g. Kafka) because that infra is too expensive and too complex for e.g. a VAR to operate

So while state *reporting* is level-triggered, state *indexing* is "best effort" -- consider, e.g., if the Orc8r state service crashes while trying to send a piece of state off for state indexing. The state would be properly reported, but not properly indexed. This is one of the assorted reasons why a reliable edge-triggered architecture is non-trivial

So that said, the content of this proposal in effect is trying to bring the derived state into exact parity with the reported state, but only via non-reliable edge-triggered events. This will work fine in the common case, but it's providing an affordance we can't live up to: it will inevitably cause hard-to-rc e2e bugs.

So to me, I'm wanting to discuss whether there are better alternatives before committing to adding this inherently buggy affordance to the Orc8r

Let me know if that makes sense, happy to discuss more!

**Comment by uri200** [comment]
Hey @hcgatewood, thanks for your comments.

This is simpler than it seems. Removing the index has the same risks and complexity than adding indexes, action we already do. In fact, not removing indexes causes the table to grow indefinitely. Note we just need an eventual consistent system on deletes (no matter if index are a little bit obsolete, but just a bit, not forever)

The amount of reliability is the same as we provide right now: we currently rely on those index so feg can find serving AGW. So this feature will be based on the same concepts we used for other features we already have.

On e2e issues LTE/5g protocol plays on our advantage: if some index is missing the request will fail and  UE will timeout. A new Attach will be triggered a new index will be generated. Obviously a drop call is not optimal, but that will not happen constantly and the system will self heal.

As you mentioned, let me set up a call. But if you have a chance, take a look at this [document](https://docs.google.com/document/d/1TwHFv9nWW4cArZA5e6P6ik60NxAB75KK7SOFamEpD5s/edit#heading=h.czv0vpn4mw66) where you can see other solutions we described (including this one labeled as solution 3). You can also comment there so the rest of the team can provide their input

**Comment by hcgatewood** [comment]
@uri200 I agree this won't be catastrophic to implement, by any means. However, I disagree that this proposal won't make things worse. If desired I can enumerate more of the ways 🙂 

So anyways: yes, we could implement it this way and things would probably function correctly 99 to 99.9% of the time *for this feature*. The problem is, once we introduce this affordance, it will get used more in the future, and particularly by devs who don't know or understand the lack of reliability. So as it gets used more, let's call it 99.7% correctness across 7 use-cases => .997^7 = .98 => before we had 1 in 330 iterations caused an issue but now we have 1 in 50. Or even 99.9% across 9 use-cases is 1 in 1000 becomes 1 in 100.

(Also, adding this affordance increases the complexity of the state + indexing functionality, making it harder for devs to reason about the state of the system.)

So maybe the misalignment here is at a higher level -- are we building Magma to be a quick-to-market feature-oriented system, or a stable platform? The recent Magma vision documents seem to point to the latter

What I'm arguing is yes, we *could* do it this way, but we're introducing affordances to the platform that are inherently buggy. 

To me, it feels clear Magma's vision includes a stable platform. And to me, that means not adding platform affordances with bugs baked in

We can chat more during 1-1. Maybe centralized teid management is also a bad idea (?), but for now, it feels much more attractive to me given that it doesn't require introducing additional platform-layer bugs

**Comment by uri200** [comment]
Hey @hcgatewood thanks for the inputs. 

After our call we discussed that we should also consider the option of creating a `pruning` function that would run periodically removing indexes from states that are not existing, instead of extending the interface to de-index. That would allow us to reach eventual consistency on the indexes. To do so, we may need to add a new column to the indexers to store the main key of the record that was used to create that entry in the index

[here](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Auri200%2Fmagma.git&branch=feg_merge_credit_reports_into_single_crru&file=orc8r%2Fcloud%2Fgo%2Fservices%2Forchestrator%2Fservicers%2Findexer_servicer.go&editor=JetBrains&version=v1.2.1&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2.2&start_row=125&start_col=26&end_row=125&end_col=26) you have where Orc8r indexes teids. Note that orc8r was already indexing sessionID so teid indexing was added similarly to sessionID. 

I will add some concerns I may have about pruning function on next messages.

**Comment by hcgatewood** [comment]
@uri200 following up on the pruning mechanism based on your pointer to the existing TEID functionality

- The primary state is `{type: "directory_record", key: imsi} -> directory_record`, where the directory record includes both the teids and hwid
- The secondary state is currently `teid -> hwid`
- So we can prune the secondary state if we include the imsi in the stored secondary state -- i.e. secondary state becomes `teid -> {hwid, imsi}`
- Side note: this will require updating the indexer, and therefore its version, which will trigger a reindex

This way, the cronjob can perform the following

1. Read in all teid secondary state
2. Check the primary state (based on the imsi of each piece of secondary state) and determine whether that secondary state is stale
3. If stale, delete the secondary state

We'll also have to

1. Update AGW to properly update/delete directory records when they're done with their relevant teid
2. Accept that some teids will be "forever" claimed, since e.g. AGWs can be decommissioned before they're able to communicate to the Orc8r that their teids are deallocated

As discussed, if we're going to use the state service for this piece of functionality, the pruning mechanism allows us to (a) preserve a level-triggered solution to staleness (rather than edge-triggered), and (b) preserve the relative low-complexity of the existing state indexing solution. For these reasons, I'm more attracted to the pruning-based solution than the `IndexRemove` solution, though I agree both will work in the common case

As a final word, I am interested to explore what centralized teid management would look like, since it feels we're using the state service as a bit of a go-between to simulate direct AGW<>Orc8r communication. But I'll let you make the final call, since it definitely seems like utilizing the state service would be the quicker way to build out this feature 🙂 

Let me know when you're ready to have the followup chat, if needed, to work through more specifics together!

**Comment by uri200** [comment]
Hey @hcgatewood thanks for the comments

>As a final word, I am interested to explore what centralized teid management would look like, since it feels we're using the state service as a bit of a go-between to simulate direct AGW<>Orc8r communication

In reference to your last comment: yes we are kind of using state as a communication mechanism. In fact I think someday we will have to refactor/redesign state to be a solid way to share states. Due to federated nature, orc8r will need to know some states (specially if we ever add mobility between AGW). Let's worry about this in the future.

>This way, the cronjob can perform the following...

The concerns I have with the purposed solution is that it only works for teids and it would have to be customized for any other index. Also the logic needs knowledge of primary and secondary state in one single object (we currently divide this logic into state and indexer).

To me the risks of a event trigger system are:
- Orc8r can crash during a request and the record could be added but not the index (that would cause a reattach and solve the issue)
- Orc8r database is hit more often (that is alleviated with garbage collector at AGW State client which send batched delete request every 60s)

--------------------------------------------

Note the idea is to design this as a wide feature for indexers, not just teid (we also have maps with HWid-SessionID that would benefit of a way to maintain true indexes). So I am tackling this dividing the issue into two:

1. What object is the owner of the deletion code
2. How we trigger the deletion (either level or event)

1- Owner of the code
Currently state code do not know anything about the implementation of the indexes. The code that deletes an index should be in the same object that added that index. So we should put the code into the Indexer. 

That means we would have to extend Indexer interface to include `DeIndex`. That new functional will take and return same parameters as `Index`
```
  rpc DeIndex(IndexRequest) returns (IndexResponse) {}
```

Once we have a function that knows how to remove an entry we just need to do: 
- State client at AGW will send a `DeleteStatesRequest` with `type` and `deviceID`
- State at orc8r will receive that `DeleteSateRequest and query for a record on states table matching those parameters
- State at orc8r will have to convert the query result query into `IndexRequest` object
- State at orc8r will go over all the indexers and apply `DeIndex(IndexRequest)`.
- Orc8r service will receive the `DeIndex` request and delete the TEID based on IndexRequest

Note we do not have to implement that `dDeIndex` in all Indexer. For now we just need `DeIndex` for teids.

2- Trigger of the Deletion 
Level and Event triggers have their pros and cons. In my opinion, if we want a perfect solution we will have to implement both, event and level: event to provide immediate consistency and level to make sure we do not have stale teids.

Right now we are already sending `DeleteStatesRequest` when we delete a record from AGW (see below). So the easier solution for now is to use even trigger since it is given for free.
```
Oct 04 20:14:54 ubuntuAGW state[2712389]:   magma.orc8r.DeleteStatesRequest {
Oct 04 20:14:54 ubuntuAGW state[2712389]:     "ids": [
Oct 04 20:14:54 ubuntuAGW state[2712389]:       {
Oct 04 20:14:54 ubuntuAGW state[2712389]:         "type": "directory_record",
Oct 04 20:14:54 ubuntuAGW state[2712389]:         "deviceID": "IMSI999991234567810"
Oct 04 20:14:54 ubuntuAGW state[2712389]:       }
Oct 04 20:14:54 ubuntuAGW state[2712389]:     ]
Oct 04 20:14:54 ubuntuAGW state[2712389]:   }
Oct 04 20:14:54 ubuntuAGW state[2712389]: INFO:root:GRPC message:
```


Some side notes to improve state service and its records:

- Can you confirm that `deviceID` on the [proto](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Amagma%2Fmagma.git&branch=master&file=orc8r%2Fprotos%2Fservice303.proto&editor=JetBrains&version=v1.2.1&utm_product_name=IntelliJ+IDEA&utm_product_version=2021.2.2&start_row=96&start_col=22&end_row=96&end_col=22) is stored as the key on the states table?
```
magma=> \d+ states
                               Table "public.states"
   Column   |  Type   |     Modifiers      | Storage  | Stats target | Description
------------+---------+--------------------+----------+--------------+-------------
 network_id | text    | not null           | extended |              |
 type       | text    | not null           | extended |              |
 key        | text    | not null           | extended |              |
 value      | bytea   |                    | extended |              |
 version    | integer | not null default 0 | plain    |              |
Indexes:
    "states_pkey" PRIMARY KEY, btree (network_id, type, key)
```

- An interesting thing to explore would be to see if there is a way in postgre to see the time the entry was created on the database. I not, it would be good to add timestamp to the record the time it is first received and last updated. That would allow us to create a simple garbage collector where entries older than X and not updated in Y should be removed.

**Comment by hcgatewood** [comment]
@uri200 the concern I have with adding `DeIndex` is the capacity for an edge-triggered system to get out of sync

You correctly identify that this is not an issue for the teid use-case (correctness is preserved -- we'll just end up with a permanently-allocated teid, which is not a big deal in a uint32 id space). However, my concern is that this new functionality will be utilized by other indexers, a subset of which would understandably not handle this failure as gracefully

To add to this: consider an example (domain-agnostic -- so not teids) indexer use-case where there's a failure to index (or deindex), and we need to manually intervene. Under indexers+pruning, the solution is to use the existing cli to manually kick off a reindex. Under indexers+deindex, there's no domain-agnostic solution -- a dev would have to connect to the db and fix the problem, by hand, for every defined state indexer that cares about correctness. And that list isn't restricted to just the indexers the core team writes -- anyone who [extends Orc8r](https://magma.github.io/magma/docs/next/orc8r/architecture_modularity#supported-extensions) with their own state indexers would need to specifically understand how to escape this bad edge-triggered situation on a per-indexer basis

This is the main concern I have with the indexer+deindex approach: it's unclear to me there's a "safe" way to implement this edge-triggered solution that works for all indexers -- unless we introduce e.g. kafka. Because yes it's safe for teids (from a correctness perspective), but it's not necessarily safe for all other indexers

---

On the topic of code locality / logical ownership: I agree it makes sense to co-locate all indexer-related code for a particular use-case. I also think we can achieve that with either indexers+deindex or indexers+pruning.

Currently, secondary state is managed by a dedicated dao -- e.g. [`DirectoryLookupServicer`](https://github.com/magma/magma/blob/13b485a9b6da5874761919c840e4c0a8be81641d/orc8r/cloud/go/services/directoryd/servicers/servicer.go#L29-L32) for teids. To me, it's reasonable to co-locate all of the following with that dao

1. The dao operations (for teids: map that teid)
2. The pruning function / spinning up the goroutine (for teids: deallocate stale teids)
3. The actual index function (for teids: extract teid and make the over-the-network request to the dao)

I think that is one option for how we could co-locate the logic for the full indexing lifecycle on a per-use-case basis

On the topic of code reuse: I think the actual pruning goroutine will be only a few lines of code (for e.g. reverse maps), so I'm not super worried about that, but lmk if you feel differently

---

As for which architecture choice we should pursue, I think there are 2 axes that we care about: correctness and developer effort. To me, the breakdown is as follows

- Centralized teid management: high correctness, high developer effort
- Indexers+pruning: high correctness, low developer effort
- Indexers+deindex: medium correctness, low developer effort

To me, since both indexers+pruning and indexers+deindex are low developer effort, my current preference is indexers+pruning since it (a) doesn't decrease the correctness and (b) we retain the capacity to, in a domain-agnostic way, escape an indexing failure

Side note: for the timestamp-based garbage collection you describe, I think the best way to implement that would be with the indexers+pruning option, where the timestamp-based garbage collection is implemented within the pruning goroutine. Lmk if you had a different idea though!

Let me know if you want to chat more about it -- I'd be down for a 1-1 deep dive to move through concerns more synchronously, if interested!

**Comment by electronjoe** [comment]
From the detailed back and forth above - it seems that this goal By @uri200:

> The concerns I have with the purposed solution is that it only works for teids and it would have to be customized for any other index. 

Cannot be met by the current state synchronization system:

> However, my concern is that this new functionality will be utilized by other indexers, a subset of which would understandably not handle this failure as gracefully.

It seems to me that a larger re-planning / careful thought / design document is needed to cover the general case and plan work packages around it, so from what I'm reading I would advocate we take the `cron prune` approach that @hcgatewood  is proposing as it does not mislead future developers as to the present capabilities of our state dissemination system.

**Comment by markjen** [comment]
I'm in favor of letting @uri200 go ahead with this proposed functionality mostly because it's better than what we currently have:

1. with no index cleanup functionality, indexes continually grow.
2. a `cron prune` could also work, but 
2.

**Comment by markjen** [comment]
oops, ignore my accidental close/re-open

Do we want index + deindex + cron reindex + cron prune?

Currently, indexes are also not guaranteed to be there, so index/deindex would be faster and mostly correct; cron reindex/prune would fixup any missed index/deindexes.

If so, should we let @uri200 continue with deindex and we'll track these crons in a separate issue? 

Also I noticed #6720, which looks to be in the same area as this work

**Comment by uri200** [comment]
reassigned to @uri200 to track all the issues that I need to code

**Comment by uri200** [comment]
Hey @markjen, probably to make state service reliable we will need to implement all the different options defined here:

- `IndexRemove` (instead of `DeIndex`) will be used by any of the options here defined to remove Indexes.
- DeleteState will be event that will trigger deletion of state and propagate the canges to the indexes using `IndexRemove`. This event based feature is immediate available (we already send some DeleteState messages) and will provide a 
- Cron job will allow us to implement some kind of garbage collection to be triggered periodically to collect old states (and propagate the changes to the indexes using IndexRemove)

I will create more issues to capture the changes on State service to enhance its content reliability and availability. Those changes should be considered a tangential effort from unique TEID feature. TEID feature will work either with or without those changes.

**Comment by markjen** [comment]
> Hey @markjen, probably to make state service reliable we will need to implement all the different options defined here:

Just to be clear and for posterity: there is no (easy) way to make this "reliable", but if we employ the proposed updates and cleanup crons we can do a better effort than what's there today.

**Comment by hcgatewood** [comment]
Closing as accepted!

**Comment by uri200** [comment]
reopening to be able to track this on our zenhub epic.

![image](https://user-images.githubusercontent.com/16157139/137808962-33d51203-ac48-4c79-a993-ef0f71163b34.png)

More discussions about proposal procedure can be seen here
https://magmacore.slack.com/archives/C01Q1T14YJ2/p1634591786031000
