### ISSUE TITLE
Magma 5G SA | TeraVM | Intermittently found no response for "PDU Session Establish request" 

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#9122]
Test Scenario/issue: 
1, SUCI based Registration is successful
2, on UL_NAS received "PDU Session Establish Request" & 4 retries, **AGW not responded for all of the retries**.

Expectation: 
AGW (SMF) Responds back & proceed with  "PDU Session Resource Setup request " 

Tested Build:
1.7.0-1631744238-11c8c453
Previous Build where this TC passed:
1.7.0-1631657885-04dafde7

TeraVm 5G SA Test case:
TC2 UE Initiated PDU Session Establishment with traffic test
TC7a Verify “PDU session establishment” after Service Request – Signaling & Service Accept

Logs Enclosed: mme log, syslog & pcap
[pdu session est retry failure_1.zip](https://github.com/magma/magma/files/7176132/pdu.session.est.retry.failure_1.zip)

Snap of the Issues Traces
<img width="1591" alt="Screen Shot 2021-09-16 at 12 40 15 AM" src="https://user-images.githubusercontent.com/70725754/133577115-d6dc62c5-4e85-4e90-944a-5fb103369f63.png">

**Comment by GANESH-WAVELABS** [comment]
Hi Arun,

From the provided syslog I could see it is duplicate request of same PDU_ID and IMSI combination. Please find the below logs snippet.
Sep 16 00:15:19 TVM3-SA sessiond[1640923]: I0916 00:15:19.850277 1640923 SetMessageManagerHandler.cpp:118] Requested session from UE with IMSI: 222456000000201 PDU ID 5\
Sep 16 00:15:19 TVM3-SA sessiond[1640923]: I0916 00:15:19.850319 1640923 SetMessageManagerHandler.cpp:237] Duplicate request of same PDU_id 5 of IMSI 222456000000201 nothing to do\

![image](https://user-images.githubusercontent.com/70899516/133593085-d65260ca-a4a0-4c92-bf55-80c9dd403144.png)

Below is the small description of current master code for magma sessiond:
/* If it is new session to be created, check for same PDU_ID exists
   * for same IMSI, i.e if IMSI found and respective PDU_ID found in
   * SessionStore, then return from here and nothing to do
   * as already same session exist, its duplicate request
   */

So, this is expected behavior with respect to current sessiond code. Please let me know if any other information is needed.
   
Thanks & Regards,
Ganesh Irrinki

**Comment by arun-magma** [comment]
@GANESH-WAVELABS @ulaskozat @panyogesh 
As we discussed in sync up call "Duplicate PDU_ID & IMSI" combination need to be handled by AGW refreshing probably earlier pdu session or return a Reject, As same issue repeats in SIT environment we may need to prioritize it. 
In this ticket related tracing we can see its the first PDU Establish request with PDU_ID = 5, which is the correct pdu_id from access side and due to some earlier hanging PDU session this request is considered as duplicate in AGW and no response is returned.

**Comment by GANESH-WAVELABS** [comment]
Hi Arun,
Could you please provide the steps & test case sequences to reproduce this scenario.

**Comment by arun-magma** [comment]
Hi @GANESH-WAVELABS : Currently this issue is repeatedly found in "SA_TC9_AMF_Initiated_Paging" in TeraVM emulation.
This is also a script name. You can access TeraVM & run TC9 to get this scenario 
[SA_TC9_AMF_Initiated_Paging_210922_233544-1.pcapng.zip](https://github.com/magma/magma/files/7215427/SA_TC9_AMF_Initiated_Paging_210922_233544-1.pcapng.zip)

**Comment by GANESH-WAVELABS** [comment]
[07-October-2021 : Ganesh . I] : This issue can be tracked with GitHub issue : https://github.com/magma/magma/issues/9373

So closing this Task.
