### ISSUE TITLE
[AGW] Static IP allocation for SGi when AGW in non-nat / static IP allocation mode

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#9309]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.6
- **Affected Component:** AGW
- **Affected Subcomponent:** IP Addressing
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

AGW uses `uplink_br0` as the SGi interface. However when the gateway is in non-NAT mode, the interface configuration on the gateway is for `eth0` and `eth1` respectively. If an IP address is not specified from the orc8r, it's possible that the gateway upon some process restart / reboot may loose SGi IP address entirely. 

**Expected behavior**
* If a gateway is non-nat mode and values in gateway.mconfig are not set for the SGi interface, static addresses specified in /etc/network/interfaces.d/eth0 should be used for uplink_br0. 

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by smiladi** [comment]
This issue has a serious consequence for companies selling AGWs to multiple customers:
- AGW is installed before being shipped to the customer
- Production team leaves SGi to DHCP (some customers prefer DHCP and some prefer static addresses)
- As part of the product verification, the unit is connected to the ORC8R
- In the field, customer changes SGi from DHCP to the static IP address - and the AGW ignores it completely
- End result is unhappy customer calling customer support, and customer support deleting /var/opt/magma/configs/gateway.mconfig 

Yes, there is a workaround (delete /var/opt/magma/configs/gateway.mconfig), but performing allowed operation (changing SGi IP from DHCP to static) should not a result in a critical issue. This is not a corner case as many WISPs prefer AGW in routed mode with 2 APNs (one APN for CPE management, the other for user data) and significant portion of those choose static IP address on SGi.

**Comment by pshelar** [comment]
Changing SGi IP from DHCP to static is allowed using NMS/orc8r. But you need to restart AGW after such a change.

**Comment by smiladi** [comment]
We had an issue where if the eth0 is configured for DHCP and SGi mgmt IP is pushed from the ORC8R, once the AGW is restarted in an environment without DHCP server it will not be reachable on the SGi (although if you SSH via S1, you can see that the IP address pushed by ORC8R is on uplink_br0).	

But even if that worked, the whole point is that operator does not want to use DHCP. And we are now telling them: you need to use DHCP (to reach the ORC8R) so that ORC8R can tell AGW that it should NOT use DHCP :). I would argue it is also not consistent: operator will have to SSH to the box to change S1 interface IP address from default 10.0.2.1, and potentially set static routes if the S1 and ENB are not on the same subnet. It would be logical that while they are editing the eth1 file, they also edit the eth0 file and set SGi interface accordingly.

Finally, the solution where connectivity to the ORC8R depends on configuration pushed from the ORC8R has inherent problem: if AGW in the field loses access to the ORC8R, you are stuck - any change on the ORC8R will not reach the AGW, and there is no easy way to solve the problem on the AGW itself (deleting /var/opt/magma/configs/gateway.mconfig is not something that field tech would know). One possible scenario: SGi IP address is incorrectly set on the ORC8R before AGW is shipped to the field. There is no DHCP in the field and the IP address scheme does not match... AGW has to be sent back to the office.

**Comment by pshelar** [comment]
> We had an issue where if the eth0 is configured for DHCP and SGi mgmt IP is pushed from the ORC8R, once the AGW is restarted in an environment without DHCP server it will not be reachable on the SGi (although if you SSH via S1, you can see that the IP address pushed by ORC8R is on uplink_br0).
> 
This looks like a bug. we need to debug it.

what are flows on uplink_br0, what is linux routing table?

> But even if that worked, the whole point is that operator does not want to use DHCP. And we are now telling them: you need to use DHCP (to reach the ORC8R) so that ORC8R can tell AGW that it should NOT use DHCP :). I would argue it is also not consistent: operator will have to SSH to the box to change S1 interface IP address from default 10.0.2.1, and potentially set static routes if the S1 and ENB are not on the same subnet. It would be logical that while they are editing the eth1 file, they also edit the eth0 file and set SGi interface accordingly.
> 
> Finally, the solution where connectivity to the ORC8R depends on configuration pushed from the ORC8R has inherent problem: if AGW in the field loses access to the ORC8R, you are stuck - any change on the ORC8R will not reach the AGW, and there is no easy way to solve the problem on the AGW itself (deleting /var/opt/magma/configs/gateway.mconfig is not something that field tech would know). One possible scenario: SGi IP address is incorrectly set on the ORC8R before AGW is shipped to the field. There is no DHCP in the field and the IP address scheme does not match... AGW has to be sent back to the office.
