### ISSUE TITLE
GTP-U Path management

### ISSUE THREAD

**Issue by sarathbrp** [magma/magma#94]
This issue is due to the missing path management feature in EPC. 

Ruckus enodeb supports S1-U path management. 

The scenario is while UL/DL traffic ongoing enodeb releases S1 considering the path management failed and starts the failure recovery process. 

UE is Sercomm LTE Band 48 dongle/Essential PH1 band43 phone
enodeb: Ruckus 43/48 

This can be easily reproducible if GTP-U path management is enabled on enodeb. Please let me know if you need more information to reproduce this problem.

Thanks,
SP

**Comment by anooptomar29** [comment]
we know the issue and solution also. It is happening since we dont respond to GTP-U echo request and after 5 retries ( approx 300 seconds) eNB declares path as failed path and releases the UE context and UE moves to idle state. After that all the initial context setup fails because eNB has declared this path as failed. Workaround can be to disable path management in eNB and final solution is to add support for echo response in AGW/SGW.

**Comment by ghost** [comment]
Is it possible to raise the priority of this issue? A fix would be highly appreciated.

**Comment by ekowtaylor** [comment]
Stale
