### ISSUE TITLE
S1AP Error Indication - Correct the Log

### ISSUE THREAD

**Issue by sarathbrp** [magma/magma#95]
looks like S1AP error indication feature is not supported. I appreciate if you let me know the timeline to implement this feature. 

Thanks,
SP

**Comment by anooptomar29** [comment]
@sarathbrp For most of the scenarios error indication-does not require any action from receiving entity and for such scenarios AGW logs that error indication is received and that is appropriate handing. For e.g. if MME sends UE context release request with enb_s1ap_ue_id which is already released by eNB ( and this can happen due to cross over of few S1AP procedures) in this eNB would send error indiction with cause "unknown enb_s1ap_ue_id and MME does not need to take any action for this and thats what we do , we log it in AGW.

**Comment by anooptomar29** [comment]
If you have observed any specific case where-in AGW should have to handled error indication please let us know or please share the logs/pcap.

**Comment by anooptomar29** [comment]
I think we should close this issue. I guess log "ERROR IND NOT SUPPORTED" is misleading , we will fix the log.

**Comment by ssanadhya** [comment]
Resolved with 363eca185bd69309fe4e80be7ddc954a1ed52015
