### ISSUE TITLE
[4G Regression | Teravm] Attach Reject due to Network Failure

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#9674]
In some of the TeraVM test cases we see Attach Reject Due to Network Failure, Here is one of the instance observation

Scenario: 
1, Federated Mode 4G Attach with S6a, Gx and Gy flows expected.
2, UE sends Attach Request.
3, {Issue] S6a AIR/AIA flow Fails and we see below snap of errors.
4, AGW sends Attach Reject due to Network Failure.

Key suspect is Feg Relay GRPC calls for S6a AIR/AIA during Network Failure.

Expectation:  S6a AIR/AIA flow should be okay and S1 Auth process should continue with UE.

Tested Build:  1.6.1-1634100297-71f9bccc

During Network Failure below are the observations in AGW's mme , syslogs, pcap snap.
"Time stamp:  06:37:49" is connecting all these logs

[Syslog] - HTTP - 502 on S6a_Proxy
<img width="1540" alt="Screen Shot 2021-10-13 at 2 23 14 PM" src="https://user-images.githubusercontent.com/70725754/137248458-83ab2090-b08f-407f-bac7-0526648d3f24.png">

[mmelog] - Auth Failure
<img width="1602" alt="Screen Shot 2021-10-13 at 9 05 22 PM" src="https://user-images.githubusercontent.com/70725754/137250075-20b0c260-72d7-411f-b6bb-29b395da3118.png">

[3gpp Pcap] - No S6a - Diameter Message and Finding HTTP-502

**Comment by arun-magma** [comment]
Enclosing here all the logs
[sysLog_211012.txt.zip](https://github.com/magma/magma/files/7342980/sysLog_211012.txt.zip)
[mmeLog_211012.txt.zip](https://github.com/magma/magma/files/7342982/mmeLog_211012.txt.zip)
[authentication_information_06_211012_063747-1.pcapng.zip](https://github.com/magma/magma/files/7342984/authentication_information_06_211012_063747-1.pcapng.zip)

**Comment by arun-magma** [comment]
In another Instance S6a AIR & AIA is found but no S1 Auth flow and Attach Reject - Network Failure
[authentication_information_30_211013_115432-1.pcapng.zip](https://github.com/magma/magma/files/7343022/authentication_information_30_211013_115432-1.pcapng.zip)


<img width="1660" alt="Screen Shot 2021-10-13 at 9 26 44 PM" src="https://user-images.githubusercontent.com/70725754/137252081-c84d841b-91cb-4644-be04-b84306d55f49.png">

**Comment by blueCARDSS** [comment]
we have similar problem ...
![image_2021_10_28T11_09_29_582Z](https://user-images.githubusercontent.com/92744847/139498671-423f7db8-1b52-4951-9547-673de4d0bee2.png)
![image_2021_10_28T11_09_11_677Z (1)](https://user-images.githubusercontent.com/92744847/139498676-9aa387b1-b39b-4988-b929-dd164774e5a3.png)

**Comment by Chandrashrathore** [comment]
I am also facing the same problem in my setup. I configured Sigscale OCS with Magma FeGW.
When UE will be send InitialUEMessage, Attach request message to MME then 
MME giving response Attach reject message  (Network failure). I debug this Network Failure & in this Attach reject message (Network Failure). I saw the MME logs and I found It show Attach reject message (cause #17).
Cause #17 =  Network failure This EMM cause is sent to the UE if the MME cannot service an UE generated request because of PLMN failures.
I verified the PLMN is both side AGW and SigScale OCS but PLMN value configured is same.

PFA pcap screenshot & MME logs for reference.

![image](https://user-images.githubusercontent.com/91726876/139636662-069465c9-7f15-43e8-b6f0-25bfa7d6ea9a.png)
![GX](https://user-images.githubusercontent.com/91726876/139642469-1d514b73-e22a-45a5-a29d-92cd39132a55.PNG)
![GY](https://user-images.githubusercontent.com/91726876/139642474-74543c5b-f386-4e03-98c3-85c6d4fee3c5.PNG)
![S6A](https://user-images.githubusercontent.com/91726876/139642476-b8af7078-dc88-4086-94d5-c12ac5441fbd.PNG)
![Magma PLMN](https://user-images.githubusercontent.com/91726876/139642703-032b2f07-f789-411e-837e-7cbc94bd7da5.PNG)


[Pcap log.zip](https://github.com/magma/magma/files/7451366/Pcap.log.zip)
[MME log.zip](https://github.com/magma/magma/files/7451375/MME.log.zip)

Any help to debug this issue will be of great help.

**Comment by vances** [comment]
At the moment SigScale OCS doesn't support three digit MNC but this is being corrected now.  See issue [OCS-458](https://sigscale.atlassian.net/browse/OCS-458). Why two digit and not three?  Because first request was for two.

**Comment by vances** [comment]
> At the moment SigScale OCS doesn't support three digit MNC but this is being corrected now. See issue [OCS-458](https://sigscale.atlassian.net/browse/OCS-458). Why two digit and not three? Because first request was for two.

This issue was resolve in SigScale OCS v3.2.11.
