### ISSUE TITLE
Re-enable timer tests for service restarts

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#9704]
Currently timer restart test cases for service restarts are commented out 

https://github.com/magma/magma/blob/580d692fac3180728f8e92f0d2b45dc2ce821d01/lte/gateway/python/integ_tests/defs.mk#L226

Can we fix the CI config to re-enable these?

**Comment by VinashakAnkitAman** [comment]
Hi @tmdzk We had commented out some of the long-running test cases because the CI execution was failing for timeouts. We want to re-enable those test cases as part of this issue. Can you please tell me what is the current CI execution timeout value, so that we can figure out if this is sufficient for enabling these test cases or we need to change CI timeout configurations?

Also it would be helpful if you can share the configuration file name where we are setting the CI timeout configurations.
