### ISSUE TITLE
Scale test: GUTI based registration is failing for more than 100UEs on TVM setup.

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#9727]
### Environment
Version:1.7.0-1634323180-c8e4d476
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: Vagrant (AGW)

Scale test: GUTI based registration is failing for more than 100UEs on TVM setup. The testcase is to perform scale test by increasing no.of UEs step by step (100,200,300...) upto 600 UE.  

**To Reproduce**
1. In TVM-GUI go to testcase SA_01_02_03_04_Hyper_Guti.
2. Execute testcase by increasing the number of UEs step by step(100,200,....)

 **Error Noticed**
For 100UEs basic flow is working. But testcase is failing if we increase no.of UEs more than 100. Observed that in pcap multiple registration and deregistration requests are happening and behavior is unstable.

**Expected behavior**
All UEs should get register, establish PDU session, and deregister successfully.

Please find the pcap and logs below:
[https://app.zenhub.com/files/170803235/5ed7b2af-6cbf-446d-8cd7-1ce84eac80f0/download](https://app.zenhub.com/files/170803235/5ed7b2af-6cbf-446d-8cd7-1ce84eac80f0/download)[https://app.zenhub.com/files/170803235/f1e13810-7b1e-44b6-baa0-c79926dcd701/download](https://app.zenhub.com/files/170803235/f1e13810-7b1e-44b6-baa0-c79926dcd701/download)

**Comment by rupa455wavelabs** [comment]
**Environment**
Version: 1.7.0-1639466782-178218a6
Affected Component: Access Gateway
Affected Subcomponent: AGW service

Executed SA_TC1_2_3_4_Hyper_Guti with 100UE and 200 UE with 12 GNB, 5 UE/sec, able to see the successful Registration, Deregistration, PDU Session Establishment/Release, but TestCase is failing due to UL/DL traffic.

Please check the below attached pcaps and logs for both 100 UE & 200 UE



[https://app.zenhub.com/files/170803235/f11b7154-85a0-44ba-a456-cfdbeb0cbc27/download](https://app.zenhub.com/files/170803235/f11b7154-85a0-44ba-a456-cfdbeb0cbc27/download)

**Comment by rupa455wavelabs** [comment]
![200GUTI_SESS.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/b7f3818e-296a-448a-871c-d440f17d5831)
![DEREG_GUTI.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/6b5dd1bc-5d5b-4a6b-b2ad-7a2cc670e59f)
![GUTI_200UE.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/704e1964-86b3-406e-b21d-946c7523fcac)
![GUTI_N6.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/7339d589-c2be-448b-947c-cf5721e451db)
![guti_pdu_200.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/915fec62-91a5-4b69-8510-8b99ecb6e4fd)

**Comment by Kaleem-Wavelabs** [comment]
@Chandhu-Wavelabs and @rupa455wavelabs This seems to be same as #11000.

**Comment by rupa455wavelabs** [comment]
Hi @Kaleem-Wavelabs, 
#11000 Zenhub issue is different than this issue, in this issue we tried GUTI based registration with 100 UE's on TVM setup. After that I tried to re-produce the same issue with 100UE(5 ue/s,12 Gnb), 200UE(5 ue/s, 12 Gnb) in TVM ,TC was failed due to traffic issue. 

In #11000 issue we tried GUTI Registration with 200 UE, 5 Ue/s in 30 loops.

**Comment by rupa455wavelabs** [comment]
Need to re-verify it in spirent setup and update the results.

**Comment by rupa455wavelabs** [comment]
Hi @all,
I re-tested GUTI based registration(200ue, 5ue/s, 10s ul/dl traffic) with latest magma build in TVM,I observed a slight drop in UL/DL traffic flow. Please check the below logs and pcaps for reference.
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/bd9c6b6b-29dd-4a86-958b-28215b200774)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/6de2da76-4e84-4887-8608-8e5bc5c77f9e)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/83b8873d-32f7-49d7-943a-0a43fb82022d)
Verdict log:
verification fail:  ((as_received_raw_bytes=32326000) 			>= (ue_sent_total_bytes=40024000)-((ue_sent_total_bytes=40024000)*0.01))  => False

**Comment by rupa455wavelabs** [comment]
[https://app.zenhub.com/files/170803235/a031cf6b-0069-4d0e-9ae5-b2ee576954f1/download](https://app.zenhub.com/files/170803235/a031cf6b-0069-4d0e-9ae5-b2ee576954f1/download)
