### ISSUE TITLE
Sessiond is showing as duplicate sessions even if the session is not available and denying the PDU-session.

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#9812]
SA_TC9_AMF_Initiated_Paging is failing in daily regression and manual testing. please find the logs and pcaps for the same below:
[https://app.zenhub.com/files/170803235/e076cf6c-574b-48b1-ad06-239d55f2101a/download](https://app.zenhub.com/files/170803235/e076cf6c-574b-48b1-ad06-239d55f2101a/download)[https://app.zenhub.com/files/170803235/d63b9a96-f0bf-4abf-92f9-b812295f6ff4/download](https://app.zenhub.com/files/170803235/d63b9a96-f0bf-4abf-92f9-b812295f6ff4/download)

**Comment by Kaleem-Wavelabs** [comment]
@GANESH-WAVELABS 
From the pcap and logs, can be seen that PDU create session ids are marked as duplicate though there are no PDU session created for this IMSI and eventually the rest of the case is failing.
Can you please look into how sessiond handles the duplicate PDU Ids though UE is not registered.
![image.png](https://images.zenhubusercontent.com/608bac58b7ba983c0fb15837/069d5bbd-782d-4a2c-9b08-6cf30bdbc390)
syslog:
Oct 20 23:40:42 TVM3-SA sessiond[199564]: I1020 23:40:42.668467 199564 SetMessageManagerHandler.cpp:256] Duplicate request of same PDU_id 5 of IMSI 222456000000101 nothing to do
Oct 20 23:40:58 TVM3-SA sessiond[199564]: I1020 23:40:58.670894 199564 SetMessageManagerHandler.cpp:256] Duplicate request of same PDU_id 5 of IMSI 222456000000101 nothing to do
Oct 20 23:41:14 TVM3-SA sessiond[199564]: I1020 23:41:14.673636 199564 SetMessageManagerHandler.cpp:256] Duplicate request of same PDU_id 5 of IMSI 222456000000101 nothing to do

mme.log:
Oct 20 23:41:30 2021 7FA9B26EF700 INFO  AMF-AP tasks/amf/prepare_request_for_sm:0116    Sending msg(grpc) to :[sessiond] for ue: [222456000000101] session
Oct 20 23:41:46 2021 7FA9B26EF700 INFO  AMF-AP tasks/amf/prepare_request_for_sm:0151    Sending msg(grpc) to :[sessiond] for ue: [222456000000101] session
Oct 20 23:41:46 2021 7FA9B26EF700 INFO  AMF-AP tasks/amf/prepare_request_for_sm:0116    Sending msg(grpc) to :[sessiond] for ue: [222456000000101] session

**Comment by GANESH-WAVELABS** [comment]
This is due to stateless feature enabled by default at sessiond side. so if previous session was received with some IMSI and PDU ID combination, and if UE request for PDU session establishment with same IMSI and PDU ID sessiond will search in redis and will get that combination already was present in redis. so sessiond treat it as duplicate request and it does nothing. so MME/AMF retrying to send PDU session establishment request. 

For the time being as a WorkAround disable the stateless feature with below commands:
Work Around:
Disable the stateless feature :
cd magma/orc8r/gateway/python/scripts/
magtivate
magmad_cli.py config_stateless disable
